### ISSUE TITLE
AFC-1225 Hide settings for the logged in user

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#172]
**Userstory:** 
As a user, I do not want to see these links, because the distract me from my work

**Module name:**
odoo-af/af_gui_disabeling

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Branch name:** 
12.0-AFC-1225-Hide-Gui-details

**Description:** 
This module disables the following links in the top-right corner of the GUI.
Documentation (invisble)
Support (invisble)
Preferences (debug only)
My Odoo-com-accont (invisble)
Logout (debug only)

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 

![image](https://user-images.githubusercontent.com/9428370/95622431-c8202a00-0a73-11eb-963b-0bfe60933995.png)

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I need to create new pull request from 12.0 or Dev-12.0?

**Comment by FredrikArvas** [comment]
Please always make the PR to Dev-12.0 for now. It might change in the future.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created pull request for this issue. https://github.com/vertelab/odoo-af/pull/188
Created new module af_gui_disabeling.

Here is output screenshots.

1. Without Debug Mode
![seeting_menu](https://user-images.githubusercontent.com/36560391/95652958-79759d00-0b12-11eb-94d5-7d860c16f579.png)

2. With Debug mode
![setting_menu2](https://user-images.githubusercontent.com/36560391/95652963-82666e80-0b12-11eb-88da-0b80860d472b.png)

3. Debug mode with assets.
![seeting_menu3](https://user-images.githubusercontent.com/36560391/95652968-8c886d00-0b12-11eb-8785-dbf1e2d492a1.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
This looks perfect. Thanks also for the screenshots. it is very easy for the tester to see what to expect when the code has been migreated into the customers environment.

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
