### ISSUE TITLE
IMP - Revert back the logotype in the af_backend_theme

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#175]
https://github.com/08arvasi/odoo-af_v3/tree/Dev-12.0/af_backend_tema

We have not got the placement of the Logotype in Odoo accepted by the Graphic-Design-team at the clients place. They say we are not allowed to use the logo like that. 
Could you please make a new branch and revert back to the normal Waffle?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created pull request for this issue.https://github.com/vertelab/odoo-af/pull/189

Here is screenshots:

![favicon](https://user-images.githubusercontent.com/36560391/95653865-67e3c380-0b19-11eb-8237-aed37b7efa87.png)

![waffle](https://user-images.githubusercontent.com/36560391/95653869-6d410e00-0b19-11eb-8779-ef6c5dd0acdc.png)

Please check it from your end and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
This looks good!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
