### ISSUE TITLE
AFC-1329 Link hr.department to res.partner

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#176]
**Userstory:** 
As a user, I want to see what department an address i related to, because I might want to understand where it belongs to.

Relationships: 
res.partner.department many2many hr.department.location

**Screen-shots:**
Image 1 = res.partner-form-view
![image](https://user-images.githubusercontent.com/9428370/99900761-c45a0700-2cb1-11eb-9c59-cd9e317c8e8c.png)

Image 2 = res.partner-sub-contact-form-view
![image](https://user-images.githubusercontent.com/9428370/99900636-13ec0300-2cb1-11eb-85d5-625cf9483fd4.png)

Image 3 = hr.department - form view
![image](https://user-images.githubusercontent.com/9428370/99900754-b6a48180-2cb1-11eb-997a-79e970be2d5e.png)

**Module name:**
odoo-hr/hr_departments_partner

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install module hr_departments_partner
Select any partner, link to Sales-department
Select a second partner, link to Sales-department
Go Sales-deparment => The two addresses should be listed

Test the same from the other direction
Select hr-department, link to any res.partner-with an address
Select delivery-department, link to the same res.partner-with an address
Go the respartner => The two departments should be listed

**Test-data:**

**Branch name:** 
12.0-AFC-1329-Link hr.department to res.partner

**Description:** 
This module adds a many2many-relationship between hr.department and res.partner

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by AnilKesariya** [comment]
@FredrikArvas : from which application view, you want to hide chatter functionality?

**Comment by FredrikArvas** [comment]
This is only a template for other issues. :-)

**Comment by nils-vertel** [comment]
@vertelab/n-development please estimate

**Comment by iammiracle** [comment]
Can we have a call on this, so i have a better understanding

**Comment by iammiracle** [comment]
[PR created](https://github.com/vertelab/odoo-hr/pull/26)

**Comment by FredrikArvas** [comment]
Thanks @iammiracle 
Please make this PR only with the new module.
Thanks

**Comment by iammiracle** [comment]
Nothing else was included in the PR, just the module I worked on

**Comment by FredrikArvas** [comment]
Hi again @iammiracle 
I see these changes
![image](https://user-images.githubusercontent.com/9428370/100498696-5b1c3d00-3164-11eb-9f16-2dedc84b5a40.png)
![image](https://user-images.githubusercontent.com/9428370/100498707-76874800-3164-11eb-9a6e-261f363ac0d5.png)

**Comment by iammiracle** [comment]
[PR Created](https://github.com/vertelab/odoo-hr/pull/27), the branch is **12.0-AFC-1329-Link-HR-Department-to-res-partner-CORRECT**

![image](https://user-images.githubusercontent.com/7355805/100514016-a721ae80-3171-11eb-922c-86acd121d211.png)

![image](https://user-images.githubusercontent.com/7355805/100514021-b274da00-3171-11eb-913f-351587ef2ddb.png)

![image](https://user-images.githubusercontent.com/7355805/100514036-c4567d00-3171-11eb-947b-6e2d60084ece.png)

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks
