### ISSUE TITLE
AFC-770 Hide the following menu-items for internal users

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#177]
**Userstory:** 
As a an internal user, I do not want to see the menu-items:
- Discuss
![image](https://user-images.githubusercontent.com/9428370/95628933-4e8e3900-0a7f-11eb-86e6-b528fd6dad72.png)

- Calendar
![image](https://user-images.githubusercontent.com/9428370/95629060-82695e80-0a7f-11eb-9108-c15f9e57a384.png)

- Contacts 
![image](https://user-images.githubusercontent.com/9428370/95629101-92813e00-0a7f-11eb-83e8-a026ceb57dbf.png)

- Website
![image](https://user-images.githubusercontent.com/9428370/95629127-a2008700-0a7f-11eb-9769-6656713c93c5.png)

We have other modules that adds other user-groups to the these standard-menues, but we have not managed to remove the "internal user" from them yet.

**Module name:**
odoo-af/af_core_menu_disabeling

**Branch name:** 
12.0-AFC-770-hide menues in Odoo Core

**Description:** 
This module removes the internal user from the following menu-items. \n
- Discuss
- Calendar
- Contacts 
- Website

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by AnilKesariya** [comment]
@FredrikArvas : I've created PR for this task.

**Comment by FredrikArvas** [comment]
Hi @AnilKesariya 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks
