### ISSUE TITLE
AFC-1024 Hide these Action-items

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#179]
**Userstory:** 
As a user, I do not want to see these "Actions" because I get confused by them.

**Module name:**
odoo-af/af_gui_disableing - for SMS  = Usergroup Technical Setting
https://github.com/vertelab/odoo-af/tree/Dev-12.0/contact_links - for Links = Usergroup LinkAdmin
https://github.com/vertelab/odoo-edi/tree/Dev-12.0/edi_af_aisf_rask - Update customer number = Usergroup Technical Setting

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Branch name:** 
12.0-AFC-1024 Hide Actions in GUI

**Description:** 
This module adds security settings to the Actions to hide them for normal users.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 

![image](https://user-images.githubusercontent.com/9428370/95629362-10454980-0a80-11eb-9a5d-adc4f4aad204.png)

**Comment by AnilKesariya** [comment]
@FredrikArvas : I don't have access to assign any of the issue

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

To hide action items based on user groups we need to add new field of res.groups in **ir.actions.server** and also need to add new record rule for **ir.actions.server.**

As these 3 action items are comes from different modules, it better to create common module for new field and record rule of ir.action.server. We will use these new module in depends of these 3 module which adds action items. So there will be no dependency issue in future.

**af_gui_disableing** module is not merged in Dev-12.0 branch. So when it merge I will create PR for this issue.

Please suggest me new module name and also please let me know your suggestion on this.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
I just checked that af_gui_disableing is merged now. Now waiting for approval on new module. Then will start work on it.

**Comment by FredrikArvas** [comment]
@robch2342  is this ok?

I apporove the new module. 
I suggest the name to be: 
af_rights_for_server_actions

**Comment by rupareliyahemangi145** [comment]
Thanks for approval @FredrikArvas. Can I start or should I wait for robch2342 replay?

**Comment by FredrikArvas** [comment]
I spoke to Robin and he implemented this feature in the af_security-module yesterday evening. So I close this issue for now.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
