### ISSUE TITLE
AFC-704 - Change target for "Close-button"

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#181]
**Userstory:** 
As a user, I want to come back to the "my start page" when I am finshed with the work of one Jobseeker.

**Current solution:** 
We have added a "close button" which calls for a method.
![image](https://user-images.githubusercontent.com/9428370/95647872-452ebc00-0ad3-11eb-96a6-98c867c3e217.png)

**Problem:** 
The current close button does not start from the start-button, but it starts with the former jobbseekers name still in "Memory".
![image](https://user-images.githubusercontent.com/9428370/95647900-8c1cb180-0ad3-11eb-9d82-fe36d9e78e1d.png)

**Module name:**
https://github.com/vertelab/odoo-base/blob/b2480e4b948e361299bad3db3da83af4072cfd5c/partner_view_360/views/res_partner_view.xml#L131

**Module type:** 
Resource module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Branch name:** 
12.0-AFC-704 - Change target for "Close-button"

**Description:** 
This fix changes the target for the "Close"-button so it directs to the main page, without remembering the former jobseeker.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas ,

Can you please provide me hr_office module? When I am trying to install partner_view_360 it gives error of hr_office.

Thanks.

**Comment by FredrikArvas** [comment]
The HR-module is available here:
https://github.com/vertelab/odoo-hr/tree/Dev-12.0/hr_office

To see which projects to download to the server -> See the [Readme-file](https://github.com/vertelab/odoo-af/issues/174). (and if something is missing there, please update it.)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas 

Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created pull request for this issue. https://github.com/vertelab/odoo-base/pull/135

Here is screenshot:
![close_button](https://user-images.githubusercontent.com/36560391/95654893-cbbdba80-0b20-11eb-9c42-f612b3825f96.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
