### ISSUE TITLE
AFC-86 - Create design templates for Mass Mailing module

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#182]
Userstory: 
As a Mass-mailing-user, I want to be able to select an "approved" email-template". 

Please create a mass_mailing_template that looks something like the below example:
![image](https://user-images.githubusercontent.com/9428370/92319272-951eec80-f016-11ea-9466-d368c7413704.png)
![image](https://user-images.githubusercontent.com/9428370/92319280-a1a34500-f016-11ea-8690-e9764d91dd36.png)
![image](https://user-images.githubusercontent.com/9428370/92319283-ab2cad00-f016-11ea-9f22-beb69be7aba2.png)
![image](https://user-images.githubusercontent.com/9428370/92319287-b1228e00-f016-11ea-8843-ae766821103c.png)

Here is some example-code on how to achieve it.
https://www.odoo.com/forum/help-1/question/how-to-create-a-template-for-mass-mail-150043

**Comment by FredrikArvas** [comment]
Hemangi comment: 
Hello @FredrikArvas ,

I have created template. Almost designing is done. I need some information form your side.

1. Subject for Mass mailing.

2. Image Urls for both images first which is left side of 'Visa i webblasaren' and second after that.
I have tried to add  static images by adding images in module but it doesn't works. So we need to images by url.

For now I have added two sample images using Url.

3. I need whole content in text file or doc file so I can copy and paste in module code. 

Here is screnshots of template design.

![template](https://user-images.githubusercontent.com/36560391/92901958-871a0300-f43e-11ea-902a-c6bcc643ba73.png)

![template_1](https://user-images.githubusercontent.com/36560391/92902053-96994c00-f43e-11ea-83da-360191a1358b.png)

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hemangi update: 
Hello @FredrikArvas 

I have create pull request. Added new module mass_mail_template.
https://github.com/08arvasi/odoo-af_v2/pull/42

Here is video to change images.
https://www.loom.com/share/b23f9a8041e3463cb715d6ee94393df8

Just double click on image it will open new popup and upload image.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi again, 
could you please check if this module is working as it should on this server.
https://fossa.vertel.se/web?debug#id=&action=275&model=mail.mass_mailing&view_type=form&menu_id=198

https://fossa.vertel.se/web?db=marketautomation_04


Please provide a screen-shot / instruction on how I can use it.
Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have installed module in https://fossa.vertel.se/web?db=marketautomation_04.

Step 1 Install module:
![app](https://user-images.githubusercontent.com/36560391/95722305-6210ee00-0c91-11eb-81ac-9f20d3d2e884.png)

When you install module it will add one mass mailing template in Email Marketing.(First one in below image.)
![mail_template](https://user-images.githubusercontent.com/36560391/95722735-eebbac00-0c91-11eb-9eea-db51b82d0568.png)

Step 2 Edit image or content(Describe how in following video link)
https://www.loom.com/share/839a1090db7d46658c5ab386cea12277

Please check it and let me know if anything.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks works fine

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
