### ISSUE TITLE
AFC-141 - Automatic Digital Customer Dialogue

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#183]
Userstory: 
I want to be able to send automated series of emails to "res-partners" based on records in the "daily_notes"-module.

Example: 
Email-Campaign 1: 
Newsletters to Jobseekers in Segment A.
Letter 1: Welcome to our agency.
Filer: All records in "partner_daily_notes" with (date = today) AND (Note_type = 90) select their "partners" where (Segment  = A). 

Send Email template Segement A letter 1.
![image](https://user-images.githubusercontent.com/9428370/91634962-d7cc3d80-e9f4-11ea-8115-adc7b226bc83.png)

![image](https://user-images.githubusercontent.com/9428370/91635019-35608a00-e9f5-11ea-98a1-b3ef5a00c456.png)

meeting : Sent three days before a booked meeting. (Booked meetings are recorded in the partner_daily_notes-module as "Registration Meeting" (or something similar).

Letter 2: Reminder of the meeting: Sent one day before a booked meeting. 
Letter 3: Follow up of the meeting: Sent three days after the meeting.

Sebastian have prepared these modules earlier, that I think you may use some code from. (We do not use these modules now)
odoo-base/event_auto_digital_dialogue 
odoo-base/event_auto_digital_dialogue_partner

_-----------

Here is the documentation to the **automatic_customer_dialogue**: 

After the installation of the module:

**Step 1**: Navigate to the Customer Dialogue and click on the menu

![image](https://user-images.githubusercontent.com/7355805/92953160-2b10a800-f459-11ea-989a-dd61be835778.png)

**Step 2**: Create an Event

**Step 3**: Fill in the Appropriate fields

![image](https://user-images.githubusercontent.com/7355805/92953296-6317eb00-f459-11ea-9d50-78db44f030f1.png)

**Step 4**: Save and let the event start running

![image](https://user-images.githubusercontent.com/7355805/92953352-7cb93280-f459-11ea-981f-cb1e21406146.png)

Once the event is active, then appropriate email will be sent as when due.

Note:

- The domain is already prefilled based on the condition of partners that have daily notes type of 90 and belong to Segment A. 
- At the point of creating a new partner daily note, if there is any record that is created today and meets the condition above, a Welcome email will be sent to them.
- On the Email Template lists, you can set when a particular email should be sent out and the email to be sent out.
- Once an event is ended, you can set the state to cancel and that marks the end of that event and any email that is meant to go out.

**Comment by FredrikArvas** [comment]
Jakob is working on this code.
https://github.com/vertelab/odoo-af/issues/183
https://github.com/vertelab/odoo-af/tree/12.0-AFC-141-ADKd

**Comment by FredrikArvas** [comment]
Hi Miracle, 
could you please test this module again, Jakob has merged it to the Dev-v12-branch from last Friday. 
And it needs some fixing. 
The Dev-v12-branch has been updated significantly today too.
sincererly
Fredrik

**Comment by iammiracle** [comment]
Hi Fredrik, I have looked into this issue, and I will like to be filled in with the latest update. Looking through what we have at this stage, I can see two modules in the **[odoo-base](https://github.com/vertelab/odoo-base/tree/Dev-12.0/)** repo and the modules relating to customer dialogues are: 

https://github.com/vertelab/odoo-base/tree/Dev-12.0/event_auto_digital_dialogue
https://github.com/vertelab/odoo-base/tree/Dev-12.0/event_auto_digital_dialogue_partner

The module I worked on is in the **[08arvasi](https://github.com/08arvasi/odoo-af_v2/tree/Dev-12.0)** repo which I think you are not using again: https://github.com/08arvasi/odoo-af_v2/tree/Dev-12.0

So can you please explain to me the fixes, I need to do.

**Comment by FredrikArvas** [comment]
Hi again, 
I hope you are feeling better. Please tell us if we can assist in any way. 

For these two old module: odoo-base/event_auto_digital_dialogue and odoo-base/event_auto_digital_dialogue_partner, they were "tests/prototypes" which are not intented to be used now. We only aim to use your module now. 

When it comes to the repositories, please work only with the github.com/vertel-repo now. The 08arvasi-repo shall be closed as soon as we have moved out of it. 

I will send you username and password to our testing-server fossa, where you can create databases and test code when it is working on your server. We use this server as "sys-test"-server before we take the code to "integration-test" inside the clients environment. 

Thanks
/Fredrik

**Comment by iammiracle** [comment]
Hi Fredrick, so I realized you created a branch for the automatic customer dialogue and I can see the module is renamed, can it be merged to the Dev-12 branch so I can update my repo and test?

https://github.com/vertelab/odoo-af/tree/12.0-AFC-141-ADKd/af_automatic_customer_dialogue

**Comment by iammiracle** [comment]
@FredrikArvas In addition to what Jakob has done, I have updated the module, it was given some errors in the process of Installation and After Installing. It is also working as expected based on the issue described

**Comment by FredrikArvas** [comment]
Hi @iammiracle 

We are reorganizing our modules and we would like to store this module in the odoo-mail-repository instead.
May I ask you to make a pull request to: 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0 instead
And we will most likely put this in use soon!

Thanks

**Comment by FredrikArvas** [comment]
This module is already merged!
https://github.com/vertelab/odoo-af/tree/Dev-12.0-Fenix-Sprint-02/af_automatic_customer_dialogue

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Please add your spent time
thanks
