### ISSUE TITLE
KPD-562 - Disable "the clickability" of the lines in a treeview

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#184]
**Userstory:** 
As a user, I do not want to be able to click on a line in this tree-view.
![image](https://user-images.githubusercontent.com/9428370/95650431-fdfcf700-0ae3-11eb-9e56-0af3aed183fd.png)

How is that changed?
Is there a generic tree-view-setting?

**Description:** 
The fix changes the setting of the Tree-view-line to not link to an other page.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 

Code: 
https://github.com/vertelab/odoo-af/blob/Dev-12.0/calendar_af_360/views/res_partner_view.xml
https://github.com/vertelab/odoo-af/blob/Dev-12.0/calendar_af_360/views/hr_employee_view.xml
https://github.com/vertelab/odoo-af/blob/Dev-12.0/calendar_af/views/calendar_appointment_view.xml
https://github.com/vertelab/odoo-af/blob/Dev-12.0/calendar_af/views/calendar_occasion_view.xml
https://github.com/vertelab/odoo-af/blob/Dev-12.0/calendar_af/views/calendar_schedule_view.xml

**Comment by AnilKesariya** [comment]
Hello @FredrikArvas ,

Can you help me to find hr_office module? **hr_office** module is depends on **partner_view_360** and **partner_view_360** is depends on **calendar_af**.

You try to install module 'partner_view_360' that depends on module 'hr_office'.
But the latter module is not available in your system.

Thanks.

Regards,
//Anil.

**Comment by FredrikArvas** [comment]
Partner_view_360 is in odoo-base -project. 
I will check that you have access to it also. 

To see which projects to download to the server -> See the [Readme-file](https://github.com/vertelab/odoo-af/issues/174). (and if something is missing there, please update it.)

**Comment by AnilKesariya** [comment]
I have access of odoo-base project. Thanks for hr_office module.

**Comment by AnilKesariya** [comment]
Hello @FredrikArvas ,

Created pull request for this issue.https://github.com/vertelab/odoo-af/pull/192

Prevent clicking from teeview from following views.

![appo](https://user-images.githubusercontent.com/5101994/95655782-4ab5f180-0b27-11eb-93e8-324cc18b7b3f.png)

![schedules](https://user-images.githubusercontent.com/5101994/95655790-54d7f000-0b27-11eb-975c-37ae7c44888c.png)

![occasions](https://user-images.githubusercontent.com/5101994/95655793-68835680-0b27-11eb-93aa-7f5597cafdd6.png)

Regards,
//Anil

**Comment by FredrikArvas** [comment]
Great!
It is easy when you know where to change stuff... Thanks!

**Comment by AnilKesariya** [comment]
Thanks @FredrikArvas

**Comment by FredrikArvas** [comment]
Hi @AnilKesariya 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks
