### ISSUE TITLE
KPD-551 - The "Breadcrumb" does not lead back to the start

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#185]
**Userstory:** 
As a user, I want to get back to the original search-form in the "My Administrative Office Area" - and in Search-mode.

Step 1:
![image](https://user-images.githubusercontent.com/9428370/95651174-b3ca4480-0ae8-11eb-9477-da52da7919c4.png)

Step 2: 
![image](https://user-images.githubusercontent.com/9428370/95651250-5da9d100-0ae9-11eb-8e9a-672ec3352f07.png)

Step 3: (should be the same as Step 1.
![image](https://user-images.githubusercontent.com/9428370/95651264-70bca100-0ae9-11eb-969a-57e55b536a60.png)

**Suggested solution:**
Link back to the same as the main meny (window-action search partner)
or
Disable the link on the step 2.

**Module name:**
https://github.com/vertelab/odoo-af/tree/Dev-12.0/hr_360_view

**Module type:** 
Application/Property/Resource/Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Branch name:** 
12.0-KPD-MyOffice-area-Breadcrum-link

**Description:** 
This fix changes the target link of the first breadcrumb in the This module 

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created pull request https://github.com/vertelab/odoo-af/pull/202 for this issue.

Disabled breadcrumb in step 2.

Step 1:
![step_1](https://user-images.githubusercontent.com/36560391/95709858-2ec46400-0c7d-11eb-98f1-079dbab770c9.png)

Step 2:
![step_2](https://user-images.githubusercontent.com/36560391/95709877-38e66280-0c7d-11eb-9a50-ca38cdc80271.png)

Please check it and let me know if anything.

Regards,
Hemengi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
