### ISSUE TITLE
KPD-614 - is it possible to display this tree-view in a calendar-view?

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#186]
**Userstory:** 
As a user, I want to see available bookable meeting-occations in a calendarview instead of a tree-view, because I am a lot more familiar with this kind of view.

Can the "tree" be exchanged to a "calendar"?

Step 1: 
![image](https://user-images.githubusercontent.com/9428370/95651699-618b2280-0aec-11eb-82a7-f2bcbf5d788e.png)

Step 2: 
![image](https://user-images.githubusercontent.com/9428370/95651719-94cdb180-0aec-11eb-9e5d-3096d87eaaa3.png)

**Module name:**
https://github.com/vertelab/odoo-af/blob/949f6fd269f8f3f1e57ec678e8ce44b888438ab8/calendar_af/views/calendar_appointment_view.xml#L149

Form: 
calendar.appointment.form

<field name="suggestion_ids" attrs="{'invisible':[('show_suggestion_ids','=',False)]}">
                        <tree string="Bookable Occasions" limit="10">
                            <field name="weekday"/>
                            <field name="start"/>
                            <field name="stop"/>
                            <field name="duration"/>
                            <field name="type_id"/>
                            <field name="occasion_ids" invisible="1"/>
                            <button name="select_suggestion" type="object" string="Book"/>
                        </tree>
                    </field>

**Branch name:** 
12.0-KPD-614-bookable_calendar-form

**Description:** 
This module changes the tree-view of the booking-form to a calendar-view.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas ,

I've tried to add Calendar view but it doesn't works. May be Odoo One2many field doesn't allow to add calendar view.

**Comment by AnilKesariya** [comment]
Calendar is not possible with one2many field on standard odoo structure. Insead we can display on main calendar view for specific detail of that record.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 and @AnilKesariya 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
