### ISSUE TITLE
KPD-578 Hide the "add line"-feature

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#187]
**Userstory:** 
As a user, I do not want to be able to "Add more alterntives to a dropdown-menu", or a tree-view. 

1 Filter out the "none"-alternative.
2 Hide the "Search and Add"-alternative
![image](https://user-images.githubusercontent.com/9428370/95652027-75d01f00-0aee-11eb-817b-c93c74a72b27.png)

3 hide the "add a line"-alternative.
![image](https://user-images.githubusercontent.com/9428370/95652077-e24b1e00-0aee-11eb-96d9-28d345aed246.png)

**Module name:**
https://github.com/vertelab/odoo-af/blob/Dev-12.0/calendar_af/views/calendar_appointment_view.xml#L149

**Branch name:** 
12.0-KPD-578-hide-add-a-line

**Description:** 
This fix disables the add-a-line-alternative in the bookable occasions tree-view.
It also filters out the "none"-alternative for channel.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created pull request for all 3 points mentioned in issue.https://github.com/vertelab/odoo-af/pull/195

For first point, 1 Filter out the "none"-alternative.
- I have removed it from code but you need to also Delete it one time  from your database.To delete it Go to Calendar -> Administration -> Channel.

Please check it and let me know if anything.

![appoint](https://user-images.githubusercontent.com/36560391/95656867-c9faf380-0b2e-11eb-98f8-600dd591dac3.png)

Thanks.

Best Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks for this. 
But the "channel=none" is used by the backend. 
Could you filter it out from the dropdown only?
thanks

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will filter it out from the dropdown only.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created new pull request https://github.com/vertelab/odoo-af/pull/201 to filter out from dropdown only.

These pull request contains all 3 points.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
