### ISSUE TITLE
AFC-1247 - change from Handläggaryta to Jobbsekers in Breadcrumbs

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#190]
**Userstory:** 
As a user, I want the Label "Handläggaryta" to be changed to "Jobbseeker".

![image](https://user-images.githubusercontent.com/9428370/95655013-a3c05e00-0b04-11eb-9a40-8e2da0ebbad1.png)

**Module name:**
https://github.com/vertelab/odoo-af/tree/Dev-12.0/hr_360_view
or 
https://github.com/vertelab/odoo-base/tree/Dev-12.0/partner_view_360
(I am not sure)

**Branch name:** 
12.0-AFC-1247

**Description:** 
This fix changes the first label in the breadcrumbs from Handläggaryta to Jobseekers.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created pull request https://github.com/vertelab/odoo-af/pull/205 for this issue. 

![breadcrumb](https://user-images.githubusercontent.com/36560391/95731993-d18cda80-0c9d-11eb-90ad-74600a7d63e4.png)


Please check it and let me know if anything.

Thanks.

Best Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
This is not right yet. See new Issue:
https://github.com/vertelab/odoo-af/issues/210

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
