### ISSUE TITLE
KPD-684 - can smart-buttons be made 30% wider?

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#194]
**Userstory:** 
As a user, I want the smart-buttons to be wider to allow the full display of longer labels in Swedish.

![image](https://user-images.githubusercontent.com/9428370/95656581-a4aabd00-0b0f-11eb-88b4-4d9077303fe4.png)

**Module name:**
Possible: 
https://github.com/vertelab/odoo-af/tree/Dev-12.0/af_backend_tema

**Branch name:** 
12.0-KPD-684-longer-smart-buttons.

**Description:** 
This fix expands the witdth of the frameworks smart-buttons with 30%

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created pull request https://github.com/vertelab/odoo-af/pull/206 for this issue.

![smart_button](https://user-images.githubusercontent.com/36560391/95734886-b4f2a180-0ca1-11eb-95c6-fb1ddd1b87e5.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 and @AnilKesariya 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time.
