### ISSUE TITLE
AFC-757 - Calendar-widget

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#200]
**Userstory:** 
As a user, I want to be able to filter the calendar-view based on multiple fields (not only users's calendars)
**Please use:**
"user_id"
"partner_id"
"location"
"office_id"
 
**in these views:**
External ID: calendar_af.view_calendar_appointment_local_calendar
External ID: calendar_af.view_calendar_occasion_calendar

--------------
Old history for the previous issue.

Hi Anil, 
Do you or anyone in your team have experience in JavaScript in this part of Odoo?
We have understood that this widget normally filters on the attribute: "color" in the <calendar>-tag in the XML-file for this view.

My personal suggestion (remember I am not a programmer) would be to add one extra selection-widget for each attribute we want to filter on.
Currently we are solving the issue by adding the parameters in the "filter"-section, but we like the widget. :-)
![image](https://user-images.githubusercontent.com/9428370/92071168-50911800-edae-11ea-8993-e41803da8c9d.png)

---------------
Hello @FredrikArvas 

I researched more about to add another attributes in calendar. Now it is showing Responsible where you want to add City and Addresses.

![calendar](https://user-images.githubusercontent.com/5101994/93181794-8e028780-f756-11ea-9524-9d4efa0d7381.png)

Instead of Responsible we can any other Many2one, Selection or Char field of calendar.event like Privacy, Location etc. But only can add one filter to add new one need to remove responsible.

For e.g., Here I have added Location.

![location](https://user-images.githubusercontent.com/5101994/93182563-737cde00-f757-11ea-8345-f4c874e5bf51.png)

Regards,
Anil.
----------------------

Hello @FredrikArvas 

I have tried to do these changes via code but when inheriting calendar view or replacing calendar view it doesn't works.

When edit calendar view directly in Database it works. If we want to change filter from Responsible(partner_id) to Location(location) we need to change color attribute of calendar view from color='partner_id' to color='location'.

**Module name:**
odoo-af/calendar_af

**Branch name:** 
12.0-AFC-757-calendar-selection-widget

**Description:** 
This module adds multiple attributes for the calendar-wiew

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by FredrikArvas** [comment]
Hi Hemangi
Could you please try again to add these "filter-widgets" with the attributes listed in the top of the issue?
Thanks

**Comment by FredrikArvas** [comment]
We close this issue, since it is not possible with the current fields.

**Comment by FredrikArvas** [comment]
I think I closed this by mistake.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

This is bit R&D topics, couldn't assume will be a quick fix or not. Also couldn't estimate time. I need to your approval on this to move forward.

**Comment by FredrikArvas** [comment]
We will choose an other way forward.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Didn't spent more time just asked for approval.
