### ISSUE TITLE
[Bug] hr_360_view KPD-551 - the breadcrumb does not come right yet

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#210]
Step 1 - search for a partner
![image](https://user-images.githubusercontent.com/9428370/95786770-893ede00-0cd8-11eb-8412-b0e559188719.png)

Step 2 - 
![image](https://user-images.githubusercontent.com/9428370/95786900-bee3c700-0cd8-11eb-9706-563639362720.png)

Result: Search-widget in "passive mode"
![image](https://user-images.githubusercontent.com/9428370/95786949-d7ec7800-0cd8-11eb-9b40-5672257c84af.png)

Expected: - Search widget in "active mode".
![image](https://user-images.githubusercontent.com/9428370/95787036-02d6cc00-0cd9-11eb-8eca-60c4fa7fc2b1.png)

The button "Close" works looks to be working fine - but it does not.

Example of strange result after some testing:
![image](https://user-images.githubusercontent.com/9428370/95786819-9b208100-0cd8-11eb-9493-d894eb1ca25d.png)
![image](https://user-images.githubusercontent.com/9428370/95787719-60b7e380-0cda-11eb-8259-7fb44112ea56.png)

Please also change the manifest to only have one line per update and please add the Jira-key. 
![image](https://user-images.githubusercontent.com/9428370/95787201-4f220c00-0cd9-11eb-9057-ec6a6fb5c059.png)

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created pull request for this issue. https://github.com/vertelab/odoo-af/pull/212.

Here attached video link to show how it works in my local.
https://www.awesomescreenshot.com/video/1330432

Please test it from you end and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks for this suggestion. Sebastian solved the same issue from an other perspective, without knowing you had solved it. So we will keep this code for the future.
