### ISSUE TITLE
hr_360_view AFC-1259 Refactoring of search form

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#211]
**Userstory:** 
As a user, I want a "normal search page", not a form that sometimes remembers previous searches.

I want one form for "when in contact" and one form for "Based on the needs of the authority". 
Both forms should lead to the Jobbseeker-form as it does today. 
Both forms should activate the credentials-actions
Both forms should activate the extended logging

Bot the new form should not require "edit-mode", or remember the previous searches etc.

![image](https://user-images.githubusercontent.com/9428370/95789956-c3ab7980-0cde-11eb-8b0b-bd75e8dedd73.png)

**Do you have any suggestions on how to implement this?**

**Module name:**
odoo-af/hr_360_view

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Branch name:** 
12.0-AFC-1259-refactoring-of-Jobbseeker-search-form

**Description:** 
This upgrade changes the form from a wizard to a... to enable better function of the search-form.

**Estimate:** 
Estimated Hours: 
Estimated Date: asap.
Actual Hours:

**Comment by AnilKesariya** [comment]
Hello @FredrikArvas 

If you want to split both "when in contact" and  "Based on the needs of the authority" then we can do it. Need to add two separate menus for both.

I you want to separate both with different menu then time estimation is near about 3 hours.But after separation this will look like same it is now just difference of separate functionality only one tab for each menu.

If you want to separate only because of bredcrumb issue and editor mode issue then Hemangi has fixed that issue in https://github.com/vertelab/odoo-af/issues/210.

Thanks.

Regards,
//Anil.

**Comment by FredrikArvas** [comment]
Hi Anil, 
Yes, please, could you try to do this for us?
best regards
Fredrik

**Comment by AnilKesariya** [comment]
Yes @FredrikArvas 

I will add two different menus for two tabs. These menu are inside My Administrative Area? or any other place?

**Comment by FredrikArvas** [comment]
Hmm. I am not sure what I want. 
If you do a first test with two menues in the top-navigation beside the current "My Administrative Area".
![image](https://user-images.githubusercontent.com/9428370/95944963-c1821180-0de9-11eb-8c17-8e8db14b308b.png)

**Comment by AnilKesariya** [comment]
Yes @FredrikArvas these pages will serve as parallel solutions. I will add two menus inside current "My Administrative Area" as mentioned.

**Comment by AnilKesariya** [comment]
Hello @FredrikArvas 

Created pull request https://github.com/vertelab/odoo-af/pull/218 for this issue.

Added separate menus for both tabs.

![contact](https://user-images.githubusercontent.com/5101994/95959927-bd251b00-0e20-11eb-8f08-7da6693e3515.png)

![authority](https://user-images.githubusercontent.com/5101994/95959943-c2826580-0e20-11eb-921d-3505ecc4bc87.png)

Please test it from you end and let me know if anything.

Thanks

Regards,
//Anil.
