### ISSUE TITLE
Upgrade of code quality to prepare for automatic code test

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#221]
Hi 

step 1: Clean code module by module
step 2: When all modules are cleaned
step 3: Install automatic testing on a copy-repo 
step 4: when this is approved, then we add the automatic testing on our repo

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created following pull request to update code quality. Created PR module by module.

https://github.com/vertelab/odoo-af/pull/229
https://github.com/vertelab/odoo-af/pull/230
https://github.com/vertelab/odoo-af/pull/231
https://github.com/vertelab/odoo-af/pull/232
https://github.com/vertelab/odoo-af/pull/233
https://github.com/vertelab/odoo-af/pull/234
https://github.com/vertelab/odoo-af/pull/235
https://github.com/vertelab/odoo-af/pull/236
https://github.com/vertelab/odoo-af/pull/237
https://github.com/vertelab/odoo-af/pull/238
https://github.com/vertelab/odoo-af/pull/239
https://github.com/vertelab/odoo-af/pull/240
https://github.com/vertelab/odoo-af/pull/241
https://github.com/vertelab/odoo-af/pull/242
https://github.com/vertelab/odoo-af/pull/243
https://github.com/vertelab/odoo-af/pull/244
https://github.com/vertelab/odoo-af/pull/245
https://github.com/vertelab/odoo-af/pull/246

Some modules are still remaining, I'll do it tomorrow.

Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created following pull request to update code quality for remaining modules. Created PR module by module.

https://github.com/vertelab/odoo-af/pull/250
https://github.com/vertelab/odoo-af/pull/251
https://github.com/vertelab/odoo-af/pull/252
https://github.com/vertelab/odoo-af/pull/253
https://github.com/vertelab/odoo-af/pull/254
https://github.com/vertelab/odoo-af/pull/255
https://github.com/vertelab/odoo-af/pull/256
https://github.com/vertelab/odoo-af/pull/257
https://github.com/vertelab/odoo-af/pull/258
https://github.com/vertelab/odoo-af/pull/259
https://github.com/vertelab/odoo-af/pull/260
https://github.com/vertelab/odoo-af/pull/261
https://github.com/vertelab/odoo-af/pull/262
