### ISSUE TITLE
KPD-668 - Hide the meeting-time

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#222]
**Userstory:** 
As a user, I do not want to 

The code controlling this is the override of name_get() in calendar_af/models/calendar.py

**Screen-shots before:**
![image](https://user-images.githubusercontent.com/9428370/95976606-0e7cdc80-0e18-11eb-84c9-45343085a192.png)

**Screen-shots after:**

**Module name:**
odoo-af/calender_af

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-668-...

**Description:** 
This module 

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by DanielEriksson11** [comment]
The code controlling this is the override of name_get() in calendar_af/models/calendar.py

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-af/pull/225 for this issue.

![meeting](https://user-images.githubusercontent.com/36560391/96079489-8576ab80-0ed2-11eb-98d1-220b19642ef1.png)

Please check it and let me know if anything.

Thanks. 
Regards,
Hemangi.
