### ISSUE TITLE
KPD-580 time in the breadcrumd shows UTC (wrong) and the time in the tree-view shows CET (right)

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#223]
**Userstory:** 
As a user, I the meeting-time and the breadcrumb-time to show different times.

**Screen-shots before:**
![image](https://user-images.githubusercontent.com/9428370/95978213-29505080-0e1a-11eb-9e44-13ec38f9645b.png)
![image](https://user-images.githubusercontent.com/9428370/95978247-32d9b880-0e1a-11eb-84ee-954cde01b2df.png)

**Screen-shots after:**

**Bugreport:**
Steps to reproduce and where in the system the defect is located...

**Module name:**
odoo-af/af_

**Module type:** 
Application/Property/Resource/Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integration:**

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1XXX-...

**Description:** 
This module 

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

We have already remove meeting time from breadcrumb in issue https://github.com/vertelab/odoo-af/issues/222.

So I think no need to work on this issue. Please check it and let me know.

Thanks.

Best Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks, 
that is right. 

I need to change the specifications for the other Issue, since we still need the Meeting-time to be present. I just need figure out exact where and when. 

/Fredrik

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
