### ISSUE TITLE
AFC-1267 - Fix meetinglists links to form-views.

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#224]
**Userstory:** 
As a user, I do not want to open meetinglines to forms

*Screen-shots before:*
 

*Screen-shots after:*

**Bugreport:**
Steps to reproduce and where in the system the defect is located...

**Robin explaines more:** 
There is no easy  way to stop the One2Many widget from opening the rows without breaking it.
We must modify the widget in order to implement this feature.
On "Many2One"-fiels there is the option no_open, but it does not work on "One2Many"- or "Many2Many"-fields.
Example: <field name="some_field" options="{'no_open': True}"/>

**Example-code:**
This code makes it possible to use the no_open setting on a "One2many"-fields.
/web/static/src/js/fields/relational_fields.js
**Widget** FieldOne2Many on row 1402 (give or take a couple of lines between Odoo versions)
**Method** _onOpenRecord on row 1559
I have added this part and made sure it works
// The magic starts here
        if (this.nodeOptions.no_open) {
            return;
        }
        // The magic ends here

The entire function looks like this:
/**
     * Overrides the handler to set a specific 'on_save' callback as the o2m
     * sub-records aren't saved directly when the user clicks on 'Save' in the
    * dialog. Instead, the relational record is changed in the local data, and
     * this change is saved in DB when the user clicks on 'Save' in the main
     * form view.
     *
     * @private
     * @param {OdooEvent} ev
     */
    _onOpenRecord: function (ev) {
        // we don't want interference with the components upstream.
        var self = this;
        ev.stopPropagation();
        // The magic starts here
        if (this.nodeOptions.no_open) {
            return;
        }
        // The magic ends here

        var id = ev.data.id;
        var onSaved = function (record) {
            if (_.some(self.value.data, {id: record.id})) {
                // the record already exists in the relation, so trigger an
                // empty 'UPDATE' operation when the user clicks on 'Save' in
                // the dialog, to notify the main record that a subrecord of
                // this relational field has changed (those changes will be
                // already stored on that subrecord, thanks to the 'Save').
                self._setValue({ operation: 'UPDATE', id: record.id });
            } else {
                // the record isn't in the relation yet, so add it ; this can
                // happen if the user clicks on 'Save & New' in the dialog (the
                // opened record will be updated, and other records will be
                // created)
                self._setValue({ operation: 'ADD', id: record.id });
            }
        };
        this._openFormDialog({
            id: id,
            on_saved: onSaved,
            on_remove: function () {
                self._setValue({operation: 'DELETE', ids: [id]});
            },
            deletable: this.activeActions.delete,
            readonly: this.mode === 'readonly',
        });
    },

We DO NOT want to edit the web module directly.
Move this check to a separate module.
The JS will look something like this:

odoo.define('some.new.module.name.relational_fields', function (require) {
var relational_fields = require('web.relational_fields');
relational_fields.FieldOne2Many.include({
                   _onOpenRecord: function (ev) {
                                     if (this.nodeOptions.no_open) {
                                                        ev.stopPropagation();
            return;
        }
                                     this._super.apply(this, arguments);
                   }
});
return relational_fields;
});

Do the same for Many2Many. It is also born in relational_fields.js. It seems to work a bit differently, so some experimentation is in order.
Make sure the JS is loaded directly after the original relational_fields.js in web.assets_backend.

Mvh
Robin

**Module name:**
odoo-af/noopen_one2many

**Module type:** 
Resource module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Jobbseekers -> Pick one person -> Go to meeting-tab -> Create new meeting -> Click on meeting-alternatives = should not open a form-view.

**Test-data:**
-

**Branch name:** 
12.0-AFC-1267-no-open-option-one2many

**Description:** 
This module adds the option to disable opeing of form-views for one2many fields in tree-views.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by AnilKesariya** [comment]
Hello @FredrikArvas 

I want to confirm about this issue, I need to create new module **noopen_one2many** and need to put JS code which suggested in issue and need to test, right?
