### ISSUE TITLE
AFC-1229 - Dashboard Fenix

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#268]
**Userstory:** 
As a user, I want to see the dashboard of my working platform for my daily tasks.

**Requirements:** 
1. The logged in user should always see a welcome text on the dashoard main page, greets logged in user by name
2. Dashboard layouts(cards) is a placeholder at the moment. The dashboard module should allow for dynamic content to be added  (example: cards that contain links, images, graphs for statistics purposes, messages etc.).

**Screen-shots before:**

![image](https://user-images.githubusercontent.com/9428370/96707928-ca9a5200-1398-11eb-8498-af218c111bcc.png)
[Startvy - engelska.pptx](https://github.com/vertelab/odoo-af/files/5416959/Startvy.-.engelska.pptx)

![image](https://user-images.githubusercontent.com/9428370/96460253-4ecac900-1223-11eb-9d84-fe1072fd9fa3.png)

**Screen-shots after:**

**Bugreport:**

**Module name:**
odoo-af/fenix_dashboard

**Module type:** 
Application type

**Integration:**

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1229

**Description:** 
This module shows the dashbord of an employee´s daily work.

**Estimate:** 
Estimated Hours: 12 hours
Estimated Date:
Actual Hours: - 11

**Comment by FredrikArvas** [comment]
Please check it.

1. https://www.loom.com/share/6143ef5747284001a46259ed1ff32822
2. https://www.loom.com/share/29992d09b8274aac9284dbaa411cbbb3
3. https://www.loom.com/share/9c9a939155244ea4a4488197e51d68f6
4. https://www.loom.com/share/04a85f7b013d4f57926edf46cb02f990

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Thanks for these examples. Would it be possible to have a static text-box as well?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I checked only static text is not possible. You can add Tile without icon and add domain **id is not** set but with that tile will show zero every time.

![static_text](https://user-images.githubusercontent.com/36560391/97414411-f766e000-1929-11eb-835e-d76fac62b40c.png)

**Comment by FredrikArvas** [comment]
Ok, that was not as I hoped.

Is it poosible to use the same kind of code as this page?
![image](https://user-images.githubusercontent.com/9428370/97424391-ee1d4980-1910-11eb-8e2f-98c11ea5b118.png)

**Comment by rupareliyahemangi145** [comment]
With this module or in separate module?

It is possible to create same kind of code in new module with static menu.

**Comment by rupareliyahemangi145** [comment]
I will do it.

**Comment by Radhika435** [comment]
Hi Hemangi,
could you please let me know the status on this soon.

**Comment by rupareliyahemangi145** [comment]
I am working on this. I will give you screenshot of look today.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

Here is video link for dashboard which I have prepared:
https://www.loom.com/share/9136153d9b5342c8b96517adb6d02802

Please check it and let me know your suggestions on this.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
This is brilliant!
Now we know it is possible, let us speak to the design-team on what they really want.

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas

**Comment by FredrikArvas** [comment]
![image](https://user-images.githubusercontent.com/9428370/97773326-fb277c00-1b4e-11eb-80c2-406f5ac1552b.png)

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 Could you please make a push request with this code now. It is not ready for release yet, but it is ready to be installed on our test-server fossa.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Let me create PR for this.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Create PR https://github.com/vertelab/odoo-af/pull/311 for this issue.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks!

**Comment by FredrikArvas** [comment]
Hi Hemangi
We spoke to the client today and showed the dashboard. 
They approved the initial work and would like these changes:
- we would like a configurable content in each box.
- we would like the boxes to be "aware" of user-groups. So some groups only are visible for managers etc.

Suggestion: 
Create a list with the content of the boxes and the top-message.
Add priority, user-groups to these records.
Content of the boxes could be HTML or similar rich text.
Thanks

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas  I will do it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I understood these changes but before start work on changes I want approval on time estimation.
I've spent 4 hours in analysis of base requirement, analysis of new changes, discussion and initial development.

I need 4 to 5 hours for new changes. In new development user can configure each content, also can add different content for each user, can add multiple boxes based on user groups. Whole dashboard will be configurable based on user.

Please check it and let me know so I can start work on new changes.

Thanks.

Best Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi Hemangi, 
I approve the solution and the estimate. Please record the actual times you have spent along the way.

Thanks

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-af/pull/333 for new changes.

Added new User Group - **My Dashboard Manager**.
User can see new menu - **My Dashboard Configuration** If user has this group.

When user click on **My Dashboard Configuration** menu he can see records for all user's dashboard.

Inside each user record, Dashboard manager can configure each and every content.

For images in boxes I've used fa-icon(https://fontawesome.com/v4.7.0/icons/)  instead of image. Because to list dynamic boxes I've used One2many field type and image of One2many is not accessible.
One2many is also not accessible in kanban that's why I've used **web_one2many_kanban** OCA module. Added module in this PR.

Here is videos to show how changes works:
https://www.loom.com/share/e673f845ca0a4cd991f3733298781bdf
https://www.loom.com/share/b639706e23634b0e92372e04c86957d4

Please check it and let me know if anything.

Thanks.

Best Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Spent time: 4 hours and 50 mins

**Comment by FredrikArvas** [comment]
Thanks you Hemangi
This looks promising.

Is the content now uniqe for each person?
Or can we have the same content for members of a group?

I am afraid we need to configure 500 messages, if we have 500 employees. :-)

**Comment by rupareliyahemangi145** [comment]
Yes content is unique for each person. For now I've set default content in Welcome message and Welcome description.
But for boxes you need to configure boxes in each person.

Let me analysis to configure box at a time for more than one user, If client want to use same box for multiple users based on user group or name.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 
I've analyzed I can add new menus to update same content in selected users. So don't need to add same content in more than one user if want same content in more users.

It will take 2 or 3 hours. Can I start work on it?

**Comment by FredrikArvas** [comment]
Hi again, 
Yes, I think this is a good solution for this.

Or is it possible to link the content on the user-group and then display the "user's group's" content?

Either way is ok to proceed.

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas. I will check to link the content on the user-group and then display the "user's group's" content.

I will start work.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-af/pull/336.

Here is video to show how to update content at a time for more than one user.
https://www.loom.com/share/c94a684094344e0695f984f1c1d3b530
https://www.loom.com/share/e8cf3515f777412880a8f96b2950b44d

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Spent time: 2 Hours and 50 Min with analysis and development

**Comment by FredrikArvas** [comment]
Hi
please close the PR https://github.com/vertelab/odoo-af/pull/336  and create a new with a new module-name here 
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02 with the new name web_dashboard_fenix
thanks

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Create PR https://github.com/vertelab/odoo-web/pull/2 and closed https://github.com/vertelab/odoo-af/pull/336.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment]
#476

**Comment by Radhika435** [comment]
Hi Hemangi,
In the above comment I have linked a issue for further changes on the dashboard.
please check and let me know if anything.

BR,¨
Radhika.
