### ISSUE TITLE
AFC-1278 - Price-list with links to project and activities

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#269]
**Userstory:** 
As a user, I want an a pricelist with articles that create projects' activities

**Examples of Products:**

"ID";"Name";"Tax-code","Price-Currency"
"kvd_01";"Carreer advice";"VAT_25","10 SEK"
"kvd_tlk_01";"Interpretor - Arabic";"VAT_25","10 SEK"
"kvd_tlk_02";"Interpretor - Finnish";"VAT_25","10 SEK"

**Project template**
Project Name = "The customers name" inlcuding Task = "Task1",  "Task2" , "Task3",
Interpretation Task = "Interpretation AA", Add time-reporting.

**Screen-shots after:**

**Module name:**
odoo-sale/af_sale_orders

**Module type:** 
Resource [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Testing steps:**
When I apporove a sales order with Carreer Advice, a project should be initated.
When I apporove a sales order with Interpretation, a project activity should be added.

**Test-data:**

**Branch name:** 
https://github.com/vertelab/odoo-sale/tree/12.0-AFC-1278-price-list

**Description:** 
This module adds a price list, articles and project templates.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 8 hours and 40 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I understood about Articles that we need to create new model with following Articles demo data.
"kvd_01";"Carreer advice";"VAT_25","10 SEK"
"kvd_tlk_01";"Interpretor - Arabic";"VAT_25","10 SEK"
"kvd_tlk_02";"Interpretor - Finnish";"VAT_25","10 SEK"

And need to add new selection in sale order for above Articles.

I am bit confused in Project and it's activity creation.
When I apporove a sales order with Carreer Advice, a project should be initated.
When I apporove a sales order with Interpretation, a project activity should be added.

Project template
Project Name = "The customers name"
Activities = "Activity 1", "Activity 2" , "Activity 3",
Interpretation Activities = "Interpretation AA", Add time-reporting.

For Career Advice,
Understood need to create project with customer name.

 About Activities: need to create new Activity types for project?
![activities](https://user-images.githubusercontent.com/36560391/96702787-b9a90b00-13af-11eb-89fd-6feb211f7f38.png)

And what is Interpretation Activities? Is this filed which added by any other module? or need to add new field in activity? 

For Interpretation, Need to create project activity but for which project?

In Carreer Advice need to create only project? and in Interpretation need to create activities in any project?

Regards,
Hemangi

**Comment by FredrikArvas** [comment]
Please join this meeting link.
http://meet.jit.si/af_project_fenix

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-af/pull/278 for this issue.

Here is screenshots:
1.Sale order with both products and related project and tasks.

![sale_both](https://user-images.githubusercontent.com/36560391/96716739-0ea24c80-13c3-11eb-97a9-f3540e52d11f.png)

![both_sale_with_task](https://user-images.githubusercontent.com/36560391/96716765-182bb480-13c3-11eb-91c7-5cbe58eba884.png)

2.  Sale order with Carreer advice and related project.

![one_sale](https://user-images.githubusercontent.com/36560391/96716821-2e397500-13c3-11eb-8d78-a0b614dc1057.png)

![one_sale_project](https://user-images.githubusercontent.com/36560391/96716872-44dfcc00-13c3-11eb-84f7-53cc8ea27ccb.png)

3. Sale with Both type of product and related Project, tasks

![both_sale_2](https://user-images.githubusercontent.com/36560391/96716923-5cb75000-13c3-11eb-90e9-57c00b5aa06c.png)

![both_sale_proj_2](https://user-images.githubusercontent.com/36560391/96716936-60e36d80-13c3-11eb-8482-085b397da228.png)

Please test it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Please add time spent on this issue. We use it to learn to estimate for the future. Thanks / Fredrik

**Comment by rupareliyahemangi145** [comment]
Spent time: 2 hours.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145 @AnilKesariya 
Previously we worked on the solution to create tasks in project module when an order is created. 

In detail when an order is created and product is added to the order then three tasks are created in the project module.
(Project Name = "The customers name" inlcuding Task = "Task1", "Task2" , "Task3",)

Now we have another user story **when I approve a sales order with Career Advice, a project should be initiated.
and when I approve a sales order with the products added, then 9 + 4 tasks must be created so in total 13 tasks and sh

First 9 tasks are required tasks and 4 tasks are optional tasks and we should see the difference between the Required 9 tasks and 4 options tasks by using some colour. (suggestion needed)

The title of the Tasks from 1 to 13  must be default title for every Project created.

On project ,task and sub-task must contain  Start date , End date. 

The calendar view must be show  for  **project -> calendar view based on start date

                                                               **Task -> calendar view based on start date
                                                                
                                                               **Sub-Tasks>calendar view based on start date


Attaching the pictures based on user story,
![image](https://user-images.githubusercontent.com/59916603/98801703-7a9c3180-2412-11eb-99ca-57ddc2d61907.png)

Picture from Odoo
![image](https://user-images.githubusercontent.com/59916603/98802635-ddda9380-2413-11eb-9c47-dc1246d9670f.png)

Last but not least 
 
All projects should have the common stages for the tasks (Default stage for all the projects)

//let me know your comments //

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435 I will check it.

**Comment by FredrikArvas** [comment]
Here is an image from a mockup Rahdika and I made today.
![image](https://user-images.githubusercontent.com/9428370/98855549-78f75b80-245c-11eb-9567-d183ccf19a9e.png)
We experimented with a way of illustrating the mandatory/optional and the task/sub-tasks.

Please show a screen shot of your proposals when you have something to show. 
Thanks

**Comment by rupareliyahemangi145** [comment]
Thanks for image from mockup @FredrikArvas Sure I'll share screen shot.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas and @Radhika435 

I've worked on new requirement and here are screenshots:

1. Sale order with **Carreer advice** product.
![sake_carreer](https://user-images.githubusercontent.com/36560391/98936263-badedb00-250a-11eb-964a-7c685a0162ae.png)

Project for **Carreer advice** product.
![project_sale_carreer](https://user-images.githubusercontent.com/36560391/98936306-cdf1ab00-250a-11eb-8548-677bb5cf6bb4.png)

2. Sale order with **Carreer advic** and **Interpretor - Arabic** product.
![sale_carreeer_other_prod](https://user-images.githubusercontent.com/36560391/98936410-ef529700-250a-11eb-98d2-344603505270.png)

13 Tasks for **Carreer advic** and **Interpretor - Arabic** product sale.
![project_carreer_other_product](https://user-images.githubusercontent.com/36560391/98936466-02656700-250b-11eb-85f0-0297ad4cbfbc.png)

3. Warning if user try to remove any of 9 required task.
![warning_required_task](https://user-images.githubusercontent.com/36560391/98936579-29239d80-250b-11eb-9a54-b870030a771c.png)

3. Added start date and end date inside project, task, sub-task form, list and kanban view.

**Project Form**
![project_from](https://user-images.githubusercontent.com/36560391/98937069-e6ae9080-250b-11eb-952d-d4fe94ab24b5.png)

**Project List View**
![project_tree](https://user-images.githubusercontent.com/36560391/98937108-f5954300-250b-11eb-90af-eb50175ed0c7.png)

**Project Kanban**
![project_kanban](https://user-images.githubusercontent.com/36560391/98937139-ff1eab00-250b-11eb-97d6-142f725f3eb9.png)

![project_kanban_2](https://user-images.githubusercontent.com/36560391/98937155-02b23200-250c-11eb-81d3-14a24d1444dc.png)

**Task List view**
![task_tree](https://user-images.githubusercontent.com/36560391/98937181-0ba30380-250c-11eb-8924-aad439995728.png)

**Task Form view**
![task_form_view](https://user-images.githubusercontent.com/36560391/98937210-152c6b80-250c-11eb-9d97-22936da21331.png)

**Task Kanban view**
![task_kanban](https://user-images.githubusercontent.com/36560391/98937236-1e1d3d00-250c-11eb-9be5-c2cde3d2ae67.png)
Please check it and let me know if anything.

Remaining point is:
We want the calendar view to show **project -> calendar view based on start date to end-date
**Task -> calendar view based on start date-time to end-time
**Sub-Tasks>calendar view based on start date-time to end-time
(The current Calendar view displayes due-date as a "full-day"-event.
- I will do it and send you screenshot also for that.

Thanks.

**Comment by FredrikArvas** [comment]
Hi, 

it looks good!

Do you have any suggestion to visually differentiate between task and sub-task?

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas I will check it and let you know If I found anything for visually differentiate task and sub-task.

**Comment by Radhika435** [comment]
Hi Hemangi,
I am glad with your screen shots.

1. I also wanted to see the default project stages on each and every task created. I mentioned on the picture as well.
Please find the pictures below,
![image](https://user-images.githubusercontent.com/59916603/98944194-fa003280-24f0-11eb-89c1-65a44027196a.png)

2.From the user story I wanted to see the difference between the Required tasks,Optional tasks and the sub-tasks (created from the required tasks) described in detail on the picture as well.
Please find the pictures below,
![image](https://user-images.githubusercontent.com/59916603/98946556-50bb3b80-24f4-11eb-9c85-8ebd4cdd0050.png)

Please give us a suggestion on how to fix this, with third-party-module or fix.

@FredrikArvas FYR ( if I need to add more/ miss something)

//let me know your suggestions//

Thanks & best regards,
Radhika

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435 I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

I've added tasks in default 'New' stage also added two fields inside task to differentiate task and sub tasks. Which are **Main task number** and **Parent Task**. You can give task number to main required tasks like 1,2,3,4 etc. and in sub task can set its parent task.

Here is videos to show functionality which I've done:
 https://www.loom.com/share/b88f1427980440bea5a0ba477dea7be1
https://www.loom.com/share/03944b10573540ddbc424c7d9538491f

Please check it and let me know if anything.

Thanks.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145 
Can we take a meeting to discuss about this in detail.

Please join this link at 11 CET 
http://meet.jit.si/swedishemployementserviceagency_project

**Comment by rupareliyahemangi145** [comment]
Yes Sure @Radhika435 Just want confirm 11 CET means 3:30 PM IST, right?

**Comment by Radhika435** [comment]
@rupareliyahemangi145 Yes at 3.30 IST 👍 
we can now also if you have time.

Let me know reply

**Comment by rupareliyahemangi145** [comment]
Yes I can. Let me join.

**Comment by rupareliyahemangi145** [comment]
I've joined.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

In call we have discussed 4 points:
1. Need to load default stages
- Done
2. Don't need to create sub tasks. Need to create Optional tasks. User will create sub task if need.
- Done
3. Differentiate with color and box size.
-  I've checked for box size but for that we need to overwrite whole task kanban view. Which is not good because it may create dependency issue and if any other module which want to add anything or replace in task kanban view it will not reflect. We need to do related project task in this module only. So for now I've added color in boxes and task name.
4. Two different module for sale and project.
- This module doesn't adding any field in sale order. This sale and product functionality is related with each other. So its better to keep one module. Only start data and end date functionality is independent.

Here is video for done points:
https://www.loom.com/share/4058ecbdb6d0480296aa5f8f2d50fd95

Please check it @Radhika435  and @FredrikArvas And let me know if anything.

Thanks.

**Comment by Radhika435** [comment]
Thank you @rupareliyahemangi145 
Seems to be good.
Will review and let you know for further changes.

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @Radhika435

**Comment by Radhika435** [comment]
Hi Hemangi @rupareliyahemangi145 
Hope you ar doing great :)
Need to add some minor changes to the tasks.

1. Now the count of the tasks are only 12, so,when I approve a sales order with Career Advice, a project should be initiated and should create 8 required tasks and 4 optional tasks.
2.Default Task stages must be limited to three (Optional, To do and Done) .The first stage must be fixed to show only optional tasks and the next stage must show the required tasks and sub tasks..
3.Task sequence must be unchangeable upon dragging and dropping cards in Kanban from different stages.I mean that 
Upon moving the tasks from different stages they should still retain their sequences in ascending order.
4.The tasks and sub-tasks must be arranged in sequence of the task number so that user can see the order of the tasks (will show in the picture).
![image](https://user-images.githubusercontent.com/59916603/99812754-1e8a8900-2b47-11eb-9d4e-5770891e2157.png)

5. Create a text field in the tasks and name it as *Instructions* 
6.These 8 + 4 tasks are default tasks created for every project and the instruction field should show the text related to that specific task (for 8 required and 4 optional ) like Instruction 1, Instruction 2.....for the Task 1,Task 2...
![image](https://user-images.githubusercontent.com/59916603/99813494-09622a00-2b48-11eb-8228-c708fb7c555c.png)

//I wanted you to retain the existing objects in regards to color//

Also I dint receive any update on this as well.
//We want the calendar view to show **project -> calendar view based on start date to end-date
**Task -> calendar view based on start date-time to end-time
**Sub-Tasks>calendar view based on start date-time to end-time
(The current Calendar view displays due-date as a "full-day"-event//

Let me know if you have any questions we can take a call based on our availability.

@FredrikArvas Please check/correct if you have comments for the above

Thanks & best regards,
Radhika.

**Comment by FredrikArvas** [comment]
I have reviewd and made some minor clarifications. 
Please proceed with the changes.

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435  and @FredrikArvas I will work on changes.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

I've published code to https://github.com/vertelab/odoo-sale/tree/12.0-AFC-1278-price-list.

Please execute **Update Task Name** server action(which I've added in this module) on exiting/created tasks. Because I've added new field to show task name with number and keep exiting field as it is.

Here is video to show all modifications:
https://www.loom.com/share/7fe543f644eb4092956ba084eddfe290

Please check it and let me know if anything.

Thanks.

Best Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 
Thanks - these changes looks very good!

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will create PR.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-sale/pull/7. Please check it and let me know if anything.

Thanks.

Best Regards,
Hemangi.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145 
Hope all well :)
In the looms video you sent, I was unable to see the sequential arrangement of the tasks and sub tasks according to the mock up picture I sent you. Could you please send me the looms video showing the same.

Thanks & kind regards,
Radhika

**Comment by rupareliyahemangi145** [comment]
@Radhika435 Yes all well. Ok I will send you videos with sub tasks.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

I've update code in af_sale_orders module for sequence with sub tasks in same PR https://github.com/vertelab/odoo-sale/pull/7.

Here is video: https://www.loom.com/share/d871503726fd46059ae623580e0ee02f

Spent 1 hour and 40 mins.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145,
Thanks for the video it seems good.
I wanted to take a short meeting today based on your availability.
Let me know if you have time now at 13:30 IST or come with new time proposal

Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

Yes I am available at 13:30 IST.

**Comment by rupareliyahemangi145** [comment]
@Radhika435 Please share with me meeting ID.

**Comment by Radhika435** [comment]
Hello @rupareliyahemangi145 
Please join here 
http://meet.jit.si/swedishemployementserviceagency_project

**Comment by rupareliyahemangi145** [comment]
Let me join.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145,
Adding some more points in regards to parent and child  task relationship.

1. Parent task (Required and Optional) must not be moved to *Done* until all the child tasks (sub-tasks) associated with that are moved to done. 
2. Moving the  Parent task (Required and Optional) to Done should close all the sub tasks and moved to Done.
3. All child/sub tasks (Required and Optional) must be in the *To do*.
4. If a "Done" mandatory task moves to "To do" child task should remain closed.
5. Optional Task cant be moved back to the stage *optional* if it have open or closed sub-task in the *to do*.
6. Child/Sub-tasks cant be deleted if the task have been closed or Parent task moved to "Done". Only open sub task should be able to be deleted.
7. Parent Task cant be created or deleted.
8. Any number of sub task (child) can be created to a task (parent).

Check this and let me know for any questions.

Thanks and kind regards,
Radhika.

@FredrikArvas Fyi.

**Comment by rupareliyahemangi145** [comment]
For now its clear I will let you if any question.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  and @Radhika435 

I've created PR https://github.com/vertelab/odoo-sale/pull/11 for all new points.

Here are points which discussed yesterday:
1. Default todo stage for subtasks
2. Same color for parent and subtask and different color for each task
3. Remove Priority(star) from Task Kanaban view
4. Parent Task in kanban when creating task
5. raise warning if user try to move optional task into 'To Do' stage
6. Task Description in task kanban view

Here is video for Yesterday points:
https://www.loom.com/share/79e55f4fd7cd465ca5f4114347989af5

Here is video for today's mentioned points in above comment of Radhika:
https://www.loom.com/share/ef6ba736c3004b0399272f738562ccfe
https://www.loom.com/share/192e0536ce644506a00b48b67bb04828

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Spent time - 4 hours

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145,
I had seen your video seems to be good and need to add some more corrections.
Can we take a short meeting to discuss the same at 15 CET (19:30 IST)

Link : http://meet.jit.si/swedishemployementserviceagency_project

Reply me soon if the time is ok for you.

Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment]
@Radhika435 Yes Sure I will join at 1:30 IST.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145 

- Firstly, remove the first functionality in the previous comments.

- Also remove Raise warning if the user try to move the optional task to "To do" stage

And add all the following changes.

- Moving the Parent task (Required and Optional) to Done should close all the sub tasks and moved to Done.

- Optional tasks can be moved to To Do stage if it have sub-tasks with it , raise the warning if we try to put the optional tasks in 
   to the Done stage or optional stage if it have sub-task associated with it in the To do stage 

- Optional Task cant be moved back to the stage optional if it have open or closed sub-task in the to do.

-  On optional tasks the number must start from 9 to 12 and sub tasks must follow the number sequence.

-  The text should appear Black in tasks and it should be same on all task / sub task.

Let me know if you have any questions

Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

I've worked on new feedback points and created PR https://github.com/vertelab/odoo-sale/pull/12 for that.

Here is video link: https://www.loom.com/share/b0143fefa54141e8bddf0d951a638e9f

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment]
Hello @rupareliyahemangi145,
Thanks a lot for the changes and the video seems to be good.
Will review and let you if there are any further changes.

Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @Radhika435

**Comment by rupareliyahemangi145** [comment]
Yesterday Spent time : 1 hour
