### ISSUE TITLE
AFC-1135 - Assign Sales-person Automatically to Sales Orders based on "HR-skills"

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#270]
**Userstory:** 
As a user, I want to receive automatically allocated participants for coaches, and manually change the allocation.
I should be able to manually change coach from suitable coach list. 
Use view Sales in Odoo.

User story. Allocate coach
In the list the user needs to see the coaches language competence, which services the coach are able to provide, name, place and amount of participants. 
For the participants name, service, track, language needs,  incoming date?, starting date, education ID and decision. The decision file has to be provided so it will be possible to open and read during the allocation period.

**Screen-shots before:**
![Tilldela handläggare via Kanban-vy before](https://user-images.githubusercontent.com/70136530/96976604-57214d80-151c-11eb-938f-db0f8d63499a.png)

**Screen-shots after:**
![Tilldela handläggare via Kanban-vy](https://user-images.githubusercontent.com/70136530/96976729-78823980-151c-11eb-8316-6b8f98fa9e96.png)

**Module name:**
odoo-af/...

**Module type:** 
Application

**Test-steps:**
1. In the Kanban view for Sales, check the allocations for participants based on the participants language needs and the coaches ability for that language.

2. Check the provision of the needs of the participants in track, service, date, place and education ID.
3. Check the coach´s competence in language, track and service ability.
4. Change manually the allocated participant to a coach.

**Test-data:**

**Branch name:** 
12.0-AFC-1135

**Description:** 
Solution alt 1
Automatically allocate participants to suitable coaches shown in "Skills" filter and "Group by". 
Add a standard group for each coach, as a automatic allocation.

Solution alt 2
Build an allocation "Server-action" that allocates a participant to an suitable coach based on skills and amount of participants. 
Filter in language in "Skills" and "Group by" field put "Salesperson".

MVP-2  (Not standard) Or add a button to "Action" that is mark able for one or many participants on the order list and than allocate to appropriate coach. The calculation is shown in AFC-1328.

**Estimate:** 
Estimated Hours: 4
Estimated Date: 27/10
Actual Hours:

**Comment by afeli76** [comment]
@FredrikArvas: git Issue uppdaterad, redo för granskning.
