### ISSUE TITLE
AFC-1138 - Select distribution channel for letter-communication

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#271]
**Userstory:** 
As a user, I want to select through which channels a letter-communication will be preformed.

As a user, I want to be able to select several channels **simultaneous**.

**Implementation suggestion**
Add communication channel selector on the Jobseeker-form
externt id: partner_view_360.view_jobseeker_form 
Selector opions, multiple choice = ((email, Email), (sms, SMS), (letter, Letter))

**Module name:**
odoo-base/partner_view_360/ = for the selector on the contact
odoo-af/ https://github.com/vertelab/odoo-af/issues/288/ = for the selector on the oe_chatter

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178/ for more info]

**Integration:**
Nadim - Outgoing: SMPT->REST
https://github.com/vertelab/odoo-mail/tree/12.0-AFC-364

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1138

**Estimate:** 
Estimated Hours: 1h
Estimated Date: 24/11/2020
Actual Hours: 1h

**Comment by FredrikArvas** [comment]
@nils-vertel Jag tycker att det här är utmärkt.

**Comment by FredrikArvas** [comment]
Hi again, 
we discussed this today and I think we need two different instances of this. 
1 Based on the contact-form, based on what we know about the contact (if they have access to the "my pages" at our client, if they accept SMS-communication etc). = Place the channel selector on the contact.
2 What channel we want the messages to be sent through. = Place the channel selector on the oe_chatter-widget

**Comment by nils-vertel** [comment]
@vertelab/n-development please estimate

**Comment by FredrikArvas** [comment]
Yevhen: Hello. I have a question about task.  I don't understand which the place where are need to add channel selector.

**Comment by nils-vertel** [comment]
Suggestion is to place it at the right column of the contact card

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated the deadline.

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-vertel, I`ve updated the actual hours.

**Comment by FredrikArvas** [comment]
@n-development 
Please provide screenshots of the implemented change in the issue.
Please provide a PR and link to that in the issue.
Thanks

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas 
<img width="1058" alt="Screenshot 2020-12-07 at 10 06 27" src="https://user-images.githubusercontent.com/75024283/101325253-1e42fb00-3874-11eb-9ecb-d3c776f12f26.png">
<img width="1058" alt="Screenshot 2020-12-07 at 10 06 48" src="https://user-images.githubusercontent.com/75024283/101325260-20a55500-3874-11eb-9efc-9c2724420ab4.png">
PR: https://github.com/vertelab/odoo-base/pull/183

**Comment by FredrikArvas** [comment]
@Yevhen-Pechurin Thanks for the screenshots!

**Comment by arturchilangwa-vertel** [comment]
Closing this https://github.com/vertelab/odoo-base/pull/183 one due to wrong base, opened this one and merged it #187 .
Also solved some merge conflicts.
