### ISSUE TITLE
AFC-1279a - Add tab with "my customers" on Employee-view

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#272]
**Userstory:** 
As a user, I want to see my "My Customers" on the "Employee-view".

Please display the Customers names where the employee is the "Responsible Sales Person" for "Sales Orders".

---------- Should be checked with Fredrik ----------
**Requirements:**
**Screen-shots before:**
Please display it here:
![image](https://user-images.githubusercontent.com/9428370/96547476-7023c780-12ac-11eb-9257-8815ce76d252.png)

**Module name:**
**_odoo-hr/hr_employee_customers_tab_**

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
1 Go to Sales Orders. Check that there are Sales orders with the selected employee as Sales Person.
2 Go to Employees
3 Select the tab "My Customers"
4 Result. List of the same customers.

**Test-data:**

**Branch name:** 
12.0-AFC-1279-HR-employee-My-Customers-Tab

**Description:** 
This module adds a tab with "My customers" on the "HR-employee"-form.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 1,5h

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-af/pull/275 for this issue.

Here is screenshots:

Sale Orders for 2 sales persons
![sale_orders](https://user-images.githubusercontent.com/36560391/96699522-fbd04d80-13ab-11eb-8864-c54c7b13abeb.png)

Employees with 'My Customers' tab.

![marc_demo_emp](https://user-images.githubusercontent.com/36560391/96699574-0b4f9680-13ac-11eb-8767-2006295fe04c.png)

![admin_customers](https://user-images.githubusercontent.com/36560391/96699593-10ace100-13ac-11eb-8713-f0fe39662620.png)

![other_emp](https://user-images.githubusercontent.com/36560391/96699605-15719500-13ac-11eb-9b0a-de7aa7600b25.png)

Please test it and let me if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
This looks great!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by FredrikArvas** [comment]
Please add time spent on this issue. We use it to learn to estimate for the future. Thanks / Fredrik

**Comment by rupareliyahemangi145** [comment]
Spent time: 1 hour and 30 mins(1.5)

**Comment by FredrikArvas** [comment]
Hi Hemangi
We are moving modules on our repositories and would like you to remove this module from odoo-af - repo and add it to odoo-hr/ instead. 
Thanks
/Fredrik

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Ok I will move from odoo-af to odoo-hr.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-hr/pull/11 to move module in odoo-hr.

Please check it and let me know if anything.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
https://github.com/vertelab/odoo-hr/pull/21
