### ISSUE TITLE
AFC-1286-Jobseeker module

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#273]
**Userstory:**
As a developer I want to have a clean well designed Application Module to add resource and property modules to.

Highlevel goals to achieve:
                 * Generic and clean top level module
                 * Structured module interface trough glue modules towards resource and property modules.
                 * Views for kanban, tree, calandar, pivot
                 * Kanban: default columns for all registered users
                 * Kanban, tree, calendar: filter my jobseekers            

class hrJobseeker(models.Model):
                 _name = "hr.jobbseeker"
                 name = char
                 state = many2one hr.jobseeker.state
                 employee_id Many2one(comodel_name="hr.employee")

class hrJobseekerState(models.Models):
                 _name = "hr.jobseeker.state"
                 stage_name = char
                 sequence = int
                 template_id = many2one mail.template
                 fold = bool
                 state = inprogress|blocked|ready for next stage

**Type of module:**
Application Module, see: https://github.com/vertelab/odoo-af/issues/178

**Name of module:**
hr_jobseeker

**Test-steps:**
The module should be able to install.

**Test-data:**

Branch name:
AFC-1286-Jobseeker module

**Description:**
Jobseeker module to handle jobseekers in the system, top level module that contains several submodules to handle different views and data that are related to jobseekers.

**Depends:**
hr

*Time spent*

**Comment by FredrikArvas** [comment]
Hi Nils
It looks like this module has a dependancy to the sale-module. Is this correct. I would prefer if that would be be placed in a different module.

**Comment by iammiracle** [comment]
Hi Fredrick, you are saying you will prefer it is placed in a different module. Do you have an existing module for this or am I to develop a module with the hr_jobseekers?

I also guess this branch  **AFC-1286-Jobseeker module** will be done in **odoo-af repository** right?

If, I am to create a new module, I guess those fields listed above are the fields to be present right?

**Comment by FredrikArvas** [comment]
Hi Miracle, 
please create a new module (that will be the future base for other modules)

The new module should be placed in the odoo-af repository at this point. We are moving stuff around but have note finished how it should be placed. (normally, I would like to have it in odoo-hr).

**Comment by iammiracle** [comment]
Do you think we should have a separate menu for the Job Seeker or it can be under Employee Menu

**Comment by FredrikArvas** [comment]
At this point, I think it should be a separate menu.
Thanks

**Comment by iammiracle** [comment]
Here is the update of the module:

**Kanban view**

![image](https://user-images.githubusercontent.com/7355805/96889196-47ebc280-147e-11eb-991a-74d4204d8be0.png)

**Form view**
![image](https://user-images.githubusercontent.com/7355805/96889315-6356cd80-147e-11eb-8206-d47928db07ef.png)

Other views are present as well. Created a [PR](https://github.com/vertelab/odoo-af/pull/287)

**Comment by FredrikArvas** [comment]
Please add time spent on this issue. We use it to learn to estimate for the future. Thanks / Fredrik

**Comment by iammiracle** [comment]
Time Spent: 4hrs

**Comment by FredrikArvas** [comment]
Please move this module from https://github.com/vertelab/odoo-af/pull/287
To: https://github.com/vertelab/odoo-outplacement - Branch Dev-12.0-Fenix-Sprint-02
