### ISSUE TITLE
AFC-1292 - display the top navigation permanently to the left

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#277]
**Userstory:** 
As a user, I do ....

**Screen-shots before:**
![image](https://user-images.githubusercontent.com/9428370/96708441-89567200-1399-11eb-8b19-f8fc86c536db.png)

**Screen-shots after:**
![image](https://user-images.githubusercontent.com/9428370/97449508-09e51780-1932-11eb-838e-38281452a2b0.png)

**Bugreport:**
Steps to reproduce and where in the system the defect is located...

**Module name:**
odoo-af/af_

**Module type:** 
Application/Property/Resource/Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integration:**

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1XXX-...

**Description:** 
This module 

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 5,5 hours

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Screen which you have mentioned in issue it comes from which module?

**Comment by FredrikArvas** [comment]
Hi 
The image is from a mockup.
The question here is there is a way to change the backend-theme to display the normal navigation permanently in a left-column.
/Fredrik

**Comment by rupareliyahemangi145** [comment]
Ok Understood @FredrikArvas . Let me check possibility for that.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've worked on similar kind of pattern to show main menu on whole screen like enterprise version.

![menu_menu](https://user-images.githubusercontent.com/36560391/96865193-3eb32380-1487-11eb-92d6-cb78a583628a.png)

If you want this kind of solution then I can use this logic in our existing theme.
To have all the menu life side as fix will occupy unnecessary space that will make form view size very smaller and that will also take time to develop.

**Comment by rupareliyahemangi145** [comment]
Here is another solution which matches mockup.

![static_meenu](https://user-images.githubusercontent.com/36560391/96866835-85098200-1489-11eb-974b-c4ca90a64d49.png)

Please check it.

**Comment by FredrikArvas** [comment]
Hi Hemangi, 
could you please give us a try with the left menu with text-links (with images) and the middle and right sections as you display here. 

how much work would it be to add this to the af_backend_tema

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

It will take approx 4-5 hours.

**Comment by FredrikArvas** [comment]
Thanks!

I will speak to the team to see what priority this issue has now.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by FredrikArvas** [comment]
Please proceed. I have got an approval from our side. /Fredrik

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-af/pull/290 for this issue.

![menu_left](https://user-images.githubusercontent.com/36560391/97068921-733ef080-15e9-11eb-9ffc-bc9d83594dab.png)

In above screenshot some menu has no icon. For that we need to add one attribute **web_icon="image_path"** in menuitem.
Once you test this I will do it. I will need icon for that.

Please test it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Spent Time: 5 hours and 30 mins(5.5 with analysis, discussion and development)

**Comment by FredrikArvas** [comment]
Please close this PR https://github.com/vertelab/odoo-af/pull/290 and create a new one here
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02 with a new name of the module: web_backend_theme_af
Thanks

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Closed https://github.com/vertelab/odoo-af/pull/290 and create new PR https://github.com/vertelab/odoo-web/pull/1.

Please check it and let you know if anything.

Thanks.

Regards,
Hemangi.
