### ISSUE TITLE
AFC-1313 - Mail-client Odoo Messaging

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#288]
**Userstory:** 
As a case worker, I want to see messages that are sent through Nadim

Please find/make a module that displayes a tree- and formview of messages sent through Odoo. 
Place the menu on the contact and the employee and make the tree view list communication for that person.

Start with copies of these forms (or simpler versions).
![image](https://user-images.githubusercontent.com/9428370/96913615-27cefa00-14a4-11eb-8cf1-553f63d4e56f.png)
![image](https://user-images.githubusercontent.com/9428370/96913638-31586200-14a4-11eb-9b53-3c80a997f8dd.png)
![image](https://user-images.githubusercontent.com/9428370/96913623-2bfb1780-14a4-11eb-992a-bc0f7c19cabf.png)

**Screen-shots after:**

**Module name:**
odoo-af/af_mail_client_contact
odoo-af/af_mail_client_employee

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Go to a contact/employee. 
Create and send a new message
Go to the tree-view = the message should be visible.

**Test-data:**
-
**Branch name:** 
12.0-AFC-1313_Mail-client Odoo Messaging

**Description:** 
This module adds a client-interface to the Odoo messageing functions centered around the selected Contact
This module adds a client-interface to the Odoo messageing functions centered around the selected Employee

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours: 1:10

**Comment by iammiracle** [comment]
Hi, here is a screen shoot of the messaging part;

**Contacts**

![image](https://user-images.githubusercontent.com/7355805/96924267-50f28900-14aa-11eb-9178-079c0fce9a70.png)

**HR**

![image](https://user-images.githubusercontent.com/7355805/96924319-6667b300-14aa-11eb-98d2-02b574360b0f.png)

Here is the [PR](https://github.com/vertelab/odoo-af/pull/289)

Time spent: 1hr 10mins

**Comment by fredrikarvasarbetsformedlingen** [comment]
https://github.com/vertelab/odoo-af/tree/Dev-12.0/af_mail_client_employee
