### ISSUE TITLE
AFC-1139 - Mail-templates for KVL 

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#291]
**Userstory:** 
As a user, I want automatic mailtemplates with pre-filled content.

------
Template: 1 - Assigned Coach
Hi [res_partner.name]
[hr_employee.name] is your coach and we will send you an invitation to a first meeting at [hr_employee.location]. 

Welcome to [res_company.name]

------

Template: 2 - First meeting
Hi [res_partner.name]
I am [hr_employee.name] and will be your coach during the 40 day programme with us at [res_company.name]. 
I invite you to a first meeting on [calendar.date] at calendar.time] in our facilities at [hr_employee.location]. 

Bring a copy of your reference-documents and a photo-identity. 

We will provide you with documentation and notes-papers. 

Welcome again!

[hr_employee.name}
[res_company.name] 
------

**Screen-shots after:**

**Module name:**
Similar as af_calendar_report
odoo-af/af_order_report

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Dependancy:**
Nadim SMTP-to-REST-integration

**Test-steps:**
Select an order, -> Create a message -> Select the appropriate template -> Send message

**Test-data:**
Any order linked to a Jobbseeker.

**Branch name:** 
12.0-AFC-1139-message-template

**Description:** 
This module adds message templates for KVL-invitation messages linked to sales orders

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
Hi Fredrik, from which module or model will this email be sent.

**Comment by FredrikArvas** [comment]
Hi Miracle, 

I think we should start with Odoos standard mail-interface. 

Later (which is rather soon), it will be sent thorugh a new module which translates the standards SMTP-protocol to a REST-protocol (https://github.com/vertelab/odoo-mail/tree/12.0-AFC-364/send_mail_nadim) but this module is not ready yet, and we can not test it outside of the clients environment.

OK?

**Comment by iammiracle** [comment]
Alright, I understand. I will get the email template ready. I just want to know where I will be pointing the fields to, either hr record or partner record.

**Comment by FredrikArvas** [comment]
You are right! 
At this point, please use the suggestions I have made in the templates above (and if they do not work, choose something else that exist in odoo-standard so we can test the module). 

Please add both email- and PDF-templates. 
Thanks for asking questions - it really leaves a lot of pressure of me, since I know that you suggest alternative solutions that might be better than the one I can think if.

**Comment by iammiracle** [comment]
Hi Fredrick,

Following the description above, I had added a field for hr.employee, so I can be able to test the template. The template is linked to sale orders like you described and the date used is the confirmation_date. 

![image](https://user-images.githubusercontent.com/7355805/97173101-5395fc80-1790-11eb-9af7-6778d81032be.png)

Assigned Coach Email and PDF

![image](https://user-images.githubusercontent.com/7355805/97173195-73c5bb80-1790-11eb-8f5d-c5284de0ca39.png)

First Meeting Email and PDF

![image](https://user-images.githubusercontent.com/7355805/97173252-8b04a900-1790-11eb-9f73-b356aba07608.png)

Nothing sensible is in the PDF, so i will like to know how you want the pdf to look like.

[PR Created](https://github.com/vertelab/odoo-af/pull/298)

Time Spent: 1hr 30mins

**Comment by FredrikArvas** [comment]
We have moved this code to this repo instead: https://github.com/vertelab/odoo-sale/pull/4
