### ISSUE TITLE
AFC-1323 - API for EN: Suborder (SV: Avrop) Create rest client/server 

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#303]
**Userstory:**
See attached swagger file for information about endpoints, messages and record.
~~[IPF-8215_leverantorsavrop.txt](https://github.com/vertelab/odoo-sale/files/5480380/IPF-8215_leverantorsavrop.txt)~~
[IPF-8215 - v1p0p3.txt](https://github.com/vertelab/odoo-sale/files/5545732/IPF-8215.-.v1p0p3.txt)

Implementation of integration modules between Fenix and BÄR.
-- Client API module - System parameters for host and base-url
-- Server API module - Dummy responses from each function.
Creation of a server action for each endpoint (for test)

Screen-shots after:

Module name:
odoo-sale/sale_suborder_ipf_client
odoo-sale/sale_suborder_ipf_server

**Module type:**
API-Module

**Test-steps:**
Server action for each endpoint from the client.

**Test-data:**

**Branch name:**
12.0-AFC-1323

**Description:**
Implementation of Suborder message between Fenix and BÄR.

**Estimate:**
Estimated Hours: 4
Estimated Date:
Actual Hours:

**Comment by n-development** [comment]
Estimated Hours: 8-12 hours
Notes:

- We had to change a bit redness level of the file for Swagger, it was hard to work with. Here is our proposal of the same file 
[bar-fenix_ipf-82115__1_.txt](https://github.com/vertelab/odoo-af/files/5481114/bar-fenix_ipf-82115__1_.txt)
 
- Overall we don't understand yet the full picture of the project (so it's hard to make precise estimations) Would be great to have more info

**Comment by FredrikArvas** [comment]
https://github.com/vertelab/odoo-sale/pull/9

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated estimates and deadline and actual hours.
