### ISSUE TITLE
AFC-1279 - Changes to the Employee-Formview and Tree-view

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#304]
**Userstory:** 
1 As a user, I want the to see the following information in the Employee-**form**-view
2 As a user, I want the to see the following information in the Employee-**tree**-view.

**Screen-shots before:**
(The Requriements about the multiple offices are excluded from this iteration.)

The image shows fields that should be hidden.
Userstory 1-tab 1
![AFC-1279 - 1a delen](https://user-images.githubusercontent.com/72881934/97541524-9ab90300-19c5-11eb-9e04-09e1e46522db.JPG)
Add **Employee ID** (add from https://github.com/vertelab/odoo-af/issues/362)

Userstory 1-tab 2
![image](https://user-images.githubusercontent.com/9428370/99141295-5aef4e00-264a-11eb-97d6-03d22ef59d69.png)

Userstory1-
Add an "SmartButton" if the Employee is working or is on leave today, beside the "Leaves"-smart-button
This indication should be based on a (hr_holidays-module) calculation (approximately) 
IF ("Current day" is within any of the LEAVES records) THEN "AWAY" ELSE "PRESENT"
![image](https://user-images.githubusercontent.com/9428370/99140886-e7e3d880-2645-11eb-9777-82999524665b.png)

Userstory1 - Add User Credentials-tab
3. Create a glue-module that displayes the "User Credential" from the Users-settings-list.

![image](https://user-images.githubusercontent.com/9428370/98383822-478e2280-204d-11eb-8231-7eab78c09879.png)

Userstory 2-tree-view
Fields: Name
**Employee id** (new field added in https://github.com/vertelab/odoo-af/issues/362)
Work phone
Work email
Municipality (we think we willl use the department-field)
**Active** (boolean field based on hr_holidays)
Job position
Manager

**Module name:**
1 odoo-hr/hr_employee_views_fenix
(please change the name of the previous module and place it in odoo-hr)

2 odoo-hr/hr_employee_views_user-credentials-tab

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1279-hr-employee-views

**Description:** 
This module changes the visible fields in the form- and tree-view based on the Fenix requirements.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created new module **af_hr_view**,
1. hide **Coach**, **Timezone** and **Work Location**  from **Work information** Tab.

![employee_view_1](https://user-images.githubusercontent.com/36560391/97700081-3c794680-1ad1-11eb-8bb5-db916d6e52f1.png)

2. hide **Km work**, **Status**, **Birthday** and **Work limit** from **Private information** Tab.

![employee_view_2](https://user-images.githubusercontent.com/36560391/97700107-469b4500-1ad1-11eb-8a57-de7c1c27b056.png)

What change you want in tree(list) view? Here is current list view.
![employee_tree](https://user-images.githubusercontent.com/36560391/97700172-63d01380-1ad1-11eb-83c8-865f8e650c76.png)

Didn't created PR but please check from screenshot and let me if anything remaining or want to change module name or anything else. Then I will create PR for this issue.

Thanks.

Regards,
Heamngi.

**Comment by FredrikArvas** [comment]
Thanks @rupareliyahemangi145 
@af-aden or @Radhika435 - could you please check this?

**Comment by afeli76** [comment]
Should be checked by Fredrik
====================
1. Delete Nationality(Country) and Passport No fields.
![h_privateinformation_after](https://user-images.githubusercontent.com/70136530/97963826-08936f00-1db8-11eb-9464-a7b014ef33a8.png)
====================
Should be checked by Fredrik

**Comment by afeli76** [comment]
> Thanks @rupareliyahemangi145
> @af-aden or @Radhika435 - could you please check this?

I checked this and added some modification. @FredrikArvas should verify the modification and please assign back to developer.

**Comment by af-aden** [comment]
@rupareliyahemangi145 
Hello Hemangi,
How is the status of this issue? I saw that you left a comment on git issue #316, did you get an answer? and what is the status of #316 ?
Best Regards
// Aden Hassan

**Comment by rupareliyahemangi145** [comment]
Hello @af-aden 

In #316 waiting for replay on **6. Active (boolean field based on hr.leaves)**.
And for this issue, I saw that 1. need to hide two fields Nationality (Country) & Passport No, 2. need to new field Employee No., 3. Create a glue-module that displayes the "User Credential" from the Users-settings-list.

But I saw comment that fredrik should verify the modification. That's why I didn't start work on these 3 points.
Should I start work on these 3 modification?

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 and @af-aden 
I have now reviewed and approved the changes. 
Please proceed with the changes: (some modifications to the previous module, upgrade an OCA-module, add a glue-module)
Thanks

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR for this issue. Here is screenshots:

![emp_1](https://user-images.githubusercontent.com/36560391/99143268-2c8d6500-2682-11eb-91b5-1c61b4d9c84d.png)

![emp_2](https://user-images.githubusercontent.com/36560391/99143272-32834600-2682-11eb-85b5-ae83eb7a3ccb.png)

![emp_3](https://user-images.githubusercontent.com/36560391/99143275-37e09080-2682-11eb-9d9c-a1778cbe0e37.png)

![emp_4](https://user-images.githubusercontent.com/36560391/99143278-3d3ddb00-2682-11eb-9b9a-37bedeb0e1de.png)

Here is info for time spent:
This spent time includes development, discussion and analysis.
**Date-Description-Spent time**
30 Oct 2020 - Issue 304: Worked on to change employee view. - 50 min.
02 Nov 2020 - Issue 316: Checked issue for employee list view. - 10 min
03 Nov 2020 - #316 Added fields in employee search filter - 10 min
04 Nov 2020 - Issue 316: Checked issue for emplyee list view. - 10 min
14 Nov 2020 - Worked on new modifivcations. - 
**hr_employee_views_user-credentials-tab** - 1 hour and 20 min
**hr_employee_views_fenix** - 30 mins

Please check it and let me know if anything.

**Comment by FredrikArvas** [comment]
thank you @rupareliyahemangi145 
the screenshots look good to me. I will ask @af-aden to check them too.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks
