### ISSUE TITLE
AFC-1282 - Modules with testdata for Fenix 

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#313]
**Userstory:** 
As a user, I want testdata to be installed by separate modules, so it will be clear that these data can be installed, re-installed and deleted at any time.

I am not sure if we should go for xml or csv-formated data. 
I am more used to csv, since it is easier to create inside Odoo and then export as "importable"-csv. But XML might be safer?
@iammiracle do you have a recommendation?

This is the list of files at this point.
odoo-af/fenix_test_contacts - /data/res.company.csv
odoo-af/fenix_test_contacts- /data/res.user.csv
odoo-af/fenix_test_contacts- /data/res.partner.csv
odoo-hr/fenix_test_hr- /data/hr.employee.csv 
odoo-hr/fenix_test_hr_leaves - /data/hr.leaves.csv
odoo-project/fenix_test_project - /data/project.project.csv
odoo-project/fenix_test_project - /data/project.task.csv
odoo-sale/fenix_test_sale - /data/sales.order.csv
odoo-sale/fenix_test_sale - /data/product.product.csv
odoo-af/fenix_test_dashboard - /data/...

**Module name:** (added by Nils or Fredrik)
odoo-af/fenix_test_contacts
odoo-hr/fenix_test_hr
odoo-hr/fenix_test_hr_leaves
odoo-project/fenix_test_project
odoo-sale/fenix_test_sale
odoo-af/fenix_test_dashboard

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
1 Install the module into a clean database. = New data should be visible.
2 Delete the data from the user interface. Upgrade the module. = The data should be back
3 Uninstall the moulde = the data should be gone.

**Branch name:** 
12.0-AFC-1282-testdatamodules

**Description:** 
This module adds testdata used for Fenix

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours: 3:30

**Comment by iammiracle** [comment]
@FredrikArvas can you please give a branch name? Then how many of these data should i create for each model. I think I will go ahead with XML data format

**Comment by iammiracle** [comment]
I have created PR for the above module except for fenix_test_dashboard:

[AFC-1282 - HR with testdata for Fenix](https://github.com/vertelab/odoo-hr/pull/14)
[AFC-1282 - Sales with testdata for Fenix](https://github.com/vertelab/odoo-sale/pull/2)
[AFC-1282 - Project with testdata for Fenix](https://github.com/vertelab/odoo-project/pull/2)
[AFC-1282 - Contact with testdata for Fenix](https://github.com/vertelab/odoo-af/pull/328)

Spent Time: 3hr 30mins

**Comment by FredrikArvas** [comment]
Could you please merge the test-data-modules to the dev-12.0-Fenix-Sprint-02-branches in each repo and install them to Fossa too?

**Comment by FredrikArvas** [comment]
Hi again, 
I looked at the commit-messages and I remember that Mikael Holm mentioned something about always having the Jirakey in the commit-message. Do you remember?

Please check this before merging the code.

**Comment by FredrikArvas** [comment]
Hi again, 

We have a new member in the team (@arturchilangwa-vertel) , who will work as Configuration Manager. Let me ask him to merge these modules instead, since they are simple to merge and will be good practice for him.

/Fredrik

**Comment by FredrikArvas** [comment]
Please close this PR https://github.com/vertelab/odoo-sale/pull/2 and rename module sale_test-data_fenix

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 Sorry for assigning you here, our collegue Artur is working with this issue

**Comment by FredrikArvas** [comment]
Please close PR https://github.com/vertelab/odoo-hr/pull/14 and rename the module hr_test-data_fenix

**Comment by rupareliyahemangi145** [comment]
It's ok @FredrikArvas I will do it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-hr/pull/18 to rename module name. https://github.com/vertelab/odoo-hr/pull/14 is already merged.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by arturchilangwa-vertel** [comment]
Created an new PR https://github.com/vertelab/odoo-sale/pull/6 that replaces https://github.com/vertelab/odoo-sale/pull/2. 

This PR also renames the module

**Comment by arturchilangwa-vertel** [comment]
Added [commit](https://github.com/vertelab/odoo-project/pull/2/commits/3485f1d19fd38c1988c111c4fd0e296d1623772e) that renames fenix_test_project to project_test-data_fenix  in https://github.com/vertelab/odoo-project/pull/2

**Comment by arturchilangwa-vertel** [comment]
Added https://github.com/vertelab/odoo-base/pull/157  which copies and renames fenix_test_contacts and https://github.com/vertelab/odoo-af/pull/381 for removing the old module
