### ISSUE TITLE
AFC-1133 - Add filter in Sales for users language and Employees skills

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#314]
**Userstory:** 
As a user, I want to filter sales orders to match clients language to sales persons skills, to assign sales persons according to skills.

**Suggested solution:**
Add "filter on" and "group by" for sales-orders based on employee-skills
Add "filter on" and "group by" for sales-orders based on clients language

**Screen-shots before:**
![Tilldela handläggare via Kanban-vy](https://user-images.githubusercontent.com/70136530/96976729-78823980-151c-11eb-8316-6b8f98fa9e96.png)

**Screen-shots after:**

**Module name:** (added by Nils or Fredrik)
odoo-af/af_

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integration:**

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1133-...

**Description:** 
This module adds filter to the sales-order tree-view and kanban-view based on emploee-skills

**Estimate:** (added by developers only)
Estimated Hours: 3,5 h
Estimated Date: 
Actual Hours: 3 hours and 10 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

If I understood needs to add filter on sale order for Client's language ad employee's skills.

I have added filter for client's language(Not created PR). I can add filter for employee's skill. Before adding filter for employee skill, I want approval for time estimation. Time estimation for both filter is near about 3 or 3.5 hours (Spent 1 hour for adding filter for client's language and analysis to add both filter).

Please check it and let me know. So I can start work on employee's skill filter.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi Hemangi, 

yes, this is correct and I approve the estimate. Please proceed. I think you might find questions along the way, but we will see!

In the next step (later on), we want a server action to automatically match the "current sale order" to the employee with the right skills (language and product) with the least customers. This will distribute the customers equally between the employees. 
I say this because it is good for you to know, but not needed to develop at this time.  But if you could estimate it would be good to know. 
Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Thanks for approval. I will start on filters.

But for next step distribute the customers equally between the employees I need more details.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-af/pull/319 for this issue.

Added filter 'My Language' which search sales of user language, Added skill and client's language in search of sale which return sales based on entered skill name and language name, Added group by client's language in sale group by.

Here are screenshots:
![filter](https://user-images.githubusercontent.com/36560391/97870770-69c82d80-1d39-11eb-8f51-765a3525815d.png)

![group_by](https://user-images.githubusercontent.com/36560391/97870783-6f257800-1d39-11eb-86d1-e887c9aba893.png)

I've added server action for exiting sale orders. 'Update employee in sale'. You need to execute that server action for exiting sales. Need to execute this server action once only for exiting sales. No need to execute it for new sales.

Added server action to update employee and skill in sale that will help to search.

Please check it and let me know if anything.

Thanks.

Best Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Spent: 3 hours and 10 mins.

**Comment by FredrikArvas** [comment]
https://github.com/vertelab/odoo-af/pull/393
