### ISSUE TITLE
AFC-1304 - View employee list

### ISSUE THREAD

**Issue by af-aden** [vertelab/odoo-af#316]
**Userstory:** 
As an administrator, i want to see a list that gives me an overview of employees and information related to them. I want to be able to edit and change employee information.

**Requirements:**
- I should be able to filter on all columns
- The following columns should show in the list view
1. Name
2. Employee Id
3. Work phone
4. Work email
5. Municipality (leave this for now)
6. Active (boolean field based on hr.leaves)
7. Job position
8. Manager

**Screen-shots before:**
![image](https://user-images.githubusercontent.com/72881934/97840367-22638200-1ce4-11eb-86dd-9f7387811a66.png)

**Screen-shots after:**

**Module name:** 
odoo-af/af_hr_view
The module is created by: https://github.com/vertelab/odoo-af/issues/304

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Branch name:** 
12.0-AFC-1304-...

**Description:** 
This upgrade changes the columns and filters in the tree-view

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will do it tomorrow.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Following two fields:
2 Employee Id
6 Active (boolean field based on hr.leaves), is already added from any module or need to add new fields?

**Comment by FredrikArvas** [comment]
2 Please use the standard-employee_id-field.

6 For the Attribute Active, please use the value provided from the module: hr_holildays
I think this module adds a field called hr.leaves 

Is this right?

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas I will check about 6 Active. Understood about Employee Id.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

6 For the Attriute Active, You mean want to add Remaining Legal leaves or Leaves left?
![employee](https://user-images.githubusercontent.com/36560391/98079838-8039ca80-1e9a-11eb-93e8-db1324c6ba8c.png)

**Comment by FredrikArvas** [comment]
We close this issue and specify all changes in the AFC-1279-issue (https://github.com/vertelab/odoo-af/issues/304)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
