### ISSUE TITLE
AFC-1149 - break out the partner education-tab from partner_360_view

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#325]
Suggestion: 
Miracle develop. Sebastian test and merge.
The aim is for this module to be used both in CRM and in FENIX.

**Userstory:** 
As a user, I want to separate the education-tab from the partner_360_view

To do: 
Break out the Education-form from the partern_360_view-form and place it in a separate glue-module.

**Screen-shots before:**
![image](https://user-images.githubusercontent.com/9428370/97893319-6a5cc600-1d31-11eb-9b82-0ed5b62f5125.png)
![image](https://user-images.githubusercontent.com/9428370/97893522-af80f800-1d31-11eb-9b73-2df7e717db96.png)
![image](https://user-images.githubusercontent.com/9428370/97893606-c9223f80-1d31-11eb-88b7-c098e3bca010.png)

**Screen-shots after:**

*Module name:** (added by Nils or Fredrik)
odoo-base/partner_360_view (from where you move the code **out**)
odoo-base/partner_education_view (from where you move the code **in**)

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Go to Jobb-seeker-form. Check that the form displayes

**Branch name:** 
12.0-AFC-1149-break-out-partner-education-form

**Description:** 
This module adds a tab with education (SUN and Drivers-licens codes)

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours: 0:20 min

**Comment by iammiracle** [comment]
[PR Created](https://github.com/vertelab/odoo-base/pull/146)

Time spent: 20mins

**Comment by FredrikArvas** [comment]
@SebastianGieser-Vertel 
Please review this code and merge into the CRM-project.

**Comment by FredrikArvas** [comment]
Merged
