### ISSUE TITLE
AFC-1151_Previous_Experiences-tab desired_jobs

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#326]
**Userstory:** 
As a user, I want to add information about the users previous experiences

Please add a field for education-level and a field for experience-lenght

**For Education**
use the "education_level" from the res_sun-module

**For Experience:** 
0 No experience
1 Less than 1 year
2 1 to 3 years
3 more than 3 years

**Add some intelligence:**
Add a "on change"-something that saves a boolean yes, if one of these new fields has a value greater than 0.

**Screen-shots before:**
![image](https://user-images.githubusercontent.com/9428370/97895359-f96add80-1d33-11eb-9242-02acd1c59973.png)

**Screen-shots after:**

**Module name:** (added by Nils or Fredrik)
odoo-base/partner_desired_jobs

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Check that the module saves data 

**Test-data:**

**Branch name:** 
12.0-AFC-1151-adds-levels-on-jobs

**Description:** 
This module adds a three levels for previous jobs.

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
Here is a screenshot

![image](https://user-images.githubusercontent.com/7355805/97960127-18f41b80-1db1-11eb-9a7e-dc18e8f87732.png)

[PR Created](https://github.com/vertelab/odoo-base/pull/147)

**Comment by FredrikArvas** [comment]
Thanks.
Small thing:
May I ask you to move the Education column to be close to Education Level?
So the column order will be:
SSYK, Job Title, Education level, Education, Experience length, Experience

And merge to Dev-12-fenix-sprint02-branch and install on fossa?

**Comment by iammiracle** [comment]
Done this

**Comment by FredrikArvas** [comment]
Thanks

**Comment by FredrikArvas** [comment]
Did you try to install it on Fossa too?
I tried and got this error:
Model not found: res.partner.jobseeker.search.wizard
Error context:
View `search.jobseeker.wizard`

Please help me install both the module: partner_desired_jobs and the module  partner_education_view

**Comment by iammiracle** [comment]
@FredrikArvas I realized that. I am looking into it. I think the server needs to be restarted, because after checking through, the appropriate python file was referenced, and I did not have this issue locally.

**Comment by FredrikArvas** [comment]
That is fine. This is a test-server - please restart it if needed at any time.

**Comment by iammiracle** [comment]
I have restarted the server several times, it keeps complaining of missing fields, I don't know if a fresh db can be created

**Comment by FredrikArvas** [comment]
This module works on our side now.
