### ISSUE TITLE
AFC-1345 - API to Interpretor portal (SV: Tolkportalen)

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#339]
**Userstory:**
- Creation of swagger file from description attached.
- Implementation of integration modules between Fenix and Tolkportalen.
-- Client API module - System parameters for host and base-url
-- Server API module - Dummy responses for each function
- Creation of a server action for each endpoint (for test)

**Data**
[messages.txt](https://github.com/vertelab/odoo-af/files/5494746/messages.txt) - Used as base for swager file
[responses.txt](https://github.com/vertelab/odoo-af/files/5494780/responses.txt) - Responses

**Screen-shots after:**

**Module name:**
odoo-project/task_interperator_ipf_client
odoo-project/task_interperator_ipf_server
**Module type:**
API-Module

**Test-steps:**
Server action for each endpoint from the client.

**Test-data:**

**Branch name:**
12.0-AFC-1345

**Description:**
Implementation of Fenix-IntepreatorBookings integration for REST-calls from the client-module to the server-module.
(Later from the Fenix-server to the Tolkportalen service.)

**Estimate:**
Estimated Hours: 6h
Estimated Date: 07/12/2020
Actual Hours: 6h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve added estimates.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel could you give approval on it?

**Comment by nils-vertel** [comment]
@n-development Go for it

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-project/pull/3

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve added the Actual Hours
