### ISSUE TITLE
AFC-1339 - Display Sales Order in Fenix

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#342]
**Userstory:**
- Creation of swagger file from description attached.
- Implementation of integration modules concerning showing order.
-- Client API module - System parameters for host and base-url
-- Server API module - Dummy responses for each function
- Creation of a server action for each endpoint (for test)

**Data**
[Get Order List_json Response example.txt](https://github.com/vertelab/odoo-af/files/5544864/Get.Order.List_json.Response.example.txt)
[Get Order_json Response example.txt](https://github.com/vertelab/odoo-af/files/5544865/Get.Order_json.Response.example.txt)
[ordertjansten-order_json.txt](https://github.com/vertelab/odoo-af/files/5544866/ordertjansten-order_json.txt)

**Aditional links**
https://eu1.anypoint.mulesoft.com/exchange/1dae6e32-bf25-4b52-aa03-8f32e1f5fc08/ordertjansten-order/minor/1.0/console/method/%231177/
https://eu1.anypoint.mulesoft.com/exchange/1dae6e32-bf25-4b52-aa03-8f32e1f5fc08/ordertjansten-order/minor/1.0/console/method/%231177/

**Screen-shots after:**

**Module name:**
odoo-sale/sale_showorder_ipf_client
odoo-sale/sale_showorder_ipf_server

**Module type:**
API-Module

**Test-steps:**
Server action for each endpoint from the client.

**Test-data:**

**Branch name:**
https://github.com/vertelab/odoo-sale/tree/12.0-AFC-1342

**Description:**
Implementation of visa order integration for REST-calls from the client-module to the server-module.

**Estimate:**
Estimated Hours: 6h
Estimated Date: 17/11/2020
Actual Hours: 6h +1h

**Comment by n-development** [comment]
Development | 06:00
Quality Assurance | 01:00

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated estimates and deadline and actual hours.

**Comment by FredrikArvas** [comment]
@AnatoliiYakymets  - please make a PR and link to it here. 
https://github.com/vertelab/odoo-sale/tree/12.0-AFC-1342 -> https://github.com/vertelab/odoo-sale/tree/Dev-12.0-Fenix-Sprint-02

**Comment by FredrikArvas** [comment]
@n-development Please add a link to the RP here.

**Comment by n-development** [comment]
@FredrikArvas 
https://github.com/vertelab/odoo-sale/pull/14
