### ISSUE TITLE
AFC-1152 Break out Partner Education from the module partern_360_view

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#357]
**Userstory:** 
As a user, I want to have the education and experiences in a separate module, to avoid depencencies

ToDo:
1 Create a new module with the **fields** and **views** of the partner_360_view-module
https://github.com/vertelab/odoo-base/blob/d36b286d63de8d77511362965148cf663d585c2c/partner_view_360/views/res_partner_view.xml#L102
to:
https://github.com/vertelab/odoo-base/blob/d36b286d63de8d77511362965148cf663d585c2c/partner_view_360/views/res_partner_view.xml#L120
2 Remove the fields from the original module

3 Add the view from the new module to the partner_360_view-module
![image](https://user-images.githubusercontent.com/9428370/99843263-92da2200-2b71-11eb-936a-a438cde2e0c1.png)

4 Add the settings-menu to the Jobseeker-form and the Employer-form, as well as the normal Contact-form with Admin-Settings-user-rights.
![image](https://user-images.githubusercontent.com/9428370/99844285-27914f80-2b73-11eb-8d6e-d58a5fd90ca9.png)

5 Add menu to the configuration-list of Education-level.
![image](https://user-images.githubusercontent.com/9428370/99843869-7db1c300-2b72-11eb-8461-32748b35ab46.png)

6 Add two fields for uploaded documents: res_partner.cv and res_partner.references
![image](https://user-images.githubusercontent.com/9428370/99844102-e1d48700-2b72-11eb-858b-81bdd24f9f01.png)

**Screen-shots before:**

**Dependencies:** 
https://github.com/vertelab/odoo-base/tree/Dev-12.0/res_sun
https://github.com/vertelab/odoo-base/tree/Dev-12.0/res_drivers_license

**Module name:** 
odoo-base/partner_education_views

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install partner_360_view on a new database. 
Check that neither the res_sun or the res_drivers_license are installed, nor should any of its fields be there.
Install the partner_education_views-module.
Find a res.partner and edit education-data.

**Test-data:**

**Branch name:** 
Dev-12.0-Fenix-Sprint-02/12.0-AFC-1152-Partner_Education-Views

**Description:** 
v12.0.0.1 This module adds a tab with the Partners Education based on SUN-codes and Drivers Licenses.

**Estimate:** (added by developers only)
Estimated Hours: 8h
Estimated Date: 24/11/2020
Actual Hours: 6h

**Comment by nils-vertel** [comment]
@vertelab/n-development please estimate

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated estimates and deadline and actual hours.

**Comment by FredrikArvas** [comment]
@Yevhen-Pechurin 
Please make a Pull Request for the work you have done and add a link to it here. 
Thanks

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas 
If you want to avoid depencencies, but you want to have field with sun codes and driver licenses in this module, i need to add it to this module.

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas 
https://github.com/vertelab/odoo-base/pull/184

**Comment by arturchilangwa-vertel** [comment]
Closed this one due to wrong base branch https://github.com/vertelab/odoo-base/pull/184 
Opened new that also solved the merge conflict and merged it https://github.com/vertelab/odoo-base/pull/186

**Comment by FredrikArvas** [comment]
@n-development 
I will assign this issue to an other developer to finish it.
