### ISSUE TITLE
AFC-1402 Bring back the Todo-icons in the top right corner

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#358]
**Userstory:** 
As a user, I do ....

we want these icons back in the graphical interface of the Odoo Theme in the Fenix-project, but not in the CRM-project. 
Could you find the fix and break it out to a separate module for us? 

I think is is in the backend_tema-module
**Screen-shots before:**
![image](https://user-images.githubusercontent.com/9428370/98999554-4884ef80-2538-11eb-8b1e-c712ff6f9c38.png)

**Screen-shots after:**
![image](https://user-images.githubusercontent.com/9428370/98999519-3acf6a00-2538-11eb-812e-b421f14e256b.png)

**Bugreport:** (only for Issues about bugs)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-af/af_

**Module type:** 
Application/Property/Resource/Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integration:**

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1XXX-...

**Description:** 
This module 

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I find why icons gone, partner_view_360 module hide these icons. So where I need to create PR in Dev-12.0-Fenix-Sprint-02 or Dev-12.0 of odoo-base?

**Comment by FredrikArvas** [comment]
Hi,
please make a push-request to Dev-12-branch. 
With a new module for the hiding of the todo-icons as an isolated item.
Thanks

**Comment by rupareliyahemangi145** [comment]
Ok Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Create PR - https://github.com/vertelab/odoo-base/pull/153 Removed functionality of hiding top icons from **partner_view_360** and Added new module **af_hide_top_todo_icons** to add functionality for hiding icons.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
