### ISSUE TITLE
AFC-1279b - upgrade OCA hr_employee_legacy_id module

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#362]
**Userstory:** 
As a user, I want to use the module hr_emmployee_legacy_id in version 12.

Please estimate what it takes to migrate to Odoo CE v12
https://github.com/OCA/hr/tree/10.0/hr_employee_legacy_id

**Module name:** 
odoo-hr/hr_employee_legacy_id

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**

**Test-data:**

**Branch name:** 
12.0-AFC-1279

**Description:** 
This module adds a field for an external Employee ID to the HR-form.

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by FredrikArvas** [comment]
If this is within the usual 2 hours, please go ahead.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-hr/pull/17 for this issue.

Here is screenshot:

![legacy](https://user-images.githubusercontent.com/36560391/99488012-7a111700-298d-11eb-90db-386eb721cfb7.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Spent time 40 mins.
