### ISSUE TITLE
AFC-1346 - API Deviation Report (SV: Avvikelserapport)

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#363]
**Userstory:** 
- Creation of swagger file from description attached.
- Implementation of integration modules concerning showing order.
-- Client API module - System parameters for host and base-url
-- Server API module - Dummy responses for each function
- Creation of a server action for each endpoint (for test)

**Data**
[publish-for-fenix_json.txt](https://github.com/vertelab/odoo-af/files/5545381/publish-for-fenix_json.txt)

**Module name:**
odoo-hr/hr_jobseeker_deviationreport_ipf_client (old name)
odoo-outplacement/outplacement_deviationreport_ipf_client (new name, will be changed later)
odoo-hr/hr_jobseeker_deviationreport_ipf_server
odoo-outplacement/outplacement_deviationreport_ipf_server (new name, will be changed later)

**Module type:** 
API-Module

**Test-steps:**
Server action from the client to the server.

**Branch name:** 
12.0-AFC-1346.

**Description:** (Manifest description)
This module handles the integration between Fenix and ABS, handling the deviation report (Avvikelserapport).

**Estimate:** (added by developers only)
Estimated Hours: 4h
Estimated Date: 17/11/2020
Actual Hours: 5h

**Comment by n-development** [comment]
Development | 04:00

**Comment by FredrikArvas** [comment]
Hi, 

We have decided to move and change the name of these modules, when they are merged into the Dev-12.0-Fenix-Sprint-02-branch.
odoo-hr/hr_jobseeker_deviationreport_ipf_client (old name)
odoo-outplacement/outplacement_deviationreport_ipf_client (new name, will be changed later)
odoo-hr/hr_jobseeker_deviationreport_ipf_server
odoo-outplacement/outplacement_deviationreport_ipf_server (new name, will be changed later)

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated estimates and deadline and actual hours.

**Comment by Yevhen-Pechurin** [comment]
Hi @anderswallenquist @nils-vertel 
What's the name of module i can to write in dependends hr_jobseeker_deviationreport_ipf_client or outplacement_deviationreport_ipf_client?

**Comment by nils-vertel** [comment]
@Yevhen-Pechurin 
outplacement_deviationreport_ipf_client
Its not completely in place yet but its close enough to do the switch

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-hr/pull/41

**Comment by arturchilangwa-vertel** [comment]
Closed because of wrong base branch vertelab/odoo-hr#41
OLD: Merged https://github.com/vertelab/odoo-hr/pull/42
Moved to:  https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_deviationreport_ipf_client
