### ISSUE TITLE
AFC-1382 - Integration Fenix - TLR 

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#371]
**Userstory:** 
See attached file for information about endpoints, messages and record **Note that only /tjansteleverantor /utforandeVerksamhet endpoints need to be implemented** 
[TLR - Tjänsteleverantörsregister.txt](https://github.com/vertelab/odoo-af/files/5558233/TLR.-.Tjansteleverantorsregister.txt)

- Implementation of integration modules between Fenix and TLR.
   - Client API module - System parameters for host and base-url
   - Server API module - Dummy responses from each function.
- Creation of a server action for each endpoint (for test)

**Module name:** (added by Nils or Fredrik)
odoo-api/api_ipf_tlr_client
odoo-api/api_ipf_tlr_server

**Module type:** 
API-Module

**Test-steps:**
Server action for each implemented endpoint
**Test-data:**

**Branch name:** 
12.0-AFC-1382-integration-Fenix-TLR

**Description:** 
This module is an API module between Fenix and TLR

**Estimate:** (added by developers only)
Estimated Hours: 12h
Estimated Date: 24/11/2020
Actual Hours: 12h

PR https://github.com/vertelab/odoo-api/pull/2

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated estimates and deadline and actual hours.

**Comment by arturchilangwa-vertel** [comment]
The code that was merged for this issue https://github.com/vertelab/odoo-api/pull/4
