### ISSUE TITLE
AFC-1338 -API CompletionReport (Gemensam Planering)

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#375]
**Userstory:** 
See attached file for information about endpoints, messages and record 
[IPF-8216 - Gemensam planering.txt](https://github.com/vertelab/odoo-af/files/5559701/IPF-8216.-.Gemensam.planering.txt)

- Implementation of integration modules between Fenix and BÄR.
   - Client API module - System parameters for host and base-url
   - Server API module - Dummy responses from each function.
- Creation of a server action for each endpoint (for test)

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement_joint_planning_ipf_client 
odoo-outplacement/outplacement_joint_planning_ipf_server

**Module type:** 
API-Module

**Test-steps:**
Server action from client
**Test-data:**

**Branch name:** 
12.0-AFC-1338-completion-report

**Description:** (For the manifest)
This module is an API module to handle communication around joint planning (gemensam planering)

**Estimate:** (added by developers only)
Estimated Hours: 4h
Estimated Date: 24/11/2020
Actual Hours: 4h

**Comment by nils-vertel** [comment]
@AnatoliiYakymets please notice that we have renamed the modules

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated estimates and deadline.

**Comment by FredrikArvas** [comment]
Pull Request https://github.com/vertelab/odoo-outplacement/pull/2

**Comment by FredrikArvas** [comment]
@nils-vertel 
Elin Löfman just decided to skip the "status" from DAFA in the message. 
"status": "SENT", -- It can show Approved/NotApproved/In-Progress/Rejected/Cancelled/Sent 
Please take it out of the message header.

**Comment by arturchilangwa-vertel** [comment]
> Pull Request [vertelab/odoo-outplacement#2](https://github.com/vertelab/odoo-outplacement/pull/2)

Is now merged https://github.com/vertelab/odoo-outplacement/pull/2
