### ISSUE TITLE
AFC-1438 Can we remove depencency to "portal"?

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#395]
**Userstory:** 
As a user, I don't want moduls that are dependencies if not needed

**Bugreport:** (only for Issues about bugs)
The dependencies of this module indicates a dependency to "portal". But it is a "Backend"-theme. 
Could you please check what it does.

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_backend_theme_af

**Branch name:** 
Dev-12.0-Fenix-Sprint-02-AFC-1438-removed_dependency_to_portal

**Test-steps:**
Deinstall website and portal
Install the module. 
If website is not installed - then it is fine.

**Description to the manifest:** 
This version removes the depencency to website.

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-web/pull/3.
In this PR, I've removed website part from **web_backend_theme_af** and added new module **website_theme_af** for website part.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
