### ISSUE TITLE
AFC-1326 - Accessibility report for Odoo Backend

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#397]
**Userstory:** 
As a user, I want to see the Accessibility-report in the Backend GUi

1 Please add a link in the top right corner called "Accessibility Report"
2 Add a page that can be translated. 
`<h1>Accessibility report for [res.company]</h1>
<h2>Header 1</h2>
<p></p>
<h2>Header 2</h2>
<p></p>
<h2>Links</h2>
https://www.funka.com/design-for-alla/lagar-och-regler/</BR>
https://www.funka.com/design-for-alla/lagar-och-regler/webbtillganglighetsdirektivet/</BR>
https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32019L0882&qid=1559901328978&from=EN</BR>
https://www.boia.org/products/wcag-2-0-aa-audit-report/</BR>
https://www.a11yproject.com/</BR>`

3 add a user-group a11y_editor "Accessibility Editor", include admin to the group.

**Screen-shots with changes:** (illustration of proposed changes)
![image](https://user-images.githubusercontent.com/9428370/99882974-66cba900-2c24-11eb-8f07-677bdd5519d4.png)

![image](https://user-images.githubusercontent.com/9428370/99883104-6089fc80-2c25-11eb-9a9f-5e2032fffc13.png)

4 add a csv-file to the report-module and make it load /data/ir.config_parameters.csv
"id","key","value"
"import.ir_config_parameter_web_dialog_size_max","web_dialog_size.default_maximize","True"

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Module name:** 
odoo-web/web_a11y_report

**Branch name:** 
Dev-12.0-AFC-1326-A11y-report.

**Module type:** 
Application [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
install the module
enable ally_editor for the logged in user
Go to Global settings page
Enter Some A11y-report-text
Login with any user (demo/demo)
Click on the link

**Test-data:**

**Description to the manifest:** 
This module adds a section in the global settings for Accessibility Report to display a report of the backoffice adherance to the Accessibility rules.

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours: 7 Hours and 40 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I'll check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

 2 Add a page that can be translated.
- When user click on "Accessibility Report" link need to redirect website page? with Header 1, Header 2 and Links?

What I need to list in Accessibility report section in global setting?

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
I would not like to use the website for the A11y-report on "odoo-inside". 
It would be a lot better if you could create a textpage. If needed, it could be a pdf.
Any thing will work, as long as we do not use the portal (odoo-outside) website. 

A solution is to build something like the shortcut-page: But, we prefer not to have it as a pop-up (since it messes with screen-readers.
![image](https://user-images.githubusercontent.com/9428370/100058527-bcbd6e00-2e29-11eb-9dfd-557d762a52f5.png)

Is this clearer?

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Clear Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've added link Accessibility Report at top and open page like Keyboard Shortcuts.
Here is video to show:
https://www.loom.com/share/9c71347abdb848ceade77b7c5770dd81

I have found one OCA module to maximize width of dialog but for height I need to research.
Also what I need to list in global setting's Accessibility report drop down?

Please check video and let me know you feedback. 

Spent time: 1 Hour and 40 mins.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks @rupareliyahemangi145 
Is it possible to display as a normal page, instead of a pop-up?
Otherwise, the hight will probably extend when we add more text.

**Comment by Viltersten** [comment]
Something to keep in mind, if you haven't already thought of it. The link to the A11Y info (accessibility report) is best presented on the front page (landing page, first accessible page prior to credential checks). It's preferably leading the user to an HTML document within the site's domain, not a text/Word document (and definitely not a PDF). Said HTML page must be a11y compliant.

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 more on the same topic. 
Thanks @Viltersten for you comment. The current page is a HTML-page (or it uses the same format as all other pages on odoo-inside).

Our users will typically log in thorugh SingleSignOn. Can we display the link on the login-page as well, without enabling the website-module?


If not, then we will have the link as in your video in the first release.
Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I will try to open normal page instead of popup.
In login page means here? If static data then yes we can add.
![login_page](https://user-images.githubusercontent.com/36560391/100092948-dd62e380-2e7c-11eb-89e6-51fbabf973d0.png)

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've made link clickable. 
https://www.loom.com/share/e77f8cd23a2f435dabe1b527cc79ee23

For normal page I've researched I think we need to create model and need to save data in that model with demo data and one record. Then need to prepare html report for that and need to redirect it from Js.

Spent more 1 hour to research on normal page and clickable link.

It will take near about 2.5 or 3.5 hours more.

Please check it and let me know you feedback.

Thanks.

Best Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks @rupareliyahemangi145 
Lets go for the solution you have made now. Please push it and we will test it. 
Then we can decide on what to do as the next step. 
Thanks

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will push code.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-web/pull/6 After install module set system parameter for full width of dialog.

![system_parameter](https://user-images.githubusercontent.com/36560391/100184792-4a6f8b00-2f08-11eb-8b1c-7f6793000226.png)

Thanks.

**Comment by FredrikArvas** [comment]
Thanks @rupareliyahemangi145

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 Please add a csv-file to the report-module /data/ir.config_parameter.csv
"id","key","value"
"__export__.ir_config_parameter_web_dialog_size_max","web_dialog_size.default_maximize","True"

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
I would like two small adjustments.

1 add a csv-file to the report-module and make it load /data/ir.config_parameters.csv
"id","key","value"
"__import__.ir_config_parameter_web_dialog_size_max","web_dialog_size.default_maximize","True"

2 I can not see where I edit the report. It looks like it is in the templates-section, but please add a section here: 
![image](https://user-images.githubusercontent.com/9428370/100496542-39678980-3155-11eb-885e-e4856238c74f.png)

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

1. Ok I will add CSV file.

2. I need to list any thing here? If yes then what? Or I just need to add one template which you can edit?

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 
Yes, please add a template that I can edit. 
Is that a lot of work?

It is possible for us to edit the report in the module, but it is slower for us

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas I need to check that. I will check it and get back to you soon.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Could you please update us on the status of this?
Please remove the dependancy to the module: web_dialog_size.default_maximize, it messes up other pop-ups in the system. 

Please also go for a solution with a "normal page", that is visible to all users (without any special server action). 
Info: We have continued the development of of the Partner_Links-module so it works with dynamic links and without the "Update partner"-action. (https://github.com/vertelab/odoo-af/tree/Dev-12.0/contact_links)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas  I will check this.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

To configure template in setting I have found solution but I have question that, this content is different for all user or same?

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 
The content is the same for all users. 
:-)

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-web/pull/13 for normal page and configurable accessibility report.
Here is video: https://www.loom.com/share/1f10c834864d423c9e793b0b7b60d0b1

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Could you see if you can change what is displayed in the top-line of the page?
![image](https://user-images.githubusercontent.com/9428370/101448744-e1384080-3927-11eb-8814-ac9b92e9c40a.png)

With this change, I like the report now!

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas I will change this top line of page.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-web/pull/14 to update top line.

![accessibility_report](https://user-images.githubusercontent.com/36560391/101496519-e0d39000-398f-11eb-9509-e9142597d9f7.png)

Please check it and let me if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Currently it works a lot better. 
1 I would like you to add a new parallell link (to the left of the current link) to the attached static html-page. Store it in the module. 
[tgr.zip](https://github.com/vertelab/odoo-af/files/5663926/tgr.zip)

2 Please correct this minor typo
![image](https://user-images.githubusercontent.com/9428370/101593981-38eeae80-39f1-11eb-8522-633ad62804f9.png)

3 The reports name is displayed as "Unnamed"
![image](https://user-images.githubusercontent.com/9428370/101594107-63d90280-39f1-11eb-8586-867c5ff726d8.png)

4 There is an issue with the "Print"-button
![image](https://user-images.githubusercontent.com/9428370/101594150-76533c00-39f1-11eb-9e3b-d80eedc3c94b.png)

5 Could you change the "formatting" of the link to be displayed as the other white links in the top line of the page?
![image](https://user-images.githubusercontent.com/9428370/101594400-df3ab400-39f1-11eb-931f-62df6652e0d5.png)


5 Optional: is it possible to hide the breadcrumbs for this page only? (Without touching the other breadcrumbs in the system?
![image](https://user-images.githubusercontent.com/9428370/101594253-a7337100-39f1-11eb-870a-c474df1d7463.png)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check points.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Can you please explain first point(1 I would like you to add a new parallell link (to the left of the current link) to the attached static html-page. Store it in the module.
tgr.zip)? I don't understand. Can't see anything when click on link of tgr.zip

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Ok, 
We are testing different options to achieve the Accessibility requirements and one of them is to display a normal HTML-file, instead of the current version we have now.

May i therefore ask you to add a simple html-file in the module and create a normal link to that file.
The content of the file could be this: 
[see the Example-code with edit-mode]
<html>
<head>Title in the header</head>
<body>
<h1>Tillgänglighetsredogörelse</h1>
<p>
© Arbetsförmedlingen<br>
</p>
</body>
</html>

Here is an example on how to do it:
![image](https://user-images.githubusercontent.com/9428370/101817587-dbf31580-3b22-11eb-890f-b547c67b9e88.png)

**Comment by FredrikArvas** [comment]
This is also a reminder for later versions.
We need the report to be stored in the module. Since it will be installed on several serves.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks. I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-web/pull/15 to redirect user on HTML page. 

Here is video: https://www.loom.com/share/e09945e142e64ef49c2665bf96dfbb91?focus_title=1&muted=1&from_recorder=1

I have added HTML file inside **web_a11y_report/static/src/html** folder. With **tgr.html** name. And redirected that file as a HTML page on Accessibility report.

If you want to change this file you can change it but make sure file name must be **tgr.html**.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by arturchilangwa-vertel** [comment]
https://github.com/vertelab/odoo-web/pull/15 is now merged!
