### ISSUE TITLE
AFC-1447 - add credentials to oe_chatter instead of hiding it

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#401]
**Userstory:** 
As a user of one instance of Odoo within our client, we do want to see the oe_chatter.
As a user of one instance of Odoo within our client, we do not want to see the oe_chatter.

Current solution: 
We have removed it from the view. But this requres us to create two user-interfaces.

Proposed solution: 
Add user-groups instead. Proposed name: mail.oe_chatter_user

Then we can re-activate the chatter-widget again:
https://github.com/vertelab/odoo-base/blob/Dev-12.0/partner_view_360/views/res_partner_view.xml
https://github.com/vertelab/odoo-hr/blob/Dev-12.0/hr_office/views/hr_location_view.xml

**Bugreport:** (only for Issues about bugs)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_oe_chatter_user-groups

**Branch name:** 
Dev-12.0-Fenix-Sprint-02-AFC-1447-mail_oe_chatter_user-groups

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
install the module
see if the oe_chatter is visible in 
Contacts
Jobseekers
Employee
Location

Change the user-credentials and see visit the same views again.

**Description to the manifest:** 
This module adds a user-group to the oe_chatter-widget, in order to control who can see it.

**Estimate:** (added by developers only)
Estimated Hours: 4h
Estimated Date: 24/11/2020
Actual Hours:4h

**Comment by nils-vertel** [comment]
@vertelab/n-development Please estimate this issue

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-vertel, I`ve updated estimates and actual hours.

**Comment by FredrikArvas** [comment]
@Yevhen-Pechurin 
Please add a PR for the branch and a link here.
https://github.com/vertelab/odoo-mail/tree/Dev-12.0-Fenix-Sprint-02-AFC-1447-mail_oe_chatter_user-groups

**Comment by FredrikArvas** [comment]
@nils-vertel  Please review this code and my comment in a separate email.

**Comment by Yevhen-Pechurin** [comment]
https://github.com/vertelab/odoo-mail/pull/2

**Comment by arturchilangwa-vertel** [comment]
module `mail_oe_chatter_user-groups` is now merged 
https://github.com/vertelab/odoo-mail/pull/2
