### ISSUE TITLE
AFC-1174 - Devation-report Functionality

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#402]
**Userstory:** 
As a user, I want to do a devation-report when a jobseeker does not attend the education program.

**Screen-shots with changes:** (illustration of proposed changes)
Step 0: Display the oe_chatter on the Project-form view. (If this is difficult, keep to the task-form view)

Step 1: Click "Schedule a Activity" -> Select "Deviation Report"
![image](https://user-images.githubusercontent.com/9428370/99911026-e96e6a00-2cf1-11eb-8ebf-f8f9fc88f6e1.png)

Step 2: 
A form opens which has fields for structured message:
![image](https://user-images.githubusercontent.com/9428370/99911187-e88a0800-2cf2-11eb-950d-3ff0ca9c8c2a.png)

Step 3: 
This form should store the reasons
Display the fields listed in step 4.

Step 4: When I click submit. The integration takes over and reports back the status in a "Status"-field displayed on the project-kanban-view.

The following fields should be connected: (See integration:  https://github.com/vertelab/odoo-af/issues/363 for details.) 
 "arbetssokande": {
            "personnummer", = **res_partner.social_sec_nr**
            "fornamn", = **res_partner.first_name**
            "efternamn" = **res_partner.last_name**

"ansvarig_arbetsformedlare": { = **res_partner.user_id**

"leverantor": {
            "leverantorsnamn", res_company.name
            "rapportor", res_user
            "kanummer" res_user.hr_employee.department.legacy_id (the legacy_id of the users connected department location)

 "franvaro": {
            "orsak", = mail_activity.deviation_reason (see property tree with reason)
            "datum", mail_activity.deviation_date
            "heldag", mail_activity.deviation_allday
            "starttid", mail_activity.deviation_timestart
            "sluttid" mail_activity.deviation_timeend

**Module name:** (added by Nils or Fredrik)
odoo-outplacemnt/outplacement_deviation-report

**Branch name:** 
Dev-12.0-Fenix-Sprint-02-AFC-1174-Deviation-report

**Module type:** 
Propertymodule [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integration:**
 https://github.com/vertelab/odoo-af/issues/363

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module adds a Deviation report to the "Schedule Activity" form in the oe_chatter-widget. 

**Estimate:** (added by developers only)
Estimated Hours: 10h
Estimated Date: 01/12/2020
Actual Hours: 6h

**Comment by nils-vertel** [comment]
@vertelab/n-development please Estimate this issue

**Comment by FredrikArvas** [comment]
From Analotlii: 
I have some questions. Why you need to create Deviation Report through schedule activity? I suggest to add button Deviation Report in top of form or next to schedule activity button. And after clicking this button, a form will open.

**Comment by FredrikArvas** [comment]
Hi @AnatoliiYakymets 
1 Thanks for asking and suggesting a different solution to what we suggested. 
2 I don't have any problems with a button.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated the deadline.

**Comment by n-development** [comment]
I`ve updated the actual hours.

**Comment by FredrikArvas** [comment]
@n-development  Please make a PR and paste a link here.

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/8

**Comment by arturchilangwa-vertel** [comment]
@FredrikArvas @nils-vertel 
Code looks good in https://github.com/vertelab/odoo-outplacement/pull/8 the `outplacement_deviationreport_ipf_client` (AFC-1346, https://github.com/vertelab/odoo-af/issues/363) module for making it work. 
I have not tried to install the module beacuse it misses that ipf_client.
And my guess that it is on its way.
