### ISSUE TITLE
AFC-613 - Please make a PR for these changes to Fenix-branch also

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#403]
**Userstory:** 
As a user, I want these changes https://github.com/vertelab/odoo-af/pull/387/files 
to in this module https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/website_theme_af

Reason: We have the same theme in two different modules (unfortunately) for a few more days.

**Module name:** (added by Nils or Fredrik)
odoo-web/website_theme_af

**Branch name:** 
Dev-12.0-Fenix]-Sprint-02-AFC-613-Test new GUI for visually impaired readers 

**Description to the manifest:** 
This update adds changes to the main navigation to enable screen readers (A11y-update)

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145  
Please make a second PR for this code into the new location of the module. 
Thanks

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Create PR https://github.com/vertelab/odoo-web/pull/4 to add mentioned file in new location.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
