### ISSUE TITLE
AFC-1445 - please move and make pr for these theme-modules 

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#407]
**Userstory:** 
As a user, I want modules to be placed in the right repo and the right branch. 
Please move and make a PR for this module: 
https://github.com/vertelab/odoo-**web**/tree/Dev-12.0-Fenix-Sprint-02/website_theme_af
to
https://github.com/vertelab/odoo-**website**/tree/Dev-12.0-Fenix-Sprint-02/website_theme_af

Please move and make a PR for this module: 
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_backend_theme_af
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_one2many_kanban
to
https://github.com/vertelab/odoo-web/tree/Dev-12.0/

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Ok sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR in odoo-web:Dev-12.0 for web_backend_theme_af and web_one2many_kanaban
- https://github.com/vertelab/odoo-web/pull/8

But I can't find Dev-12.0-Fenix-Sprint-02 branch in odoo-website(https://github.com/vertelab/odoo-website).

**Comment by FredrikArvas** [comment]
You are right about the missing branch. 
Can you create one?

**Comment by rupareliyahemangi145** [comment]
Ok I will create.

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Should I need to create branch from master or 12.0?

**Comment by FredrikArvas** [comment]
Please from 12.0

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks

**Comment by FredrikArvas** [comment]
I have created these branches now: 
https://github.com/vertelab/odoo-website/tree/Dev-12.0-Fenix-Sprint-02

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas 

Create PR https://github.com/vertelab/odoo-website/pull/2 for website_theme_af.

Spent time: 1 hour.
