### ISSUE TITLE
AFC-1382b - Connection between API DAFA - TLR #371 and Odoo

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#414]
**Userstory:** 
As user, I want the data about the company-details and departments to be filled in by the API
Please add an "Action" to "Update TLR-data" for the selected records res_partner.legacy_id and updates it.

![image](https://user-images.githubusercontent.com/9428370/100518267-d1369900-3190-11eb-84a0-143530e83438.png)

The information is fetched with: 
odoo-api/api_ipf_tlr_client

It should be triggered by a Server Action on the contact-card with the key-value from: res_partner.partner_legacy_id
It should also be triggered by an incoming new Suborder (SV: Avrop). 

Info:   "/lista/tjansteleverantorer": = List of suppliers
          "/sok/utforandeVerksamhet":  = Search for Subsidiary 
         "/sok/utforandeVerksamhet/{organisationsnummer}": Search for Subsidiary with the value from the field "res_partner.parent_id.company_registry"
         "/hamta/utforandeVerksamhet/{utforande-verksamhet-id}" Get Subsidiary with the value from "res_partner.legacy_id"
             "/hamta/adress/{adress-id}" Get Address with the value of Addres_id (which i am not sure of where we store...)

**Endpoint1**: The (education) Organisation. 
(Internal link https://eu1.anypoint.mulesoft.com/exchange/1dae6e32-bf25-4b52-aa03-8f32e1f5fc08/tjansteleverantorsregister/minor/1.0/console/method/%232198/

/hamta/tjansteleverantor/{tjansteleverantor-id}
Fields: 
<ns107:tjansteleverantorId> res_partner.partner_legacy_id
<ns107:namn> res_partner.name (or res_company.name, id=1)
<ns107:organisationsnummer> res_partner.company_registry
<ns107:hemsida> res_partner.website
<ns107:teleadressfax>res_partner.fax
<ns27:telefonnummer>res_partner.phone

List of contact-persons:
<ns107:kontaktpersonLista>
     <ns25:kontaktpersonId> res_partner.partner_legacy_id
     <ns26:Fornamn>res_partner.first_name
     <ns26:Efternamn>res_partner.last_name
     <ns27:telefonnummer>res_partner.phone
     <ns25:epost>res_partner.email
</ns107:kontaktpersonLista>

<HR>

**Endpoint2:** 
/hamta/utforandeVerksamhet/{utforande-verksamhet-id}

This should be stored as departments and linked addresses.
This moudule links this: https://github.com/vertelab/odoo-af/issues/176

Fields: 
 <ns64:utforandeVerksamhetId> (hr.departments with their res.partners that are linke to res.company id=1 as their parent)

ns64:namn "res_partner.name"

start loop - ns64:kontaktpersonIdLista
ns64:avtalId use "res_partner.category_id" for now
ns23:adressId use the "external_id" field and build an external-id that we can use to update.
ns23:adressrad "res_partner.street"
ns23:postnummer "res_partner.zip"
ns23:postort "res_partner.city"
ns23:lanskod "res_partner.country_id.name"
ns23:kommunkod "res_partner.state_id"
end loop - ns64:kontaktpersonIdLista

<HR>

**Module name:** (added by Nils or Fredrik)
odoo-base/partner_tlr_update 

**Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1382b-Connection_glue_module

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**
Integration module: https://github.com/vertelab/odoo-af/issues/371
Link between hr.department and res.partner https://github.com/vertelab/odoo-af/issues/176

**Test-steps:**
Install the module on the clients network.
Add a Legacy_id to the Company-record.
Click the Actio:  "Update TLR-data"
The Information should be updated.

**Test-data:**
See: https://confluence.ams.se/pages/viewpage.action?pageId=76597519

**Description to the manifest:** 
This module links the TLR-API to the Odoo-logic and adds res-partner-data for the company and its contac-persons.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 12h
Estimated Date: 03/12/2020
Actual Hours: 12h

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel Estimation done, waiting for approval.

**Comment by n-development** [comment]
Hello @FredrikArvas, tell me, please answer these questions:
1. Could you give me sens legacy _ID field( This`s an internal or external field?) I haven`t found it in the code. How I can find it?
2. We need to Trigger` condition because didn`t know what I should trigger and when I need to do it. Tell me, please more details about Trigger.
3. In Endpoint 2, some fields unknown, because the description of it doesn`t exist. Could you add this description, please?
4. Some fields in the endpoint that doesn`t default in Odoo. I need information on which module these fields exist. Example first_name field.
5. How I should add Legacy_ID and Company_ID fields?
6. How must work Endpoint? Should it go from us to you, or not? Tell me, please more information about endpoints work.

**Comment by n-development** [comment]
@nils-vertel maybe we can get this point not only from @FredrikArvas?

**Comment by FredrikArvas** [comment]
@n-development I have updated part of the answer.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel Estimated added. 12h.

**Comment by FredrikArvas** [comment]
@n-development and @Yevhen-Pechurin 
I have now added the rest of the answers. Please confirm if this is enough

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas 
Endpoint1 and Endpoint2 are the same? Module api_ipf_tlr_client don't have these enpoints, it has the similar endpoint /hamta/tjansteleverantor/{tjansteleverantor-id}

**Comment by FredrikArvas** [comment]
@Yevhen-Pechurin I have revisited the integration-specification and found better endpoints. 
I send my apologies for a requirements specification that was not ready for development. :-(
Let´s try to make this work together.

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas Could you give me example of xml with some contact-persons and departments?

**Comment by FredrikArvas** [comment]
@Yevhen-Pechurin 
Good point!
I need to ask someone for that, since the swagger-file is so large. But it is a good suggestion.

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas swagger-file contains only one contact-person and one department, but i need more then one for implementation functionality.

**Comment by arturchilangwa-vertel** [comment]
@Yevhen-Pechurin 
> @FredrikArvas swagger-file contains only one contact-person and one department, but i need more then one for implementation functionality.

Here is some test data:  [AFC-1382b_test_data.zip](https://github.com/vertelab/odoo-af/files/5637045/AFC-1382b_test_data.zip)

**Comment by n-development** [comment]
Hello @FredrikArvas , I`ve added the Actual Hours.

**Comment by FredrikArvas** [comment]
Hi @n-development and @Yevhen-Pechurin 
What is the status of this development?
I can see a branch but no changes. 
https://github.com/vertelab/odoo-base/tree/Dev-12.0-DAFA-Sprint-02-AFC-1382b-Connection_glue_module
Please give us an update. If the code is ready, please make a Pull Request and add a link to it here. 
thanks
/Fredrik

**Comment by Yevhen-Pechurin** [comment]
Hi @FredrikArvas 
I have created Pull Request in another repo by mistake. I've fixed it.

**Comment by FredrikArvas** [comment]
Thanks @Yevhen-Pechurin 
Please add a link to the repo where it is pushed here, or if it is not merged yet, please cancel that PR and add one here. 

This will help us find the code when we need to go back to it. (That is also why the comit-messages are so important).

**Comment by Yevhen-Pechurin** [comment]
Dev-12.0-DAFA-Sprint-02-AFC-1382b-Connection_glue_module

**Comment by arturchilangwa-vertel** [comment]
@FredrikArvas 
Is now merged https://github.com/vertelab/odoo-base/pull/185
