### ISSUE TITLE
AFC-1382c Create a partner_legacy_id module based on hr_employee_legacy_id

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#416]
**Userstory:** 
As a user, I want an external partner ID to be stored, to keep reference to other systems.
Create a module, that is similar to this: 
https://github.com/vertelab/odoo-hr/tree/Dev-12.0-Fenix_Sprint-02/hr_employee_legacy_id

**Screen-shots with changes:** (illustration of proposed changes)
![image](https://user-images.githubusercontent.com/9428370/100405727-7dc72c80-3064-11eb-8a3d-00d80c2c9578.png)
**Module name:** (added by Nils or Fredrik)
odoo-base/partner_legacy_id

**Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1382c-partner_legacy_id

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install the module
Go to Contact-card
the field should be visible in the left column

**Description to the manifest:** 
This module adds a extra customer ID-field to be used for id-numbers in external or legacy systems.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 40 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-base/pull/167 for this issue.

Here is screenshot:

![partner_legacy](https://user-images.githubusercontent.com/36560391/100420906-55175500-30ad-11eb-9a8d-cc8d00cacd61.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks again, 
you are like lightning fast!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas
