### ISSUE TITLE
AFC-1476 UserAdminWizard for DAFA

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#418]
**Userstory:** 
As an SuperAdmin of DAFA, I want to CRUD users with a wizard, not with a form, because I should not be able to write directly to the user-table.

Scenario: 
SuperAdmin logs in. 
Goes to Employee-page
Clicks Create new Employee
Enters details
Clicks "Assign User Groups"-button
A wizard starts with a form with a list of user-rights. 
When I click save, the wizard (if needed creates a user, link it to the employee), saves the user-rights on the user.
Close the wizard and the user-rights are displayed on the Employee-form.

Example of design
![image](https://user-images.githubusercontent.com/9428370/100478930-0a1d3200-30ed-11eb-85c9-e1c0ccf2ada8.png)

Link to xml-file that creates user-groups: (the module is not ready yet, but please use these groups)
https://github.com/vertelab/odoo-af/blob/AFC-1187-kvl_behorigheter_Fenix_02/af_kvl_test_behorigheter/security/security.xml

The user needs to have Admin-user-rights for running the wizard. 

**Module name:** (added by Nils or Fredrik)
odoo-auth/auth_user-rights_wizard (the user-wizard)
odoo-hr/hr_user_ciam_update  (the glue module)
odoo-hr/hr_employee_ciam_client (the api-module)

**Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1476_UserAdminWizard

Branch: Dev-12.0-Fenix_Sprint-02_AFC-1476-UserAdminWizard-for-DAFA

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**
odoo-hr/hr_employee_ciam_client (the api-module)

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module adds a wizard to edit user-rights without the user having write-access on the to the res.user-class.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
![image](https://user-images.githubusercontent.com/7355805/100513442-79d40100-316f-11eb-9b82-5d725ef6d107.png)

![image](https://user-images.githubusercontent.com/7355805/100513594-835d6900-316f-11eb-956a-e2a658bbdf86.png)

I am unable to push to the [odoo-auth](https://github.com/vertelab/odoo-auth/) repository. I need access

**Comment by FredrikArvas** [comment]
hi @iammiracle 
Great!
Did you ad a filter on the "Assign User Rights"-view to only display user-rights with the name *dafa* in their name?

**Comment by FredrikArvas** [comment]
@iammiracle Please also filter the user-rights on the employee-cards to user-groups with the name "dafa" in their names. 
Can you filter on the technical-group-name and not the display-name?

**Comment by FredrikArvas** [comment]
Here comes more work on this issue!

Is is possible to trigger this API when a "new user with a DAFA-user-rights-group" is created or deleted?
This module: https://github.com/vertelab/odoo-hr/tree/Dev-12.0-Fenix_Sprint-02/hr_employee_ciam_client that is created by this issue: https://github.com/vertelab/odoo-af/issues/320

I think this can be done if your module calls a "action" on the CIAM-API. But this is a @iammiracle-question how these things work...

**Comment by iammiracle** [comment]
> 
> 
> @iammiracle Please also filter the user-rights on the employee-cards to user-groups with the name "dafa" in their names.
> Can you filter on the technical-group-name and not the display-name?

@FredrikArvas the dafa user group record is not available in any of the modules in my environment, like you said that the groups are available [here](https://github.com/vertelab/odoo-af/blob/AFC-1187-kvl_behorigheter_Fenix_02/af_kvl_test_behorigheter/security/security.xml) but not ready, unless I want to duplicate the groups already created in this moduel

**Comment by iammiracle** [comment]
> 
> 
> Here comes more work on this issue!
> 
> Is is possible to trigger this API when a "new user with a DAFA-user-rights-group" is created or deleted?
> This module: https://github.com/vertelab/odoo-hr/tree/Dev-12.0-Fenix_Sprint-02/hr_employee_ciam_client that is created by this issue: #320
> 
> I think this can be done if your module calls a "action" on the CIAM-API. But this is a @iammiracle-question how these things work...
> 
> You will not be able to test this, since it needs to run on the inside of the clients network.
> One solution could be to create a temporary second "action" that triggers the API. Hereby we can have the original functionality, that can be tested outside and then the link between the API and the module.
> 
> I think that "action" should be stored on the CIAM-module, rather than on this wizard-module. Because the wizard-module is useful for other clients as well.

I am not sure, I get this, maybe you can show me, where will the action be, on employee form? and what will the action be doing?

**Comment by FredrikArvas** [comment]
Suggested name of the CIAM-Action = Update CIAM for user

**Comment by iammiracle** [comment]
> 
> 
> @iammiracle Please also filter the user-rights on the employee-cards to user-groups with the name "dafa" in their names.
> Can you filter on the technical-group-name and not the display-name?

I just filtered the group based on the name, as you can't have access tot the technical group name. So the filter is ('name', 'ilike', 'DAFA'), which means any group that contains DAFA will be displayed. I hope that helps

**Comment by FredrikArvas** [comment]
Yes @iammiracle 
That is perfect for now.

**Comment by iammiracle** [comment]
Here is the PR for [CIAM User Update](https://github.com/vertelab/odoo-hr/pull/28) 

Here is the PR for [User Right Wizard](https://github.com/vertelab/odoo-auth/pull/2)

**Comment by FredrikArvas** [comment]
@robch2342 Here are two modules to link the CIAM-integration to Odoo. 
I think the next step now is to review, merge, and build a new DAFA-pod and test it with Keith.

**Comment by FredrikArvas** [comment]
@iammiracle - Did you manage to test it with two Odoo-databases?

**Comment by iammiracle** [comment]
@FredrikArvas - No, but I tried connecting with the CIAM server module, i made a request and I got Unauthorized response, I guess someone with the internal access will be able to test what I have added and complete the module.

**Comment by FredrikArvas** [comment]
Ok. 
thanks!

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
@robch2342 has reviewd the code and would like the following changes: 

1 Please do not change anything on the "model_access" on the groups.
2 The user who runs the wizard should not have write-access on the res.user. This write-access needs to be set with a "sudo"-code in the wizard. 
3 We need to check that the user who runs the wizard also belongs to the "Super-Admin"-group. 
See https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/base_user_groups_dafa for a module with the groups.
4 Please limit the assignments to the DAFA-groups in the logic, not only in the view - because of security reasons.
5 On the hr.employee, we should list res.groups, not ir.model.access.
6 Please display the cusers current groups in the wizard

Optional in this release:
7 It would be useful to be able to allow assignment of multiple groups in one go. Currently, it only allows one group at a time.

Thanks

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Can you please push the code you have so far in about an hour and we can install and test that?
Thanks
Fredrik

**Comment by iammiracle** [comment]
Hi @FredrikArvas, I need few clarifications;

**Point 1:** I have not changed anything regarding model_access
**Point 2 and 3**: I understand you don't want the person running the wizard to have write access to res.user, yet you want the person to be a Super Admin group, this means, the Super Admin group will not have write access to res.user, kindly confirm this is what you meant, so i can create a record rule around this.

Other points are sorted.

**Comment by iammiracle** [comment]
> 
> 
> Hi @iammiracle
> Can you please push the code you have so far in about an hour and we can install and test that?
> Thanks
> Fredrik

@FredrikArvas Here is the [PR](https://github.com/vertelab/odoo-auth/pull/3), as regarding what has being done

**Comment by FredrikArvas** [comment]
Thanks @iammiracle 

Hi @FredrikArvas, I need few clarifications;

Point 1: I have not changed anything regarding model_access. 
- OK I will ask @robch2342  again, he said it looked like you had code that worked with model_access. I will come back

Point 2 and 3: I understand you don't want the person running the wizard to have write access to res.user, yet you want the person to be a Super Admin group, this means, the Super Admin group will not have write access to res.user, kindly confirm this is what you meant, so i can create a record rule around this.
- Correct. It is a bit strange. The SuperAdmin is not a real SuperAdmin, it is more like a person who is allowed to edit users (at this point). We will create three levels of "ServiceDeskAdmins" who will have "Real access".

Other points are sorted.
- great!

**Comment by FredrikArvas** [comment]
@iammiracle - question: How do I get the "Action" to be visible?

- The module auth_user-rights_wizard is installed.
- The user has DAFA Admin and DAFA SuperAdmin
![image](https://user-images.githubusercontent.com/9428370/100858961-f0823e80-348e-11eb-8b78-baca1763770b.png)
- do I need to do something to the action:?`
![image](https://user-images.githubusercontent.com/9428370/100859122-27585480-348f-11eb-8eec-6fd1f4bbd29b.png)

**Comment by iammiracle** [comment]
@FredrikArvas if the user has superadmin right then it should be visible, refresh the employee form it should be there

**Comment by FredrikArvas** [comment]
Thanks @iammiracle 
"Refresh for president" 
:-)

**Comment by FredrikArvas** [comment]
I will close this issue and open a new with suggested changes, when I have worked with the UX-designers.
