### ISSUE TITLE
AFC-1282b add test-data with Education companies

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#420]
**Userstory:** 
I want testdata to be loaded with the demo-data-setting
[DAFA_Partner_Demo_Data.zip](https://github.com/vertelab/odoo-af/files/5612211/DAFA_Partner_Demo_Data.zip)

**Module names:**
**Add partner-test-data here**: 
https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/partner_test-data_fenix

**Add bank-test-data here**: 
https://github.com/vertelab/odoo-account/tree/Dev-12.0-DAFA-Sprint-02/partner_test-data_dafa (create new branch)

**Add contract-test-data here**:
https://github.com/vertelab/odoo-account/tree/Dev-12.0-DAFA-Sprint-02/contract_test-data_dafa
(with a depend to this module https://github.com/OCA/contract/tree/12.0/contract) 

**Module type:** 
Resource module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Description to the manifest:** 
This module adds testdata to be used in the KVL and STOM-projects. The source of the data is here: https://confluence.ams.se/pages/viewpage.action?pageId=76597519

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by FredrikArvas** [comment]
HI @iammiracle 
here is an other issue with a file of test-data that needs to be divided into several mallar modules and files. 
Please proceed and ask if you have questions.

**Comment by iammiracle** [comment]
Hi @FredrikArvas adding bank account number will require partner record, do you want me to depend on the **partner-test-data** or do you want me to create new set of partners for the **bank-test-data** module

**Comment by iammiracle** [comment]
PR for **[partner_test_data](https://github.com/vertelab/odoo-base/pull/172)**

PR for **[bank_test_data](https://github.com/vertelab/odoo-account/pull/1)**

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
I have reviewed the file and I would like you to add the following fields
- tags
- legacy_id
- create an external_id based on the "Address id" instead of the name.

![image](https://user-images.githubusercontent.com/9428370/100580784-de659c00-32e6-11eb-8af4-0c8aba056215.png)

Please also add a module with testdata for contracts-module
![image](https://user-images.githubusercontent.com/9428370/100580926-1967cf80-32e7-11eb-9ccf-be6fc97ac04d.png)

**Comment by arturchilangwa-vertel** [comment]
PR for [partner_test_data](https://github.com/vertelab/odoo-base/pull/172/files) is now merged

**Comment by iammiracle** [comment]
> 
> 
> Hi @iammiracle
> I have reviewed the file and I would like you to add the following fields
> 
>     * tags
> 
>     * legacy_id
> 
>     * create an external_id based on the "Address id" instead of the name.
> 
> 
> ![image](https://user-images.githubusercontent.com/9428370/100580784-de659c00-32e6-11eb-8af4-0c8aba056215.png)
> 
> Please also add a module with testdata for contracts-module
> ![image](https://user-images.githubusercontent.com/9428370/100580926-1967cf80-32e7-11eb-9ccf-be6fc97ac04d.png)

@FredrikArvas where will the legacy_id, tags and address_id be, I mean the module. Then this fields are not available by default, should I create these fields?

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Here is the module: 
https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/partner_legacy_id

The address ID is a Swedish description. 
Please create an "odoo" external_id based ont he number in the D-column.

**Comment by arturchilangwa-vertel** [comment]
Code worked for bank_test_data https://github.com/vertelab/odoo-account/pull/1
