### ISSUE TITLE
Renaming and moving odoo-web-modules

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#422]
Please move these modules:

Move: https://github.com/vertelab/odoo-web/tree/Dev-12.0/website_theme_af
to: https://github.com/vertelab/odoo-**website**/tree/Dev-12.0/website_theme_af

Copy: https://github.com/vertelab/odoo-af/tree/Dev-12.0/af_gui_disabeling
to
https://github.com/vertelab/odoo-**web**/tree/Dev-12.0/**web_gui_disabeling_af**
Add the "Depreciated" before the display-name of the module on the old place
Add "Installable=False"

Move: https://github.com/vertelab/odoo-af/tree/Dev-12.0/web_autocomplete_off
to: https://github.com/vertelab/odoo-**website**/tree/Dev-12.0/web_autocomplete_off

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 40 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will do this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Create following PRs:

To add website_theme_af in odoo-website : https://github.com/vertelab/odoo-website/pull/3
To add web_gui_disabeling_af in odoo-web : https://github.com/vertelab/odoo-web/pull/10
To add Depreciated and Installable False in af_gui_disabeling in odoo-af : https://github.com/vertelab/odoo-af/pull/423
To add web_autocomplete_off in odoo-website : https://github.com/vertelab/odoo-website/pull/4

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by arturchilangwa-vertel** [comment]
The old modules that will be removed: 

1.  website_theme_af in odoo-web https://github.com/vertelab/odoo-web/pull/11
2.  web_autocomplete_off in odoo-af (Dev-12.0 branch) https://github.com/vertelab/odoo-af/pull/438
3. web_autocomplete_off in odoo-af (Fenix-sprint branch) https://github.com/vertelab/odoo-af/pull/439
