### ISSUE TITLE
Add Translations and Documentation in modules.

### ISSUE THREAD

**Issue by rupareliyahemangi145** [vertelab/odoo-af#425]
Add Translations and Documentation in modules.

af_core_menu_disabling
#af_backend_tema - replaced 2020-11-25 by web_backend_theme_af
af_gui_disabeling
af_hide_top_todo_icons
odoo-sale/af_order_report
web_autocomplete_off

Actual Hours: 1 hour and 30 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Create PR https://github.com/vertelab/odoo-af/pull/426 to add translation and index file for af_core_menu_disabling module.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
This looks great and is a good level of ambition!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created PR to add index file for **web_gui_disabeling** and **web_gui_disabeling**
https://github.com/vertelab/odoo-web/pull/18
https://github.com/vertelab/odoo-web/pull/15/commits

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by arturchilangwa-vertel** [comment]
`af_core_menu_disabling` is now merged https://github.com/vertelab/odoo-af/pull/426/
