### ISSUE TITLE
AFC-1154 Order Interpreter - GUI

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#427]
**Userstory:** 
As a user, I want to order an  interpreter when a job seeker needs help with the language.

**Screen-shots with changes:** (illustration of proposed changes)
Step 1:  Press scedule activity
![Inked100875194-fc2d2f80-34a5-11eb-9bb2-483fba1440b4_LI](https://user-images.githubusercontent.com/72382478/101036347-4af8c900-357b-11eb-96e8-0b5272b88806.jpg)

Step 2: Selecting the "order interpreter" must automatically open the "Schedule a Activity"  Display the oe_chatter on the Project-form view. (If this is difficult, keep to the task-form view)

Step 3: Click on "Schedule a Activity" -> Select "Order Interpreter" from the schedule activities list and then schedule.

![image](https://user-images.githubusercontent.com/59916603/100732730-6d4ce400-33cd-11eb-90e0-526315c2dd70.png)

Step 4: The form must be opened which stores the data about the interpreter.

![image](https://user-images.githubusercontent.com/59916603/100700930-eed94d80-339e-11eb-9e9f-a3c8f482de19.png)

Step 5: Create the following field and need to input the data in the following fields in the " order interpreter activity form" (mail.activity.type)

| Form Fields | Label | Default value | Notes |
| ------------- | ------------- | ------------- | ------------- |
| interpreter_gender_preference | Interpreter Gender Preference |  task.outplacement_id.partner_id.interpreter_gender_preference | 
|Interpreter_ref | Interpreter reference|
| interpreter_language|  Interpreter Language|  task.outplacement_id.partner_id.lang | |
| location_type | Location | | Location Type Selection(On premise, Telephone)|
| time_start | Start Time | | Date-Time |
| time_end |  End Time | | Date-Time |
| phone | Phone |  | Field only visible when user has selected location_type Telephone|
| address | Address | task.outplacement_id.departement_id.address_id.[street, street2, zip, city] | Unpack in to several subfields with name address_<field>, Section only visible when user has selected location_type on_premise|

Step 6:Check the picture to locate the fields in the form.

![image](https://user-images.githubusercontent.com/59916603/100899123-c5fda900-34c1-11eb-8f04-0480805290f5.png)

Step 7: create the following fields in the Job seeker (res.partner contacts)

![image](https://user-images.githubusercontent.com/59916603/100891832-fa6d6700-34b9-11eb-89d4-ff991ab23852.png)

Step 8:Check the picture to locate the fields in the form.

![image](https://user-images.githubusercontent.com/59916603/100895659-196df800-34be-11eb-929b-a4bf0ed1d223.png)

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement_order-interpretor

**Branch name:** 
oDev-12.0-DAFA-Sprint-2-AFC-1120-EPIC-Interpreter

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 10h
Estimated Date: 08/12/2020
Actual Hours: 10.5h

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-verte, I`ve updated the estimate, could someone give approval to it?

**Comment by nils-vertel** [comment]
@n-development Go for it!

**Comment by Yevhen-Pechurin** [comment]
Hello @FredrikArvas @Radhika435 @nils-vertel 
Where i can find field task.outplacement_id?

**Comment by Yevhen-Pechurin** [comment]
@FredrikArvas i don't have permision for push into https://github.com/vertelab/odoo-outplacement. Could you give me permission?

**Comment by FredrikArvas** [comment]
hi @Yevhen-Pechurin I have added you now. Please check if it works.

**Comment by Yevhen-Pechurin** [comment]
No, it don't work, and for https://github.com/vertelab/odoo-base too.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel excuse me, but we have the blocker, check comments above, please.

**Comment by FredrikArvas** [comment]
I have added the team n-development to odoo-base and odoo-outplacement
![image](https://user-images.githubusercontent.com/9428370/101527675-9b629300-398e-11eb-9cde-c631c7aad7af.png)
![image](https://user-images.githubusercontent.com/9428370/101527732-ad443600-398e-11eb-9c33-54c2c8fdfa26.png)
![image](https://user-images.githubusercontent.com/9428370/101527803-c4832380-398e-11eb-9ced-ab18ce15ce4d.png)

**Comment by n-development** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/3

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've updated deadline and Actual hours.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've updated the actual hours how we spend on fixing an error. (0.5h)

**Comment by arturchilangwa-vertel** [comment]
First PR is no merged. 
https://github.com/vertelab/odoo-outplacement/pull/3
