### ISSUE TITLE
AFC-1343 - Raindance API 

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#432]
**Userstory:** 
Please see attached file for information about endpoints.
[IPF-9164 - Raindance - FA faktura.txt](https://github.com/vertelab/odoo-af/files/5617336/IPF-9164.-.Raindance.-.FA.faktura.txt)

- Implementation of integration modules between DAFA and Raindance.
  - Client API module - System parameters for host and base-url
  - Server API module - Dummy responses from each function.
-Creation of a server action for each endpoint (for test)

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Module name:** (added by Nils or Fredrik)
odoo-api/api_raindance_client
odoo-api/api_raindance_server 

**Branch name:** 
Dev-12.0-DAFA-Sprint-2-AFC-1343-Raindance

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**
Server action from client to server
**Test-data:**

**Description to the manifest:** 
APi for connection between DAFA and Raindance

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 6h
Estimated Date: 02/12/2020
Actual Hours: 6h

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve updated the deadline and estimated hours.

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-vertel, I`ve updated the actual hours.

**Comment by arturchilangwa-vertel** [comment]
@nils-vertel @FredrikArvas 
PR https://github.com/vertelab/odoo-api/pull/3 for this issue is merged
