### ISSUE TITLE
AFC-1489 - The web_backend_theme_af does not install correct after merge

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#434]
**Bugreport:** (only for Bug-Issues)
Since we merged the branches for the web-theme it does not install anymore.
Please check on a new database
https://github.com/vertelab/odoo-web/tree/Dev-12.0

**Module name:** (added by Nils or Fredrik)
web_backend_theme_af

**Branch name:** 
12.0-DAFA-Sprint-02-AFC-1489-IMP-web_backend_theme_af

**Test-steps:**
Install the module
the module "Website" should not install

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 Please check this bug. 
I do not have access to the logfiles on the virtual server, so I need your help with isolating the reason for the theme not to install.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Let me check.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've installed theme in new module and it installed successfully without website module. If can you share with me credential of server where facing issue then I can check what is issue.

**Comment by FredrikArvas** [comment]
Ok. Thanks for testing. 
The server is inside the clients network, so we need to check it on our side.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
