### ISSUE TITLE
AFC-1116 Assign Coach (SV: EPIC Tilldela handledare)

### ISSUE THREAD

**Issue by anderswallenquist** [vertelab/odoo-af#436]
**Userstory:** 
As a user (FA), I want open a view for new outplacements 

Assign the customers to the right coach using kanban vy.
Step 1: Firstly they must be assigned automatically to the admin as shown below.(named the column as undefined)
![image](https://user-images.githubusercontent.com/59916603/101760314-fe614080-3ada-11eb-81e8-2e7c00b8ad77.png)

Step 2:now the admin must assign to the right coach by cross checking the service information and interpreter information on the order created.
![image](https://user-images.githubusercontent.com/59916603/101761044-fa81ee00-3adb-11eb-9922-4f47d0b5fbdc.png)

![image](https://user-images.githubusercontent.com/59916603/101760972-e2aa6a00-3adb-11eb-9f2f-de402a29bc81.png)

**Technical**
Add group by for:

- Department
- Employee
- Stage

Add filter by for:

- My Department
- My Outplacement

Add Search for:
- booking ref
- partner_name

Kanban view:
When the view is filtered on department and grouped by employee then there shall be a column for each employee on that department.

When the view is grouped by department then there shall be a column for each department.

The Card should display the following information:
- Name (partner_name)
- Booking ref
- Date interval (start, end)
- Language Need

<img width="1152" alt="Kanban Card2" src="https://user-images.githubusercontent.com/72382478/102211696-449c1280-3ed4-11eb-91ec-a966d0673aac.png">

For the treeview the following columns should be visible:
- partner_name
- booking_ref
- employee
- stage

Create related fields:
| Field | Related field |
| ---- | ---- |
| parter_name | parter_id.name |

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement

**Branch name:** 
Dev-12.0-DAFA-sprint-2-AFC-1116-Assign_coach

**Base branch**
Dev-12.0-Fenix-sprint-2

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 6h
Estimated Date: 18/12/2020
Actual Hours: 4h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by Yevhen-Pechurin** [comment]
@anderswallenquist @nils-vertel 

> Firstly they must be assigned automatically to the admin as shown below

How do we define admin?

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-vertel, we have the blocker, could any of you answer this question, please?

**Comment by nils-vertel** [comment]
@n-development were on it we will get back to you as soon we have an answer

**Comment by anderswallenquist** [comment]
@n-development FIrst step is that outplacement records has employee_id == None (undefined) All records are shown in the undefined column. Employee is not set in earlier stages and are to be set in this kanban-view.

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-vertel, I've added the estimate and the deadline. Could one of you check it, please, and give approval?

**Comment by nils-vertel** [comment]
@n-development Go

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/16

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the actual hours.
