### ISSUE TITLE
AFC-1501 - Create IPF-Config Page 

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#441]
**Userstory:** 
As an admin I want a central place to configure common and specific settings for all IPF-API:s.

**Technical details**
System parameters (ir.config_parameter)
- api_ipf.client_secret (char)
- api_ipf.client_id (char)
- api_ipf.system_id (char)
- api_ipf.environment (selection) ( U1, I1, T1, T2, PROD)

**Screen-shots :**
![IFP-settings](https://user-images.githubusercontent.com/72382478/100882708-c8570780-34af-11eb-85c4-6d01a18d5d4d.png)

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Module name:** (added by Nils or Fredrik)
odoo-api/api_ipf 

**Branch name:** 
Dev-12.0-DAFA-Sprint-2-AFC-1501-Config_Page

**Module type:** 
Application [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
Configuration of API:s that goes towards IPF.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 3h
Estimated Date:  04/12/2020
Actual Hours: 3h

**Comment by n-development** [comment]
Hello @FredrikArvas @nils-vertel, I`ve updated estimates and the deadline.

**Comment by nils-vertel** [comment]
Estimates are OK.
Please develop this.

**Comment by n-development** [comment]
Hello @nils-vertel, I`ve updated the Actual Hours.

**Comment by FredrikArvas** [comment]
Hi @n-development 
Please add a Pullrequest and a link to that here (if/when you have developed it).
thanks

**Comment by Yevhen-Pechurin** [comment]
https://github.com/vertelab/odoo-api/pull/8

**Comment by arturchilangwa-vertel** [comment]
https://github.com/vertelab/odoo-api/pull/8 is merged!
