### ISSUE TITLE
AFC-1487a - Receive Suborder

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#446]
**Userstory:** 
_sale_outplacement:_
    As a system I want to be able to receive a suborder and automatically create `sale.order` and `outplacement.outplacement` objects.

**Technical**
When a suborder is received through the integration https://github.com/vertelab/odoo-af/issues/303 is received, a `sale.order` and an `outplacement.outplacement` shall be created.

`sale_outplacement` (glue module) extends function leverantorsavrop from `sale_suborder_ipf_server`.

On the `sale.order.line` a `product.product` is created that contains the template for the suborder, the `product.product` shall have an unique external_id (`outplacement.product_leverantorsavrop`)

_Depends_:
`outplacement`
`sale`
`res_joint_planning_af`
`sale_suborder_ipf_server`

pseudo code
```
def leverantorsavrop(sale_suborder_ipf_server_record):
    create sale.order/sale.order.line(product_id = sale_outplacement.product_suborder)
    o = create outplacement
    populate o with data, see table below
    search and if missing create res.partner see personnummer in table below
```
Extend class outplacement.outplacement:
| Field Name | Label (String) | Data type |
| ------------- | ------------- | ------------- |
| activity_ids   |  Activites | M2M (mail.activity) |
| task_ids | Tasks | M2M (product.task) |

Extend class project.task
 | Field Name | Label (String) | Data type |
| ------------- | ------------- | ------------- |
| outplacement_id |  Outplacement | M2O (outplacement.outlacement) |
| activity_id | Activity | Selection (res.joint_planing) |
| joint_planing_type | JP_Type | Selection(KVL, Preplaning, Endraport)

| Received Key  | Field name in outplacement | Field name in sales.order | res.partner |
| ------------- | ------------- | ------------- | ------------- |
| genomforande_referens  |  | origin |
| utforande_verksamhet_id  | departement_id (look up hr.department (ka_ref))  | |
| ordernummer  |  | name |
| boknings_id  | booking_ref | |
| personnummer  | partner_id (look up res.parner(use social_sec_nr_age, create if not found))  | | social_sec_nr_age |
| sokande_id  |   | | customer_id|
| tjanstekod  | skill_id (look up hr.skill)  | | |
| deltagandegrad  | participitation_rate (int)| | |
| startdatum_insats  | service_start_date  (date)| | |
| slutdatum_insats  | service_end_date  (date)| | |
| slutdatum_avrop  | order_close_date  | | |
| aktnummer_diariet  | file_reference_number  | | |
| telefonnummer_handlaggargrupp  | management_team_id (look up res.partner (use phone as key, create if not found))  | |  phone |
| epost_handlaggargrupp  | management_team_id (look up res.partner (use phone as key, update mail)) |  |  email |

when created a reference to sale_order is saved in order_id
**Module name:** (added by Nils or Fredrik)
odoo-sale/sale_outplacement (new module)

**Branch name:** 
Dev-12.0-DAFA-Sprint-2-AFC-1487-Receive-Suborder

**Base branch to develop from** 
Dev-12.0-Fenix-Sprint-02

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
Receives a suborder and automatically create sale.order and outplacement.outplacement objects.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 14h
Estimated Date: 11/12/2020
Actual Hours: 15h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve added the estimate. Waiting for approval.

**Comment by nils-vertel** [comment]
@n-development please start development

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the deadline, we're starting work.

**Comment by n-development** [comment]
@nils-vertel
what is sale_outplacement.product_suborder?

**Comment by Yevhen-Pechurin** [comment]
@nils-vertel for creating sale.order and sale.order.line i need price, uom and quantity. Where i can find origin of project.task?

**Comment by FredrikArvas** [comment]
@Yevhen-Pechurin 
Does this file in this module help?
https://github.com/vertelab/odoo-sale/blob/Dev-12.0-Fenix-Sprint-02/af_sale_orders/data/product_template.xml

if not, please add 1 as price, any uom and 1 as quantity

**Comment by nils-vertel** [comment]
@Yevhen-Pechurin
product_id is the string "sale_outplacement.product_suborder" - I have to double check this with the Architect tomorrow but I'm 90% sure.
@anderswallenquist double check this

**Comment by n-development** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/5
https://github.com/vertelab/odoo-sale/pull/13

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the actual hours.

**Comment by arturchilangwa-vertel** [comment]
PRs below is merged: 
https://github.com/vertelab/odoo-outplacement/pull/5 (sale_outplacement)
https://github.com/vertelab/odoo-sale/pull/13 (extending sale_suborder_ipf_(server+client))
