### ISSUE TITLE
AFC-1486a Send GP activities from DAFA to BÄR

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#450]
**Userstory:** 
As user, I wanted to send the data regarding the Job seeker and private vendors GP activities, which must be approved in BÄR. GP activities are saved in outplacement module as task and this information must be send via API. It should be triggered by a Server Action on the task 

Step 1: User needs to click on the *Action* and select the option *Send GP to BÄR*
![image](https://user-images.githubusercontent.com/59916603/100994527-f6435700-3556-11eb-888c-d9a5333daa82.png)

Step 2:
Payload is sent to BÄR via API: `odoo-outplacement/outplacement_joint_planning_ipf_client`

**Technical notes**

Use `post_request` from `ipf.completion_report.client.config` 

psuedo code:
```
outplacement_object.jp_sent_date = Today()
self.env['ipf.completion_report.client.config'].post_request(outplacement_object, res_joint_planning_af_recordset)
```

*Extend:* 

outplacement.outplacement 
| Field Name | Comment |
| ------------- | ------------- | 
| jp_sent_date | Log on change (track_visibility='onchange') |

![image](https://user-images.githubusercontent.com/59916603/100989100-bed1ac00-3550-11eb-9685-02c78256d340.png)

**Module name:** (added by Nils or Fredrik)
`odoo-outplacement/outplacement_joint_planning`

**Branch name:** 
`12.0-AFC-1486-send_joint_planing`

**Base branch to develop from**
`Dev-12.0-Fenix-Sprint-02`

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module adds joint_planing (Gemensam planering) to Outplacement module.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours:  3h
Estimated Date: 18/12/2020
Actual Hours: 4h

**Comment by arturchilangwa-vertel** [comment]
@n-development 
Please give an estimation.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the estimate and the deadline.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I'm almost done, I just see that the screen belongs to project.task, but the description says outplacement_object. Maybe there is a technical error in the description of the problem?

**Comment by nils-vertel** [comment]
Answered in Slack. For the record its a technical error in the description that were missed from the drawning board.
Its correct that the action shall be initiated from the outplacement_object and not on individual tasks.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've updated the actual hours. Unfortunately, we had to use 1 extra hour.
PR link : https://github.com/vertelab/odoo-outplacement/pull/6
