### ISSUE TITLE
AFC-1511 changes in admins access roles

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#453]
**Userstory:** 
As a user, I want the usergroup af_security.3_line_support to inherit base.group_system

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-af/tree/12.0/af_security

**Branch name:** 
Dev-12.0-CRM-AFC-1511_admin_user_rights

**Test-steps:**
Login with a normal user. 
Add the group 3_line_support

**Description to the manifest:** 
This change adds an inherit base.group_system to usergroup af_security.3_line_support 

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
@FredrikArvas [PR Created](https://github.com/vertelab/odoo-af/pull/454)

**Comment by FredrikArvas** [comment]
Thanks @iammiracle 
Fast and correct.
