### ISSUE TITLE
[Bug] AFC-1519 - Error in Contacts formview 

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#455]
**Bugreport:** (only for Bug-Issues)
1 Go to contacts = See kanban view
Open any contact = Generates this error message.
![image](https://user-images.githubusercontent.com/9428370/101237076-472d8980-36d6-11eb-9df8-c9601afe2701.png)

<HR>

2 If I go to a contact through settings -> users -> related partner = I get this error:
![image](https://user-images.githubusercontent.com/9428370/101237129-9b386e00-36d6-11eb-989f-ede3e16d5255.png)

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-web/tree/Dev-12.0/web_dashboard_fenix
(created in this issue https://github.com/vertelab/odoo-af/issues/268)

**Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1519

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
I think it is an error in this database, 
Because i de-installed all modules and the error was still there. 
(And I can not create new databases on our servers.)

Here is a list of all repos on the server. 
(you need all these to test, I think).
odooprojects=(
# Vertel
"odoo-af|Dev-12.0-Fenix-Sprint-02|https://github.com/vertelab/odoo-af.git"
"odoo-account|Dev-12.0-DAFA-Sprint-02|https://github.com/vertelab/odoo-account.git" 
"odoo-api|Dev-12.0-DAFA-Sprint-02|https://github.com/vertelab/odoo-api.git" #Ändrat namn för sprint branchen
"odoo-auth|Dev-12.0|https://github.com/vertelab/odoo-auth.git" 
"odoo-base|Dev-12.0-Fenix-Sprint-02|https://github.com/vertelab/odoo-base.git"
"odoo-contract|Dev-12.0-DAFA-Sprint-02|https://github.com/vertelab/odoo-edi.git" 
"odoo-edi|Dev-12.0|https://github.com/vertelab/odoo-edi.git"
"odoo-hr|Dev-12.0-Fenix_Sprint-02|https://github.com/vertelab/odoo-hr.git"
"odoo-imagemagick||https://github.com/vertelab/odoo-imagemagick.git"
"odoo-l10n_se|12.0|https://github.com/vertelab/odoo-l10n_se.git"
"odoo-outplacement|Dev-12.0-Fenix-Sprint-02|https://github.com/vertelab/odoo-outplacement.git"
"odoo-project|Dev-12.0-Fenix-Sprint-02|https://github.com/vertelab/odoo-project.git"
"odoo-sale|Dev-12.0-Fenix-Sprint-02|https://github.com/vertelab/odoo-sale.git"
"odoo-server-tools|Dev-12.0|https://github.com/vertelab/odoo-server-tools.git"
"odoo-user-mail|12.0|https://github.com/vertelab/odoo-user-mail.git"
"odoo-web|Dev-12.0|https://github.com/vertelab/odoo-web.git"
"odoo-website|Dev-12.0-Fenix-Sprint-02|https://github.com/vertelab/odoo-website.git"

# Use Vertel versions of OCA modules
"odooext-oca-web||https://github.com/vertelab/web.git"
"odooext-oca-server-auth||https://github.com/vertelab/server-auth.git"

# OCA
"odooext-oca-partner-contact||https://github.com/OCA/partner-contact.git"
"odooext-oca-contract|12.0|https://github.com/OCA/partner-contract.git" 
"odooext-oca-hr||https://github.com/OCA/hr.git"
"odooext-oca-social||https://github.com/OCA/social.git"
)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've cloned all repos which mentioned above. Is it possible to share database backup? It would be easier to solve this issue.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Yes, it is possible (if I had the right db-admin-password) on Monday. 
Thanks for trying.

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas
