### ISSUE TITLE
AFC-1521 Fixes to Dashboard

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#458]
Hi Hemangi

- If you have time - could you do an instruction for the dashboard-module
- I need it to be in text and images, rather than a video, since it should be stored in the index-file of the module. 
- I have started to test it and would like the following userstories to be covered:

1 Create a message that is displayed to all users in usergroup internal-users

2 Create a message that is displayed to all users in usergroup admin/user-rights

3 Displaying an image (explain the tags attribute), including alt-img-tag.
How can I change the grey background?
![image](https://user-images.githubusercontent.com/9428370/101243110-47da1600-36fe-11eb-89c0-6a3d6c8fa016.png)

4  How can I align the text to "top"?

5 Please do not allow to create user-groups from this page.
![image](https://user-images.githubusercontent.com/9428370/101243236-131a8e80-36ff-11eb-89b7-ce3504d8536e.png)

6 The "message-boxes" appears in a row. This is not ideal, since 10 messages-boxes will make a very wide-screen.
Please find a way to display them after each other in two or three columns.
![image](https://user-images.githubusercontent.com/9428370/101243664-0cd9e180-3702-11eb-8e13-2c11297f787d.png)

7 Please explain how I should use the "action"-attribute.

**Module name:** (added by Nils or Fredrik)
odoo-web/web_dashboard_fenix

Please change name to odoo-web/web_dashboard_dafa

**Branch name:** 
https://github.com/vertelab/odoo-web/tree/Dev-12.0/

**Description to the manifest:** 
This update Adds an instruction page

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 3 Hours and 10 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have create PR https://github.com/vertelab/odoo-web/pull/12 for index file, to change module name and to prevent Create and Edit on Groups. Also updated code to set text align top.

In Action, you user need to select action on which want to redirect user. Like need to select Tasks action to redirect tasks.
It is list of Window Actions. Setting >> Technical >> Actions >> Window Actions.
In Image, need to use free Font Awesome icon classes. Added link in index file.
For point 6, I need to investigate more.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
