### ISSUE TITLE
AFC-1487b - Glue module between sales and outplacement 

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#461]
**Userstory:** 
As a user (EN: Coach SV:Handläggare) I want to be able to see attributes added in https://github.com/vertelab/odoo-af/issues/446

Add attributes to classes and views already in outplacement and hr_department

**Technical**
| Field name in outplacement | Label | Data Type |
|  ------------- | ------------- | ------------- |
| boknings_ref  | Booking number | Char |
| participitation_rate | Participation Rate| Int |
| service_start_date | Start Date | Date |
| service_end_date | End Date | Date |
| order_close_date  | Close Date | Date |
| file_reference_number  | File Reference Number | Char |

| Field name in hr.department | Label | Data Type |
|  ------------- | ------------- | ------------- |
| ka_ref  | KA-Number  |  Char|

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement (Enhancement) 

**Development Branch name:** 
12.0-AFC-1487b-outplacement-enhancement

**Base branch to develop from:** 
Dev-12.0-Fenix-Sprint-02

**Module type:** 
Application module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
Keep old description

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 2h
Estimated Date: 11/12/2020
Actual Hours: 2h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by n-development** [comment]
@nils-vertel I`ve added the estimate.

**Comment by nils-vertel** [comment]
@n-development Please implement this

**Comment by n-development** [comment]
Hello @nils-vertel, we agreed if an estimate less than 4 hours then a task automatically approves.

**Comment by nils-vertel** [comment]
@n-development yes, just added the comment to document that I have seen it and that I explicitly agree

**Comment by n-development** [comment]
@nils-vertel, I got it.

**Comment by n-development** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/5

**Comment by n-development** [comment]
@nils-vertel @FredrikArvas I've added actual hours and deadline.
