### ISSUE TITLE
AFC-1486b - Send GP activities from DAFA to BÄR (Joint planing module) 

### ISSUE THREAD

**Issue by arturchilangwa-vertel** [vertelab/odoo-af#462]
**Userstory:**
As a system I want to be able to use data from a module. This module includes a recordset that will be used by other modules as initial data. We want to use this module to distribute changes in this recordset. 

This is a part of issue https://github.com/vertelab/odoo-af/issues/450 

**Technical notes:** 
Create a new resource module called `res_joint_planning_af`. Technical name for class: `res.joint_planning`. 
The module should also contain this data below in XML. This data should be usable for every module that is coupled with `res_joint_planning_af`. 

Sequence [int] | Task type [selection] aktivitets_namn) | Activity id [char] (aktivitets_id) | Task name [char] (beskrivning)
-- | -- | -- | --
  | Mandatory | 175 | Gruppskapande aktiviteter
  | Mandatory | 176 | Val och framtidsplanering - deltagarens karriärplan
  | Mandatory | 177 | Individuella karriärsvägledningssamtal
  | Mandatory | 178 | Stöd till att bli antagen till kommunens insatser
  | Mandatory | 186 | Självständigt arbete
  | Mandatory | 180 | Studiebesök arbetsplatser
  | Mandatory | 181 | Möte med förebilder
  | Mandatory | 182 | Kunskap om arbetsmarknad, utbildningsvägar, studiefinansiering, omvärldsbev.
  | Mandatory | 183 | Hälsa och stresshantering i förhållande till arbete och studier
  | Optional | 184 | Rättigheter och skyldigheter i arbetslivet
  | Optional | 185 | Digital kompetens
  | Optional | 179 | Studiebesök utbildningsanordnare
  | Optional | 187 | Studiebesök utbildningsanordnare

*Security:* 
    * `base.group_user` (read only), 
    * `base.group_erp_manager` (modify)

**Module name:** (added by Nils or Fredrik)
`odoo-outplacement/res_joint_planning_af`

**Branch name:**
`12.0-AFC-1486b-data_for_joint_planing`

**Base branch to develop from**
`Dev-12.0-Fenix-Sprint-02`

**Module type:**
Resource module [see issues/178](https://github.com/vertelab/odoo-af/issues/178) for more info. 

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:**
This module can be used as data for any outplacement module.

**Estimate:** ([@Developers](https://github.com/Developers): Add your times here, not in comments please)
Estimated Hours: 3h
Estimated Date: 18/12/2020
Actual Hours: 3h

**Comment by arturchilangwa-vertel** [comment]
@n-development 
Please give an estimation.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the estimate and the deadline.

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I`ve added the actual hours. The ticket has done.
PR :  https://github.com/vertelab/odoo-outplacement/pull/4

**Comment by arturchilangwa-vertel** [comment]
First PR for this issue is merged
https://github.com/vertelab/odoo-outplacement/pull/4
