### ISSUE TITLE
AFC-1486c - Send GP activities from DAFA to BÄR (extend outplacement_joint_planning_ipf_client)

### ISSUE THREAD

**Issue by arturchilangwa-vertel** [vertelab/odoo-af#463]
**Userstory:** 
As a system I want to send a joint planning message to BÄR. 

**Technical notes**

modify `outplacement_joint_planing_ipf_client`:

Update_api so that send takes two params, `outplacement_object`, and `res.joint_planning`'s record set.

When constructing the payload dict according to API the following has to be observed:

* `innehall` field is a list of activities read from `outplacement.task_ids`. 	
  * The list shall be constructed in the order of sequence defined by `res.joint_planning` 's read `activity_id` in `res.joint_planning`. 
  * use `activity_id` with the same id in `outplacement.task.ids` to create dict of: 

	```
	aktivitets_id: activity_id, 
	aktivitets_namn: activity_name,
	beskrivining: description
	```

All fields are not implemented in outplacement yet. So use dummy values for fields that are not implemented yet. 

The table below shows the structure of the JSON that will be sent

| JSON-field                 | JSON-Subfield        | Odoo-field                                       | Comments                                |
| -------------------------- | -------------------- | ------------------------------------------------ | --------------------------------------- |
| `utforande_verksamhets_id` |                      | `outplacement.department_id.department_ref`* |                                         |
| `avrops_id`                |                      | `outplacement.name`*                         |                                         |
| `genomforande_referens`    |                      | `outplacement.order_id.origin`                   |                                         |
| `ordernummer`              |                      | `outplacement.order_id.name`                     |                                         |
| `personnr`                 |                      | `outplacement.partner_id.social_sec_nr_age`      | Depends ?                                 |
| `unikt_id`                 |                      | `outplacement.` **?**                            |                                         |
| `deltagare`                |                      |                                                  |                                   |
|                            | `fornamn`            | `outplacement.partner_id.firstname`             | Depends partner_firstname (OCA)                          |
|                            | `efternamn`          | `outplacement.partner_id.lastname`              | Depends partner_firstname (OCA)                           |
|                            | `deltog_per_distans` | `outplacement.meeting_remote`                    | Depends outplacement_joint_planning_af  |
| `inskickad_datum`          |                      | `outplacement.jp_date`                           |                                         |
| `status`                   |                      |                                                  | Remove from API-Json - Not used anymore |
| `innehall`                 |                      |                                                  |                                         |
|                            | `aktivitets_id`      | `outplacement.task_ids.activity_id`              | Mapped field                            |
|                            | `aktivitets_namn`    | `outplacement.task_ids.activity_name`                     | Mapped field                            |
|                            | `beskrivning`        | `outplacement.task_ids.name`                         |     Mapped field                                    |
|                            |                      |                                                  |                                         |

Astrix (*) marked fields are not implemented.

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement_joint_planning_ipf_client

**Branch name:** 
`12.0-Sprint-2-AFC-1486-send_joint_planning`

**Base branch to develop from:**
`Dev-12.0-Fenix-Sprint-02`

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module adds joint_planing (Gemensam planering) to Outplacement module.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 10h
Estimated Date: 11/12/2020
Actual Hours: 10h

**Comment by arturchilangwa-vertel** [comment]
@n-development 
Please give an estimation.

**Comment by Yevhen-Pechurin** [comment]
Hello @arturchilangwa-vertel 
I can't found outplacement_joint_planing_ipf_client and outplacement_joint_planning_af modules. Could you help me?
I've found a module 'outplacement' with an object 'outplacement' in a branch 'Dev-12.0-Fenix-Sprint-02', but it have a field 'name' and don't have fields 'order_id', 'partner_id', 'jp_date', 'meeting_remote', and 'task_ids'(maybe you means 'activity_ids'). What of an end point i need to use for sending  to BÄR? And what is res.joint_planning?

**Comment by n-development** [comment]
@nils-vertel

**Comment by nils-vertel** [comment]
@Yevhen-Pechurin see https://github.com/vertelab/odoo-af/issues/462
This issue is part of related issues:
https://github.com/vertelab/odoo-af/issues/450
https://github.com/vertelab/odoo-af/issues/462

**Comment by n-development** [comment]
@nils-vertel
[#462](https://github.com/vertelab/odoo-af/issues/462) contains only data and haven't ralation with 'outplacement' object.
I didn't find fields 'order_id', 'partner_id', 'jp_date'(maybe it 'jp_sent_date'), 'meeting_remote', and 'task_ids'.

**Comment by nils-vertel** [comment]
order_id is added by: https://github.com/vertelab/odoo-af/issues/446
partner_id is added by: https://github.com/vertelab/odoo-af/issues/446
jp_date is jp_sent_date:
meeting_remote is added by: https://github.com/vertelab/odoo-af/issues/446 (But not in the spec for it now, I'll have to add it there)
tasks_ids is added by: https://github.com/vertelab/odoo-af/issues/446

**Comment by n-development** [comment]
@nils-vertel 
I can't found outplacement_joint_planing_ipf_client, maybe it is new module?

**Comment by n-development** [comment]
@nils-vertel @FredrikArvas I've updated the estimate and dealine.

**Comment by n-development** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/7

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've updated the actual hours.
