### ISSUE TITLE
AFC-1156-Send Interpreter Booking Request

### ISSUE THREAD

**Issue by af-aden** [vertelab/odoo-af#465]
**Userstory:** 
As a user i want:
1. Book an interpreter as an activity and post a request

**Requirement: Post-Request**
- The GUI for "Interpreter booking" is: (https://github.com/vertelab/odoo-af/issues/427)
- This issue adds the glue between the gui and the API. It "books an interpreter" as an activity, the "booking"-object is saved as an object in mail.activity. 

Send that "booking"-object as a POST-request, the API in module: task_interperator_ipf_client
- The Endpoint to look for is: "/v1/tolkbokningar" (https://github.com/vertelab/odoo-af/issues/339)
- The Method to use: "post_tolkbokningar" (https://github.com/vertelab/odoo-project/pull/3/commits/1d2f1770e1c19505bda02abb77fa17c0c30ee3d2)

- The response: is ”tolkbokningId” and should be saved to the activity object in the field (interpreter_ref)
The issue for the field (interpreter_ref) is developed in this issue: (https://github.com/vertelab/odoo-af/issues/427)

**Object to be sent:**
tolkbokning (object)
- tolkTypId (number) *
- distanstolkTypId (number)
- adress (object)
  - gatuadress (string) *
  - postnr (string) *
  - ort (string) *
- adressat (string)
- fromDatumTid (string, datetime) *
- tomDatumTid (string, datetime) *
- tolksprakId (string) *
- tolkkonId (number) *
- bestallandeKAnr (number) *

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacment_interpreter_booking

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1156_interpreter_booking

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Module type:** 
Glue Module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**
https://github.com/vertelab/odoo-af/issues/339

**Test-steps:**
Install the module 
Login with admin/admin
Click on Outplacement -> Create an Outplacment -> Create a Task (if it is not created) -> Click "Schedule Activity" -> Select "Book Interpreter" in the dropdown.

**Description to the manifest:** 
This module combines the Interpreter-booking API with the Interpreter-booking GUI AFC-1156.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by nils-vertel** [comment]
@af-aden Please refrain from using Images as issue description as it makes it hard to do changes to the description.
Please try to use markdown instead.

**Comment by FredrikArvas** [comment]
Screenshots from systems are ok though. :-)
