### ISSUE TITLE
AFC-1156 - Update the status of Interpreter bookings

### ISSUE THREAD

**Issue by af-aden** [vertelab/odoo-af#469]
**Userstory:**
As a user i want status to be updated regularily

**Requirement (GET-Requests):**
To acheive this task, create a cron-job.
Create data-xml for cron-job:

```
for booking in mail.activity.search(activity_type='outplacement_order_interpreter.order_interpreter', state != 'done'):
     res = selv.env['ipf.interpretator.api].get_tolkbokningar_id(booking.interpreteter_booking_ref,booking.departmernt_id.ka_ref)

```
Use best practice for checking for state not done 

**_A). The Parameters are:_**
Interval: 1 hour

**_B). To do:_**
  - Use _'tekniskStatusTypId'_ field to see if status is 'godkänd' (=approved), 
  - If status == 'godkänd' check if _Interpreter_ exists in hr.employee (use interpreter_ref (tolkid)),
    - If not: create interpreter in hr.employee/res.partner
    - update hr.employee/res.partner with tolkNamn (name) tolkTelefonnummer ( phone) tolkLeverantorVerksamhetsnamn (res.partner.commercial_partner_id.name) tolkLeverantorKontaktperson (res.partner.commercial_partner_id // contact.name //)  
telefonnummer contact.phone
    - update the activity - tolkbokningId (interpreter_ref)  tekniskStatusTypId (interpreter_status) tolkTypId (interpreter_type) 
     distanstolkTypId (location_type) fromDatumTid (time_start) tomDatumTid (time_end)
    - On project.task log json-record

-----------------
enchance hr.employee with interpreter_ref (tolkid)
enchance mail.activity interpreter_id m2o hr.employee

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement_order_interpreter

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1156-Update the status of Interpreter bookings

Target Branch name:
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 8h
Estimated Date: 17/12/2020
Actual Hours: 6h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by n-development** [comment]
@nils-vertel @FredrikArvas I've added the estimate. Could you check it and give approval, please?

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel This ticket has approved by Nils.

**Comment by nils-vertel** [comment]
@n-development Go

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the deadline.

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/12

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the actual hours.
