### ISSUE TITLE
AFC-1555-Extend sale_outplacement with additional fields 

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#471]
**Userstory:** 
As a system I want to be able to add data to the suborder.

**Technical**
|Field name | Label | Data type |
| ------- | -------  | ------- |
| is_suborder | Is Suborder Product | Boolean |
| mail_activity_ids | Activities | many2many (mail.activity) | 

mail_activities in notebook page Suborder.
Notebook page Suborder is visible when is_suborder==True

Enhance suborder_process_data in models/outplacement.py with outplacement.task_ids = recordset project.task built from res.joint_planing in odoo-outplacement.
Create mail activites from sale.order_line where product.product of type is suborder.

**Screen-shots old GUI:** (illustrations of the old system)
<img width="1898" alt="Suborder" src="https://user-images.githubusercontent.com/72382478/102008173-f00b6280-3d2e-11eb-9fc7-f85ec9968c40.png">

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/sale_outplacement 

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-2-AFC-1555-Sale_Outplacement_Fields

**Base Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Module type:** 

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 5h
Estimated Date:  15/12/2020
Actual Hours: 5h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by n-development** [comment]
Hello @nils-vertel @FredrikArvas, I've updated the estimate. 
Could you check and give approval for it, please?

**Comment by nils-vertel** [comment]
Go

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've updated the deadline.

**Comment by n-development** [comment]
@nils-vertel 
"Create mail activites from sale.order_line where product.product of type is suborder." - what the kind of mail activites need to create? 
Maybe for field mail_activity_ids need model mail.activity.type?

**Comment by anderswallenquist** [comment]
```
For activity in product.mail_activity_ids:
       res_id = outplacement.id
      res_model = 'outplacement'
      activity_type_id, date_deadline, summary, user_id, note from activity
```


Change request 1:
Move "Create mail activites from sale.order_line where product.product of type is suborder" to a server activity on outplacement class "Start planned activities". Use user_id from outplacement.employee_id.user_id date_deadline calculated as today + activity.due_days

Change request 2;
Enhance mail.activity with field due_days (integer)

Change request 3:
Add data.xml with a record for a mail.activity tied to the suborder product earlier created with an external id, activity_type_id, due_days, summary,note

@n-development

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/13

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the actual hours.
