### ISSUE TITLE
AFC-1556 - Sales_Suborder Enhance outplacement views with added fields

### ISSUE THREAD

**Issue by nils-vertel** [vertelab/odoo-af#472]
**Userstory:** 
As a user, I want to see detailed information about my suborders.
Please add relevant data fields to views.

**Technical**
- partner_id = fields.Many2one('res.partner')
- management_team_id = fields.Many2one('res.partner')
- task_ids = fields.Many2many('product.task', string='Tasks') - Add as a button in div button box
- order_id = fields.Many2one('sale.order')

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/sale_outplacement 

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-2-AFC-1556-Update-sale_outplacement-views

**Base Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/Dev-12.0-Fenix-Sprint-02

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours:  3h
Estimated Date: 14/12/2020
Actual Hours: 3h

**Comment by nils-vertel** [comment]
@n-development please estimate

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've updated the estimate and deadline.

**Comment by nils-vertel** [comment]
Go

**Comment by n-development** [comment]
PR: https://github.com/vertelab/odoo-outplacement/pull/9

**Comment by n-development** [comment]
@FredrikArvas @nils-vertel I've added the actual hours.
