### ISSUE TITLE
[IMP] AFC-1406c api_odoo_xmlrpc 

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#473]
**Userstory:** 
1 As an admin I want to select which field that should be the "synk-key", since we use different keys for different odoo-classes.

Example: 
For Jobseekers, stored in res.partner, we use "company_registry" and the identifier
For Employees, we use phone-numbers
For Projects, we do not have a number and need to rely on something else

2 When testing, it would be a lot simpler if we could have a "sync"-object-button, similar to the "test connection"-button. 
Is this possible?

3 We need other modules to be able to trigger the sync for an individual object. 
Please help with instructions on how to trigger the sync when a new object is created in a server. 
Example: We have two servers: CRM and DAFA. I create a sales-order in DAFA and need to link it to a jobseeker (with company_registry = 123456790). This Jobseeker exists in CRM, but not in DAFA. The current behavior: The Sales-order-integration creates a res.partner. How can that module trigger the integration for this jobseeker only?

4 We need a chron-job by the end of this week. Please prepare questions you need to start this. 

Module name: 
https://github.com/vertelab/odoo-api/tree/Dev-12.0-DAFA-Sprint-02/api_odoo_xmlrpc

Development Branch name:
Dev-12.0-DAFA-Sprint-02-AFC-1406c-api_odoo-xmlrpc

Target Branch name:
https://github.com/vertelab/odoo-api/tree/Dev-12.0-DAFA-Sprint-02/api_odoo_xmlrpc

Test-steps:
Install the module api_odoo_xmlrpc
Login with admin/admin
Click settings -> Global settings -> Synchronized items

Test-data:

Description to the manifest:
This update adds description and limits the sync of system-unique-records (like base.company and base.admin)

Estimate: (@Developers: Add your times here, not in comments please)
Estimated Hours:
Estimated Date:
Actual Hours: 9 Hours

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

 1 As an admin I want to select which field that should be the "synk-key", since we use different keys for different odoo-classes.
- This means you want to search or sync using field which is selected as synk-key not with ID or name, right?

2 When testing, it would be a lot simpler if we could have a "sync"-object-button, similar to the "test connection"-button.
Is this possible?
- I will check it.

3 We need other modules to be able to trigger the sync for an individual object.
Please help with instructions on how to trigger the sync when a new object is created in a server.
Example: We have two servers: CRM and DAFA. I create a sales-order in DAFA and need to link it to a jobseeker (with company_registry = 123456790). This Jobseeker exists in CRM, but not in DAFA. The current behavior: The Sales-order-integration creates a res.partner. How can that module trigger the integration for this jobseeker only?
- Sale order Integration means which module if it is an exiting module? Please let me know functionality of this module.
How we need to search Job seeker in CRM when creating Sale order in DAFA?

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
(I am sorry for not answering this earlier, I have been too busy to notice your question).

1 As an admin I want to select which field that should be the "synk-key", since we use different keys for different odoo-classes.

HR: This means you want to search or sync using field which is selected as synk-key not with ID or name, right?

 - FA: Yes. We need to be able to confige which field to use as uniqe identifier for each model.
 - Simple Example: For Contacts: MobileNr can be the key, for Sales Orders: database+order_no could be the key, for Projects: Database_name+Database_id etc
 - 
 - More complex Example: We create a new res.partner-object in one DAFA-database with the outplacement.social_sec_nr as a unique value to be synced with our CRM-systems res_partners. 
![image](https://user-images.githubusercontent.com/9428370/103145668-35bc2800-473e-11eb-9023-e0786842b520.png)

 - Then on the same DAFA-database we have an uniqe number stored on outplacement.unique_id (a new object similar to the project). 
![image](https://user-images.githubusercontent.com/9428370/103145741-897b4100-473f-11eb-9e6c-e6d32b180721.png)

 - To the outplacement object, we have connected tasks (project.task-objects) where we do not have any special id and we can use any number. 

And please remember: 
Since we are syncing many many DAFA-databases to one CRM-database, we can not use the normal database_id-field as a uniqe key, since it is a sequence-number generated in each database. 
 
Here is a link to the  "Outplacement"-modules (which are using the new outplacement-class see https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement) 



3 We need other modules to be able to trigger the sync for an individual object.
Please help us with instructions on how to trigger the sync when a new object is created in a server.
Example: We have two servers: CRM and DAFA. I create a sales-order in DAFA and need to link it to a jobseeker (with company_registry = 123456790). This Jobseeker exists in CRM, but not in DAFA. The current behavior: The "Sales-order-integration" creates a res.partner. How can that module trigger the integration for this jobseeker only?

FA: I think this leads into a too compex solution at this point. So let's make this in several steps: 
Step 1. Enable a trigger of a "synk of an individual record".
Step 2. Call this "synk of an individual record" by an other module
Step 3. Create a "Search for a record in a different Odoo-database
Step 4. If a record is found, then trigger a "synk of an individual record" for that "found record".

Below are my answers to your questions (as good as I can). 

HR: "Sale order Integration" means which module if it is an exiting module? 
FA: Yes this module is: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/sale_outplacement

HR: Please let me know functionality of this module. How we need to search Job seeker in CRM when creating Sale order in DAFA?
FA: When a "Suborder" is received with API (https://github.com/vertelab/odoo-sale/tree/Dev-12.0-Fenix-Sprint-02/sale_suborder_ipf_server), it calls the "sale_outplacement"-module to create a new partner or update an existing one. When doing this it uses "social security number" as unique number.
Somewhere in the code, we want to check if that partner exists in the CRM-system and instead of creating one.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Thanks for explanation. 

I have checked for Point 3, We need other modules to be able to trigger the sync for an individual object.
Please help with instructions on how to trigger the sync when a new object is created in a server.
Example: We have two servers: CRM and DAFA. I create a sales-order in DAFA and need to link it to a jobseeker (with company_registry = 123456790). This Jobseeker exists in CRM, but not in DAFA. The current behavior: The Sales-order-integration creates a res.partner. How can that module trigger the integration for this jobseeker only? 

--> I have studied modules which mentioned above. We need to modify one module of those to search jobseeker from CRM. I can do this but for that I need to understand how to configure ipf server and how this modules currently works with configuration.

Can you please arrange meeting or prepare videos/index file to explain how to configure ipf server and how this modules currently works with configuration?

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
I think you are aiming for too much in this case. I do not think it is right if we ask you or Anil to change the code of the other modules. What I was trying to ask for is where in your code the other developers should find the "action" to call for. 

But let's have a meeting in next week. 
I will arrange it on January the 5th when we are all back. 
Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Ok understood. Ok we will discuss in meeting. Let me try to explain how to use code of this module in that module for requirement, there is no direct action.

Other developer can check method check_connection() at line number 52 in https://github.com/vertelab/odoo-api/blob/Dev-12.0-Fenix-Sprint-02/api_odoo_xmlrpc/models/odoo_api_synchro_obj.py

This method first connect two databases. 
line no. 53 is for connection. line no. 55 is to provide model name from which we want to get data.
line no. 56 and 57 is example how to use search_count method. You also can use search method or any other methods to get data from another database.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Questions to speak to at meeting: 
1 Ideas to what this means: 
<ProtocolError for dafa-db823-test.tocp.arbetsformedlingen.se:80/xmlrpc/common: 302 Found>

2 
How can we select which field should be the "key"-field
![image](https://user-images.githubusercontent.com/9428370/103744000-4b163980-4ffd-11eb-80f7-dbbffa053bb0.png)

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 
Revised instruction:
Please make a Chron-job on the Object- record. 
Then we can run that job manually. 
For the "Key"-attribute to be synced, we will go an other way round and use the "Search"-method to search in the source-database first to find the right database-id.

Estimated to be delivered Monday January 11th

**Comment by FredrikArvas** [comment]
I forgot to ask: 
What does <ProtocolError for dafa-db823-test.tocp.arbetsformedlingen.se:80/xmlrpc/common: 302 Found>
indicate?

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas 

I have checked about 302 error code but didn't find anything that direct help. May be there is mistake on user input.
Can you please provide me detail where facing issue and what is configured?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created PR https://github.com/vertelab/odoo-api/pull/11 for following points:
1. Created cron job per object. Here is video for that.
- https://www.loom.com/share/686c48855f084fbca5917175a1642903
2. Added Object selection on Synchronize popup.
- https://www.loom.com/share/860726162193429796a0a36a81fc239b
3. Added description on check_connection().

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here is correct video links.

I have created PR vertelab/odoo-api#11 for following points:

1. Created cron job per object. Here is video for that.
https://www.loom.com/share/3ec8f69e5f93473f828a1d029cfe2ec8

In this video I have configured two servers and two objects(Projects, Tasks). Deactivated cron of task because want to sync it manually.(Shown in next video). Tried to deactive project cron but it was already running. So projects synced automatically by cron job.

2. Added Object selection on Synchronize popup.
https://www.loom.com/share/d61b9cb772284c7e918acfcb0022a165

In this video I have synced tasks manually on popup window.To show that we can select objects to sync.

3. Added description on check_connection().

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created new PR https://github.com/vertelab/odoo-api/pull/12. To change module name base_synchro, To keep author Serpent and added our name as contributor.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Thanks, we will review and merge it tomorrow.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
