### ISSUE TITLE
AFC-1561 - Order interpreter enhancement

### ISSUE THREAD

**Issue by anderswallenquist** [vertelab/odoo-af#475]
**Userstory:** 
As a user, I want to order an interpreter and catch order id 

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Technical**
Missing attributes mail.activity  (outplacement_order_interpreter)
|Attribute|Data Type|String|Note|
|---|---|---|---|
|interpeter_booking_ref|Char|Booking Reference| View in form when type == outplacement_order_interpreter.order_interpreter
|Interpreteter_booking_status|Char|Booking Status|View in form when type == outplacement_order_interpreter.order_interpreter
|department_id|m2o hr.department (default from hr.employee)|Department|View in form when type == outplacement_order_interpreter.order_interpreter

When creating mail.activity of type external id  outplacement_order_interpreter.order_interpreter
call self.env['ipf.interpreter.client'].post_tolkbokningar(mail.activity)

Enchance: odoo-project/task_interperator_ipf_client  (post_tolkbokningar) to map mail.activity to json-record:

|json|mail.activity|note
|---|---|---|
|tolkbokning (object)| ?| Do nothing
|tolkTypId (number) *| ? | Do nothing
|distanstolkTypId (number)|location_type 
|adress (object)|street
|gatuadress (string) *|street2
|postnr (string) *|zip
|ort (string) *|city
|adressat (string)| ? | Do nothing
|fromDatumTid (string, datetime) *|time_start
|tomDatumTid (string, datetime) *|time_end
|tolksprakId (string) *| interpreter_language
|tolkkonId (number) *|interpreter_gender_preference 
|bestallandeKAnr (number) *|departmernt_id.ka_ref

Out parameters:
|json|mail.activity|note
|---|---|---|
|tolkbokningId (number)|mail.activity.booking_ref

**Module names:** 
odoo-outplacement/outplacement_order_interpreter
odoo-project/task_interperator_ipf_client  

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1561- Order interpreter enhancement

**Target Branch name:** 
https://github.com/vertelab/odoo-project/tree/Dev-12.0-Fenix-Sprint-02
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 7h
Estimated Date: 17/12/2020
Actual Hours: 4h

**Comment by nils-vertel** [comment]
@n-development Please estimate

**Comment by n-development** [comment]
@nils-vertel @FredrikArvas I've added the estimate and deadline. Could you check it and give approval, please?

**Comment by nils-vertel** [comment]
@n-development Go

**Comment by Yevhen-Pechurin** [comment]
PR: https://github.com/vertelab/odoo-project/pull/4 - merged
https://github.com/vertelab/odoo-outplacement/pull/14 - merged

**Comment by n-development** [comment]
@nils-vertel @FredrikArvas I've added the actual hours.
