### ISSUE TITLE
AFC-1119 Add partner_skill-module

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#480]
**Userstory:** 
As a user, I want to see the Jobseeker on a separate tab on the contact-form-view

Create module based on: 
https://github.com/OCA/hr/tree/12.0/hr_skill
or
https://apps.odoo.com/apps/modules/8.0/partner_skill/

We want the following extra fields on the tab before or after the skills-tree-view.

| Form Fields | Label | Field type |
| ------------- | ------------- | ------------- |
|other_experiences| Other experiences|Text field, tag-widget|
|streangths| Strenghts|Text field, tag-widget|
|interests|Interests|Text field, tag-widget|

This module adds a view to an existing view (res_partner-form-view) 

**Module name:** (added by Nils or Fredrik)
odoo-base/partner_skill 
Depends: web

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1119-partner_skill

**Target Branch name:** 
https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02

**Module type:** 
Resource module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install the module.
Click "Contacts" -> Any contact -> Skills-tab
Add data

**Description to the manifest:** 
This module adds a tab with skills to the contact-card based on AFC-1119

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1hr 30mins

**Comment by Radhika435** [comment]
@FredrikArvas  This is creating a module for kartläggning Competenser
please review and assign it to the developer.

**Comment by FredrikArvas** [comment]
@iammiracle 
We need a skills-tab in a separate module. Please see if you can refactor the oca/hr_skill in a way that we can send it to OCA later. Possibly by 1 creating a partner_skill-module, and then add an extension with our extra fields to that module.

**Comment by iammiracle** [comment]
Hi @FredrikArvas this does not seems clear, on the contact form, I can only see a **Skill** field with the tag widget, not a tree view, in which i added above fields after it

![image](https://user-images.githubusercontent.com/7355805/102181454-ddb63380-3eaa-11eb-9551-b611bc213287.png)

You also said you want to see the Job seeker on the contact view, do you want me to added a tab for Jobseeker?

Maybe you can explain with images here;

> We want the following extra fields on the tab before or after the skills-tree-view.

Not clear enough, maybe we can have a call

**Comment by FredrikArvas** [comment]
Thanks for the image, I agree - it is not clear.

**Comment by FredrikArvas** [comment]
![image](https://user-images.githubusercontent.com/9428370/102203105-73ac8700-3ec8-11eb-8a73-63d93a2acf54.png)

**Comment by FredrikArvas** [comment]
@iammiracle  Does this make any more sense?
I will try to reach you after my current meeting

**Comment by iammiracle** [comment]
@FredrikArvas [PR Created](https://github.com/vertelab/odoo-base/pull/192)

**Comment by FredrikArvas** [comment]
Hi, 
Please add a screenshot

**Comment by iammiracle** [comment]
![image](https://user-images.githubusercontent.com/7355805/102211292-b2940a00-3ed3-11eb-80f8-378d33092e1c.png)
