### ISSUE TITLE
AFC-780b Add a module with an Odoo-tour to auth_user_rights_wizard

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#483]
**Userstory:** 
As a user, I want to be instructed on how to use a new module with a virtual guided tour.

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-auth/auth_user_rights_wizard_tour

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1780b-auth_user_rights_wizard_tour

**Target Branch name:** 
https://github.com/vertelab/odoo-auth/tree/Dev-12.0

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
**Install the module...
Login with...
Click...**

**Description to the manifest:** 
This module adds a Odoo-tour for the auth_user_rights_wizard-module AFC-780

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
@FredrikArvas do you want me to move the tour functionality from the auth_user_rights_wizard to auth_user_rights_wizard_tour. That is if the PR created as not being merged

**Comment by FredrikArvas** [comment]
@iammiracle - yes please. 
I would like the wizard module to be independent from the tour.

**Comment by iammiracle** [comment]
@FredrikArvas I think it will be cool to support this with a video, here is the [link](https://www.loom.com/share/72ffb3fcd53e4490aeaf992e531f8a98).
[
PR Created](https://github.com/vertelab/odoo-auth/pull/9)
