### ISSUE TITLE
AFC-1346 - Deviation Report Improvments

### ISSUE THREAD

**Issue by arturchilangwa-vertel** [vertelab/odoo-af#486]
### User Story

As a user, I want improvements to the Deviation report functionality and move functions to the outplacement module.

### Technical

This issue is linked to https://github.com/vertelab/odoo-af/issues/363  & https://github.com/vertelab/odoo-af/issues/402 

_Relevant modules for this task:_

* `deviation_report`
* `outplacement_deviationreport_ipf_client` (old  was called `hr_jobseeker_devationreport_ipf` , may not be renamed yet when development starts)
* `outplacement`

_What should be done_

* The `devation_report_wizard`is now tied with `project.task`, the wizard should be tied from `outplacement`'s `project.task` instead. 
* The same goes with the `button` that is tied to `action_send`, it should be placed in `outplacement`'s `project.task` .
* In the wizard **Deviation reason** should called **Deviation Comment**

The values in the wizard model should take values from the `outplacement`'s task instead.

| wizard field name              | outplacement field name |
| ------------------- | ---- |
| `first_name`          | `partner_name` (splitted) |
| `last_name`           | `partner_name` (splitted) |
| `responsible_id`      | `activity_user_id`.email |
| `company_name`        | `company_id`'s name |
| `user_id`             |      |

New fields for the the wizard, that will also be in the payload

| wizard field name | payload value |
| ------------------- | ---- |
| `expected_time_start` | `fronvaro.forvantad_narvaro.starttid` |
|`expected_time_end` | `franvaro.forvantad_narvaro.sluttid` |
| `activity_handling_company_name` | `utforande_verksamhet.namn`|
|`activity_handling_company_id`|`utforande_verksamhet.utforande_verksamhet_id`|
|`reponsible_signature`|`ansvarig_arbetsformedlare.signatur`|

Payload shall be updated this way:
```python
{
    "genomforande_referens": "123456789",
    ...
    "ansvarig_arbetsformedlare": {
        "funktionsbrevlada": self.responsible_id.email
        # New field
    },
    
    "leverantor": {
        ....
        "rapportor": {
            .....
        },
        "utforande_verksamhet": {
            #New fields
        }
        ....
    },
    
    "franvaro": {
        ....
        "forvantad_narvaro": {
           # New fields
        },
    }
}
```

**Branch name:**
`Dev-12.0-AFC-1346-Deviation-Report-Improvments`

**Estimate:** (added by developers only)
Estimated Hours: 10 + 4h
Estimated Date: 01/12/2020 + 08/01/2021
Actual Hours: 6h  + 4h

**Comment by n-development** [comment]
Hello @FredrikArvas, I hope you`re having a nice holiday. Could you give me information about this thicket? Whether we need to develop it?

**Comment by nils-vertel** [comment]
@n-development you have Go for this one

**Comment by Yevhen-Pechurin** [comment]
4 hours
PR: https://github.com/vertelab/odoo-outplacement/pull/38

**Comment by n-development** [comment]
Hello @nils-vertel @FredrikArvas, I`ve added the estimates.

**Comment by arturchilangwa-vertel** [comment]
PR is now merged https://github.com/vertelab/odoo-outplacement/pull/38
