### ISSUE TITLE
[bug] AFC-1445 - add labels to buttons

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#488]
**Bugreport:** (only for Bug-Issues)
This module generates an error (which I currently do not remember), it has to do with "editing" contacts, if I remember correctly.

Original issue: https://github.com/vertelab/odoo-af/issues/399

Please add a new module with the name: web_a11y_create-buttons
(The old module is now set to "installabe: false")

**Module name:** (added by Nils or Fredrik)
Old: https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_a11y_filter_view
Old: https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_a11y_create-buttons

**Development Branch name:** 
Dev-12.0-DAFA]-Sprint-2-AFC-1445b-a11y-buttons

**Target Branch name:** 
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02

**Test-steps:**
Install the module.
I think it was

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 40 mins

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Could you please test this module again, we have disabled it since it created an error (either with contact-editing) or with the navigation (that disappeared some times).
If it works fine on your side, I will re-activate it on our side and test again.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have created PR https://github.com/vertelab/odoo-web/pull/25 for this issue.

Created new module **web_a11y_create-buttons** and solved contact error in this module.
Set Installable False in old module **web_a11y_filter_view.**

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Great!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas
