### ISSUE TITLE
AFC-1607  Investigate tab-order and kanbanview for a11y compliance

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#489]
We have overall issues with Accessibility that I would like to ask you if you would like to investigate.

Currently, it is about how screen-readers (for blind users) handle Odoo. 
If you like, please take four hours and do some testing with: 
1 if you have a windows-computer: install this software https://webaim.org/articles/nvda/
2 see if you can add a function to set the tab-order of the Gui
3 see if you can understand how the kanban-widget works and adjust it to be displayed with the screen reader

And report back what you find.

thanks

**Comment by iammiracle** [comment]
Hi @FredrikArvas is there any specific module you will want me to test or just the general tab order of odoo ad the kanban view

**Comment by FredrikArvas** [comment]
It is the general functionality. Thanks

**Comment by iammiracle** [comment]
@FredrikArvas I tried the software on my PC and I software worked well as I used the tab keyboard button to navigate on the kanban view, on the focused selection, the software reads out every words on the kanban view correctly.

To open the kanban record, I hit the Enter button and used the tab keyboard button to navigate till i got to the tab view.

I tried this on the contact module and HR Module.

**Comment by FredrikArvas** [comment]
This is great news! 
could you test the same on a server with the odoo-web/web_backend_theme_af ?

**Comment by FredrikArvas** [comment]
Hi again, 
please test with this server http://fossa.vertel.se:8069/web/login - mvp23-database
admin / admin 

Could you do small screen recordings with these steps?
1 Login 
2 Go to "Outplacement" (left vertical menu) 
Go to one "outplacement" (it is a type of project)

3 Open it and edit some details. 

Thanks

**Comment by iammiracle** [comment]
Hi @FredrikArvas 

My findings this time is as follows;

* Using tab to navigate on the kanban view works well
* On the form view, when it is on readonly view (that is the edit button is not clicked on), the tab navigates from the edit button to the stages and then to the management team field, then goes back to the edit. The expected behavior is to move to the tabs before repeating the process
* On the form view, when it is in the edit state, the tab navigates through the fields fine, but not to the tab, unless when one tab is focused one. That is the same way the base HR module works.

**Comment by iammiracle** [comment]
@FredrikArvas did you get this?

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Yes thanks. 
Could you please record a simple video?

**Comment by iammiracle** [comment]
Hi @FredrikArvas kindly view here - https://drive.google.com/file/d/1iTwdTit_du9_IJ2zVn9XmFGZQrf1DwL5/view?usp=sharing

The module seems to be showing error at this point, some updates must have been done

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
We do updates on this system every day, so I think it would be solved if you use a new version of the code. 

Here is a list of the requrired branches where the default branch is: Dev-12.0-Fenix-Sprint-02 in all Github-repos:

odooprojects=(

# Vertel
"odoo-account||https://github.com/vertelab/odoo-account.git"
"odoo-af||https://github.com/vertelab/odoo-af.git"
"odoo-api||https://github.com/vertelab/odoo-api.git"
"odoo-auth||https://github.com/vertelab/odoo-auth.git" # New branch Dev-12.0-Fenix-Sprint-02 based on Dev-12.0
"odoo-base||https://github.com/vertelab/odoo-base.git"
"odoo-edi||https://github.com/vertelab/odoo-edi.git" # New branch Dev-12.0-Fenix-Sprint-02 based on Dev-12.0
"odoo-hr||https://github.com/vertelab/odoo-hr.git"
"odoo-l10n_se|12.0|https://github.com/vertelab/odoo-l10n_se.git" # We want 12.0 for the moment
"odoo-mail||https://github.com/vertelab/odoo-mail.git"
"odoo-outplacement||https://github.com/vertelab/odoo-outplacement.git"
"odoo-project||https://github.com/vertelab/odoo-project.git"
"odoo-sale||https://github.com/vertelab/odoo-sale.git"
"odoo-server-tools||https://github.com/vertelab/odoo-server-tools.git" # New branch Dev-12.0-Fenix-Sprint-02 based on Dev-12.0
"odoo-user-mail||https://github.com/vertelab/odoo-user-mail.git"
"odoo-web||https://github.com/vertelab/odoo-web.git" # New branch Dev-12.0-Fenix-Sprint-02 based on Dev-12.0


# Use Vertel versions of OCA modules
"odooext-oca-web|12.0|https://github.com/vertelab/web.git"
"odooext-oca-server-auth||https://github.com/vertelab/server-auth.git" # New branch Dev-12.0-Fenix-Sprint-02 based on Dev-12.0

# OCA
"odooext-oca-contract|12.0|https://github.com/OCA/contract.git"
"odooext-oca-hr|12.0|https://github.com/OCA/hr.git"
"odooext-oca-mis-builder|12.0|https://github.com/OCA/mis-builder.git"
"odooext-oca-partner-contact|12.0|https://github.com/OCA/partner-contact.git"
"odooext-oca-reporting-engine|12.0|https://github.com/OCA/reporting-engine.git"
"odooext-oca-server-ux|12.0|https://github.com/OCA/server-ux.git"
"odooext-oca-social|12.0|https://github.com/OCA/social.git"
"odooext-oca-timesheet|12.0|https://github.com/OCA/timesheet.git"
