### ISSUE TITLE
AFC-1445b - add Module-name to Add-buttons

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#490]
**Userstory:** 
As a user, I want standard-buttons to display the module-name to help users with limited visual field to understand the context o the button

**Screen-shots with changes:** (illustration of proposed changes)
![image](https://user-images.githubusercontent.com/9428370/104085691-ab051e00-5251-11eb-8a8b-cba906397da5.png)
![image](https://user-images.githubusercontent.com/9428370/104085739-06371080-5252-11eb-9b98-300a2c91af34.png)
![image](https://user-images.githubusercontent.com/9428370/104085778-544c1400-5252-11eb-8d4a-2b39bbc489f5.png)
![image](https://user-images.githubusercontent.com/9428370/104085798-6cbc2e80-5252-11eb-93c3-4892c89f19a0.png)

**Screen-shots from development:** (please add screen-shots of the development in the comment below)

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_a11y_create-buttons

**Development Branch name:** 
Dev-12.0-DAFA]-Sprint-2-AFC-1445-more-names-to-buttons

**Target Branch name:** 
https://github.com/vertelab/odoo-web/tree/Dev-12.0-Fenix-Sprint-02/web_a11y_create-buttons

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 hours and 30 mins

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Ok I will check it

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have worked on this issue and updated module name on Save button. 

To update module name on form view buttons like Validate, Preview mentioned in issue need to change button string inside form view where button added. 

To update string on Create button of One2many kanban like **Contact & Address** of **Contacts** view. Need to work on JS. I have found solution which function need to change but when updating function from our module facing js error. 
I have spent total 2 hours. For JS error I need more time may be 2-3 hours or less. So, I need your approval on this.

Please check this and let me know.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi Hemangi, 
thanks for this. We have several issues with the JS, and I would like to "solve them all in one go" - so please wait with them.
Please add a description in the module on how to change the buttion-string.

**Comment by rupareliyahemangi145** [comment]
Ok Sure, @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-web/pull/31 for this issue.

Added module name on Save button and Added description in xml and js for one2many's kanban view's create button.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by arturchilangwa-vertel** [comment]
Merged: https://github.com/vertelab/odoo-web/pull/31
