### ISSUE TITLE
AFC-1548 Please show where these items are found in the source

### ISSUE THREAD

**Issue by fredrikarvasarbetsformedlingen** [vertelab/odoo-af#504]
**Userstory:** 
As a developer, I want to see where I can find these lines of code.
![image](https://user-images.githubusercontent.com/63856803/106469224-5135f380-649f-11eb-95bf-db0e9d347575.png)

Please respond with a URL to each file on github.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by fredrikarvas-vertel** [comment]
@timforsstromAF  and @jonasnyhav - Please add questions here if you have some.

**Comment by rupareliyahemangi145** [comment]
Ok @fredrikarvas-vertel I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel 

Here I have attached file which contain source of items.
[issue_504_description.txt](https://github.com/vertelab/odoo-af/files/5909881/issue_504_description.txt)

Please check it and let me know if anything.
Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Thanks @rupareliyahemangi145
