### ISSUE TITLE
AFC-1745 - Enhancements to Autoresponer-module.

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#511]
1 
**Userstory:** 
As a user, I want to read the description text and understand how the module works. 

In this case, the description-text of the mail_autoresponder-moduler refers to Daily-Notes-arguments. These should be in the mail_autoresponder_crm-module (only).

Please update this modules description:
https://github.com/vertelab/odoo-mail/edit/Dev-12.0/mail_autoresponder/static/description/index.html

2 
Please change the logic that triggers the Autoresponder to: 
![image](https://user-images.githubusercontent.com/61729317/107799663-fe412380-6d5d-11eb-9c72-d53075b61787.png)

**mail_autoresponder**
res_partner:create_date (base)

**mail_autoresponder_crm**
res_partner.customer_since (partner_view_360) 
res_partner.deactualization_date   (partner_view_360) 
res_partner.last_contact_date (partner_daily_notes)
res_partner.next_contact_date (partner_daily_notes)

3 
Change dispaly-widget to only date (no time)
![image](https://user-images.githubusercontent.com/61729317/107799981-7ad40200-6d5e-11eb-9e81-2d0c4a679723.png)

4 
Please filter the Dropdown with emails to only include emails that apply to the Autoresponder-module(s)
![image](https://user-images.githubusercontent.com/61729317/107801924-fdf65780-6d60-11eb-9fe9-774cf89c273e.png)

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_autoresponder
and
odoo-mail/mail_autoresponder_crm

**Development Branch name:** 
Dev-12.0-CRM-AFC-1745b-Enhancement_AutoResponder

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12

**Description to the manifest:** 
AFC-1745b - Changes the selection to refer to a date rather than an event.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
Hi @FredrikArvas 

I don't understand this:

**mail_autoresponder**
res_partner:create_date (base)

**mail_autoresponder_crm**
res_partner.customer_since (partner_view_360)
res_partner.deactualization_date (partner_view_360)
res_partner.last_contact_date (partner_daily_notes)
res_partner.next_contact_date (partner_daily_notes)

If there is no time, the hours reminder wont work, unless I remove the hours from the unit

**Comment by fredrikarvas-vertel** [comment]
Hi
thanks for asking.

I am not sure I answer the right question. But I will try.
1 At this point, I do not see any need to keep track of hourly reminders, it is enough with dates. 
Example: A Contact has a registration date of Jan 1st. We start the autoresponder Jan 10th. Then there will be the first email will be sent Jan 11th (some time after at 00:00).
Then a new registration is created in the same segment on Feb 3rd and that persons first email will be sent Feb 4th at 00:00. 

Optionally. We might have a server_setting on which time the emails should go out each day.
  
Question 2. 
The list of fields are the date-fields that I would like to used.

mail_autoresponder-module
res_partner:create_date (base)
(only one date-field, but it is standard for all systems)

mail_autoresponder_crm-module
res_partner.customer_since (partner_view_360)
res_partner.deactualization_date (partner_view_360)
res_partner.last_contact_date (partner_daily_notes)
res_partner.next_contact_date (partner_daily_notes)

This module will extend mail_autoresponder-module with these four date-fields. 
(I think we will do some more adjustments in the list of fields later on).

Clearer?
Thanks

**Comment by iammiracle** [comment]
Hi @FredrikArvas 

[PR Created](https://github.com/vertelab/odoo-mail/pull/18)

**Comment by fredrikarvas-vertel** [comment]
Hi @iammiracle 
1 I have installed the mail_autoresponder allright.
Please adjust so the calculation is based on the field that is listed in the line.
![image](https://user-images.githubusercontent.com/61729317/107937359-1c886880-6f84-11eb-90f1-a209a33e6bb5.png)



2 I get an error with the mail_autoresponder_crm

File "/opt/af/odoo/odoo_crm/odoo-server-crm/odoo/fields.py", line 571, in _setup_related_full
raise TypeError("Type of related field %s is inconsistent with %s" % (self, field))
TypeError: Type of related field partner.event.next_contact is inconsistent with res.partner.next_contact

**Comment by iammiracle** [comment]
@FredrikArvas [ PR created](https://github.com/vertelab/odoo-mail/pull/19)
