### ISSUE TITLE
AFC-1818 - Enhancement of partner_mail_client 

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#513]
**Userstory:** 
As a user, I want see all messages to and from an employee in a tab
![image](https://user-images.githubusercontent.com/9428370/108737980-66002700-7533-11eb-9c9c-cfe63e800b41.png)

As a user, I want see all messages to and from a res-partner in a tab
![image](https://user-images.githubusercontent.com/9428370/108738839-4f0e0480-7534-11eb-9566-bb7f1b51f3bc.png)

**Please add three security groups:** 
None - hide the tab and menu
"See own messages" (where the logged in user is sender or reciever of the message)
"See all messages"(where the logged in user is sender or reciever of the message)

When I click on a message - display form-view for that message.

See old https://github.com/vertelab/odoo-af/issues/288

**Module name:** (moved and renamed)
1 
Old Module:  https://github.com/vertelab/odoo-af/tree/Dev-12.0/af_mail_client_employee
New Module:  https://github.com/vertelab/odoo-hr/tree/Dev-12.0/hr_employee_mail_client

2
Old module: https://github.com/vertelab/odoo-af/tree/Dev-12.0-Fenix-Sprint-02/af_mail_client_contact
New Module:  https://github.com/vertelab/odoo-base/tree/Dev-12.0/partner_mail_client

**Dev-branch:** 
12.0-AFC-1818_Enhanc_partner_mail_client

**Target-branch**
https://github.com/vertelab/odoo-base/tree/Dev-12.0
https://github.com/vertelab/odoo-hr/tree/Dev-12.0

**Description to the manifest:** 
This version adds tabs with messages.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
@FredrikArvas Here are the PRs - [HR Mail Client](https://github.com/vertelab/odoo-hr/pull/64) and [Partner Mail Client](https://github.com/vertelab/odoo-base/pull/255)

**Comment by fredrikarvas-vertel** [comment]
Merged for continued testing
