### ISSUE TITLE
AFC-2063 - Lift this module mail_browser_view  to v12

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#527]
**Userstory:** 
As a news-letter-user, I would like to see a link to the newsletter with my web-browser.

Upgrade this module: 
https://github.com/OCA/social/tree/11.0/mail_browser_view 
to version 12.

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_browser_view 

**Development Branch name:** 
Dev-12.0-CRM-AFC-2063_mail_browser_view

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0

**Test-steps:**
Install the module...
Send a news-letter. 
See a link to the letter in the webbrowser

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by fredrikarvas-vertel** [comment]
@AnilKesariya or @rupareliyahemangi145 do you have time to lift this module before Monday (or explain if there is a similar function in Odoo v!2 CE.

**Comment by fredrikarvas-vertel** [comment]
Thanks @iammiracle for lifting the module. I can test this on my dev-server tomorrow.

**Comment by fredrikarvas-vertel** [comment]
Give the link to the PR here as usual.

**Comment by iammiracle** [comment]
@FredrikArvas here is the [PR](https://github.com/vertelab/odoo-mail/pull/32)

**Comment by fredrikarvas-vertel** [comment]
Hi Miracle, 
I have tested this module and it works as specified!

I wonder if you can see if we can change the "magic tag" or add a second one like this: 

This line of code triggers the "display link": <a href="#" class="view_in_browser_url">View this mail in browser</a>

I would like to be able to use an other trigger than "#". Maybe #browser_url or similar.
I think this is calculated here: https://github.com/vertelab/odoo-mail/blob/f64855333e93e40e00debc5d2be1b5f0f6aa9ab0/mail_browser_view/models/mail_mail.py#L77
