### ISSUE TITLE
AFC-2078 - Change to workdays and send email based on individuals registration date

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#529]
1 Change Display in the Kanban-view to:
![image](https://user-images.githubusercontent.com/61729317/114416956-7a66b480-9bb1-11eb-87bb-6376d7d25523.png)

2 Change calculation to workdays.
![image](https://user-images.githubusercontent.com/61729317/114418863-3674af00-9bb3-11eb-8b94-9099f6b16b6d.png)

3 Change the send logic to send individual emails each day to all recipients that match the criteria for each letter. If a recipient have recieved a letter, then do not send again. :-)
![image](https://user-images.githubusercontent.com/61729317/114418750-1d6bfe00-9bb3-11eb-932b-d44d8469e1d2.png)

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_autoresponder

**Development Branch name:** 
Dev-12.0-CRM-AFC-2078b-Imp-Autoresponder

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This version changes calculation to workdays and to send letters to recipients of each email each day based on the criteria of the email-line.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
@FredrikArvas 

Starting from the last point, the emails sent to a contact for the criteria is not repeated. That is email is not sent to the partner again. That seems to be sorted already.

Point 2: What I am not clear of is the workdays. Do you intend on removing weekends, that is calculation should be based on week days or work days, meaning holidays will be considered, or you just want me to change the string from days to workdays.

Point 1: What is Sample, I can see Count of Sample,

**Comment by fredrikarvas-vertel** [comment]
Point 2: Weekdays is fine to start with.

Point 1: Count of Sample is fine (in the image above it is 35 records)

**Comment by iammiracle** [comment]
Does it mean number of partner records?

**Comment by fredrikarvas-vertel** [comment]
Yes for that "event"

**Comment by iammiracle** [comment]
@FredrikArvas [PR Created](https://github.com/vertelab/odoo-mail/pull/34)

**Comment by fredrikarvas-vertel** [comment]
Hi @iammiracle 
It worked one step better. But when I run the scheduler. I get this: 


Odoo Server Error
Traceback (most recent call last):
  File "/opt/af/odoo/odoo_crm/odoo-server-crm/odoo/tools/safe_eval.py", line 352, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/af/odoo/odoo_crm/src/odoo-mail/mail_autoresponder/models/partner_event.py", line 84, in automated_event_mail
    self.after_event(event, email_line)
  File "/opt/af/odoo/odoo_crm/src/odoo-mail/mail_autoresponder/models/partner_event.py", line 100, in after_event
    days=email_line.interval_nbr)
TypeError: unsupported operand type(s) for +: 'bool' and 'datetime.timedelta'

**Comment by iammiracle** [comment]
Are you sure the field interval_nbr on the lines has a value?

**Comment by fredrikarvas-vertel** [comment]
I changed the sample to a sample where all records had a date and got a new error.
(please add a "skip" funktion if the date-field is empty)


  File "/opt/af/odoo/odoo_crm/src/odoo-mail/mail_autoresponder/models/partner_event.py", line 126, in before_event
    if week_day_date[-1].strftime("%Y-%m-%d") == today_date:
ValueError: <class 'IndexError'>: "list index out of range" while evaluating
'model.automated_event_mail()'


![image](https://user-images.githubusercontent.com/61729317/114874217-6662c300-9dfc-11eb-9032-c52debf280c7.png)


![image](https://user-images.githubusercontent.com/61729317/114874439-a0cc6000-9dfc-11eb-98f0-b6dceeb8d9e1.png)

**Comment by fredrikarvas-vertel** [comment]
@iammiracle  Please tell me when you have time to look at this error. I can share my screen if that helps.

**Comment by iammiracle** [comment]
Hi @FredrikArvas I found out the issue. I have made the correction.

**Comment by fredrikarvas-vertel** [comment]
@iammiracle 
The workdays looks right now. And I get no error-messages (but I do not see any emails either).

[Autoresponder_troubleshooting.pdf](https://github.com/vertelab/odoo-af/files/6337300/Autoresponder_troubleshooting.pdf)

I have added some images two which I would like some instructions on the trouble shooting.
[Autoresponder_troubleshooting.zip](https://github.com/vertelab/odoo-af/files/6337341/Autoresponder_troubleshooting.zip)
[Autoresponder_troubleshootingppt.zip](https://github.com/vertelab/odoo-af/files/6337348/Autoresponder_troubleshootingppt.zip)

**Comment by fredrikarvas-vertel** [comment]
Please add a view for emails sent for each segment. 
Columns: 
"Autoresponder-name", "Email-template", "res_partner.name", "res_partner.email", Sent Date, "No of Workdays", "Before/After", "Field", "Status", 

Please add import/Export functionality to this table.

**Comment by fredrikarvas-vertel** [comment]
@AnilKesariya  - I think I need to explain this to you. I just need to find time to do it. Maybe tomorrow morning 
07:00 Wednesday, Central European Time (CET)  / 10:30 Wednesday, Indian Standard Time (IST)

**Comment by AnilKesariya** [comment]
@fredrikarvas-vertel : I've  noticed that one PR is not merged to Dev-12.0, from this branch Dev-12.0-CRM-AFC-2078-Imp-Autoresponder, which is submitted 6 days ago. Do I need to clone Dev-12.0 with existing status or you want to merge that changes first?

Regards,
Anil

**Comment by AnilKesariya** [comment]
https://www.loom.com/share/c90042c907a0443f93330750217d3bde
https://www.loom.com/share/09ce162bdda042c2aec1059f1c060e6c


Hi Fredrik, I've tested with fields applied on schedule line, checked on both type of field date and datetime and done some improvements and pushed the code.

**Comment by AnilKesariya** [comment]
HI @FredrikArvas 

I've pushed the code for email rich body that can allow use to chose website snippet on email template code is pushed on same branch

Here is the video link

https://www.loom.com/share/4da0452e6f9f4a7897f1ea7f3a0ee7b8

Regards,
Anil

**Comment by fredrikarvas-vertel** [comment]
Great!
Thank you!

**Comment by fredrikarvas-vertel** [comment]
https://github.com/vertelab/odoo-mail/pull/38

**Comment by AnilKesariya** [comment]
@FredrikArvas : I've pushed one more commit on same branch, that will consider the new contacts to be used to sent on same schedule line which already sent email for some contact would consider new contacts which satisfy the criteria for email receive and before and after would work on flexible check not on exact. we can check it together tomorrow morning call. as we are going to discuss some other changes related to same module.

Regards,
Anil.
