### ISSUE TITLE
AFC-2078b Autoresponder improved logic

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#538]
1 
Change the name of ther "after the event" to "after the event (exakt match)"
Add "after the event" to "after the event (greater then match) "  
and 
Change the name of ther "before the event" to "before the event (exakt match)"
Add "before the event" to "before the event (greater then match) "  

2 Please change logic for the of the "Sent"-icon to calculate with the **contact**, not the email.

3 Add the ability to import "sending-log"-data from the previous system, (recipient, email, state) to allow the system to continue sending to users that have recieved some of the email-templates.

// I have used the "customer_since"-field, but you can work with the standard "res_partner.date" or "res_partner.created_on" field

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_autoresponder
odoo-mail/mail_autoresponder_crm (logic for the "Customer Since"-field). 

**Development Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0-CRM-AFC-2078-Imp-Autoresponder

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0

**Test-steps:**
Create an autoresponder with: "Start date 2021-04-20" and "End date 2021-05-10"
![image](https://user-images.githubusercontent.com/61729317/116355173-c47aa780-a7f9-11eb-86a2-139ecf18b265.png)

**Test-data:**
Create a res.partner with "customer since" 2021-04-01
Create a res.partner with "customer since" 2021-04-05
Create a res.partner with "customer since" 2021-04-10

**Description to the manifest:** 
This version updates the calculation logic to calculate each email-line each time the Chron-job runs.
It also adds "exact match" and "greater then match" on the **before** and **after**. 

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by fredrikarvas-vertel** [comment]
i will test the code you pushed yesterday

**Comment by AnilKesariya** [comment]
@fredrikarvas-vertel : Please test this and let me know, as we have updated this match the exact days with today date.

**Comment by AnilKesariya** [comment]
@FredrikArvas : 

Here is the update for the feedback :

**Comment by fredrikarvas-vertel** [comment]
@AnilKesariya 
I tested this with new test-data today and on an old set. 

  File "/opt/af/odoo/odoo_crm/odoo-server-crm/odoo/tools/safe_eval.py", line 204, in test_expr
    expr = expr.strip()
ValueError: <class 'ValueError'>: ""'bool' object has no attribute 'strip'" while compiling
False" while evaluating
'model.automated_event_mail()'

**Comment by fredrikarvas-vertel** [comment]
1 
I added two emails: 1 and 2 working days
I expected two emails:
![image](https://user-images.githubusercontent.com/61729317/117699974-bf3c3600-b1c5-11eb-9a42-ee2dd0b09959.png)
= got 2 mails sent 6 and 7 "Calendar days" after the "customer since"-date


2 
I added two emails: 1 and 2 working days
I expected two emails:
![image](https://user-images.githubusercontent.com/61729317/117697626-f5c48180-b1c2-11eb-9d61-f2cb0166bce0.png)
= None sent 

3 
I added two emails: 5 and 10 working days
I expected one email:
![image](https://user-images.githubusercontent.com/61729317/117698117-a16dd180-b1c3-11eb-91f4-c40af2c88008.png)
= None sent

**Comment by fredrikarvas-vertel** [comment]
No "Customer Since Date" is set
I added two emails: 1 and 2 working days
I expected two emails:
![image](https://user-images.githubusercontent.com/61729317/117699089-b5660300-b1c4-11eb-97b7-5ec9ae2567ab.png)
Recived none.

**Comment by AnilKesariya** [comment]
@fredrikarvas-vertel : Fixed one issue for this.
Pushed the changes to : Dev-12.0-CRM-AFC-2078-Imp-Autoresponder here is it's [PR](https://github.com/vertelab/odoo-mail/pull/55).

**Comment by AnilKesariya** [comment]
@FredrikArvas : Is there is any feedback on this?
