### ISSUE TITLE
AFC-2100b - Autoresponder  Delivered Opened Clicked

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#539]
**Autoresponder-module**

1 Please make the Autoresponder-header bold
![image](https://user-images.githubusercontent.com/61729317/116044873-b9950b00-a671-11eb-9206-4aa114d4a8bf.png)

Add 
1) Count on mails - Sent, delivered, opened (by mail recipients),
    Count on mails - recipients clicked and opened the link, replied 
    Count on mails - expired [Radhika - please explain more]
![image](https://user-images.githubusercontent.com/61729317/116045328-3d4ef780-a672-11eb-958c-c9ab37c1a72a.png)

![image](https://user-images.githubusercontent.com/61729317/116049209-53f74d80-a676-11eb-927c-8088071467e1.png)

![image](https://user-images.githubusercontent.com/61729317/116049244-5c4f8880-a676-11eb-9ab3-d8611aa8a307.png)

![image](https://user-images.githubusercontent.com/61729317/116049167-4641c800-a676-11eb-95cb-811e0eab0800.png)

Please use this branch: Dev-12.0-CRM-AFC-2078-Imp-Autoresponder

**Comment by AnilKesariya** [comment]
Thanks @rupareliyahemangi145 : I will work on this.

**Comment by AnilKesariya** [comment]
@FredrikArvas : in which branch should make these changes? is that Dev-12.0-CRM-AFC-2078-Imp-Autoresponder? or need to create a new branch?

**Comment by fredrikarvas-vertel** [comment]
Please make a new branch, since I merged all outstanding yesterday

**Comment by AnilKesariya** [comment]
Hi @FredrikArvas : pushed the code in same branch

For menu names update and kanban update, related to opened, clicked statistic info, we need to create a mass mailing campaign for each schedule line in backend that will help us to have the real statics for which the logic is already build.

We will discuss in the morning call.

Regards,
Anil.

**Comment by fredrikarvas-vertel** [comment]
Hi @AnilKesariya 

I have done more testing with the updated code. And to mee, it sends less emails now, but still too many.
This config produece 14 emails. I was excepcting 10.
![image](https://user-images.githubusercontent.com/61729317/116702255-289f9600-a9c9-11eb-96e5-a253dc1a8b11.png)
![image](https://user-images.githubusercontent.com/61729317/116702294-3228fe00-a9c9-11eb-80b0-8ca92e104c34.png)




[test-data_autoresponders.zip](https://github.com/vertelab/odoo-af/files/6405620/test-data_autoresponders.zip)
mail.template_autoresonder import to 
mail.template_testdata_mailtemplates = import to mail-templates
partner.event_testdata_autoresponders = not used now.

Autoresponder-test-schedule = the reference 
Autoresponder_testdata-partners = template to create new test-data-contacts

**Comment by AnilKesariya** [comment]
https://www.loom.com/share/04ad82dbfc74450e8bc8cf0b7ed470a7

@FredrikArvas : I've pushed the changes for statistics code.

**Comment by fredrikarvas-vertel** [comment]
![image](https://user-images.githubusercontent.com/61729317/117845403-cbd19480-b280-11eb-8a31-e64ba47f654b.png)

**Comment by AnilKesariya** [comment]
@FredrikArvas : did you upgraded the module? As there are XML Changes so required an upgrade.

**Comment by AnilKesariya** [comment]
@FredrikArvas : Is there is any feedback on this?
