### ISSUE TITLE
AFC-1822 - Upgrade af_statistics-module to work with system parameter

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#542]
https://github.com/vertelab/odoo-af/tree/Dev-12.0/af_statistics

<script type="text/javascript"> 
var _mtm = _mtm || []; 
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'}); 
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; 
g.type='text/javascript'; g.async=true; g.defer=true; g.src='   Insert URL-value from System Parameter     '; s.parentNode.insertBefore(g,s); 
</script> 

Systerm Parameter Values 
CRM PROD https://af.analytics.elx.cloud/js/container_4v00kfpD.js
Test CRM: https://af-staging.analytics.elx.cloud/js/container_ew8X7e8B.js
DAFA PROD https://af.analytics.elx.cloud/js/container _t72Scj0c.js
Test DAFA: https://af-staging.analytics.elx.cloud/js/container_n7teu7kr.js

**Userstory:** 
As a user, I want/do ...., Because... 

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**NEW Module name:** (added by Nils or Fredrik)
odoo-web/web_statistics_af

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1822-...

**Target Branch name:** 
https://github.com/vertelab/odoo-web/tree/Dev-12

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Description to the manifest:** 
This module adds
// CRM PROD https://af.analytics.elx.cloud/js/container_4v00kfpD.js
// Test CRM: https://af-staging.analytics.elx.cloud/js/container_ew8X7e8B.js
// DAFA PROD https://af.analytics.elx.cloud/js/container _t72Scj0c.js
// Test DAFA: https://af-staging.analytics.elx.cloud/js/container_n7teu7kr.js

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hour and 40 mins(Development and Discussion)
40 mins(Prepared video, created PR, Updated description)
20 mins(Created PR for Fenix branch.)

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel 

Created PR https://github.com/vertelab/odoo-web/pull/55 for this issue and here is video for result.
https://www.loom.com/share/948b4a63e1cb462881242ca52d6ef746

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
This works fine now.

**Comment by rupareliyahemangi145** [comment]
Ok Thanks Fredrik.

**Comment by rupareliyahemangi145** [comment]
Created PR https://github.com/vertelab/odoo-web/pull/57 for Dev-12.0-Fenix-Sprint-02 branch.
