### ISSUE TITLE
AFC-2170 - Create a mockup module to illustrate design elements

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#550]
**Userstory:** 
As a user, I want to see data from different classes on the same screen, because i want to see several parts in the same view.

1 Please make a module with one view with a form (res-partner-fields) in two columns and several tabs below from different classes (odoo-standard modules)
![image](https://user-images.githubusercontent.com/61729317/116974676-c099ca00-acbe-11eb-8903-83e2005ff620.png)

Please provide formview, kanban view and tree-view

Please add name, email.

2 Please mak an other view with the same clasess but displayed in a view where all data is displayed separtately. 
Below is an example with different "places" with the information. Please give different options. 
One option is HTML-report, but it is limited to read-only.

![image](https://user-images.githubusercontent.com/61729317/116974876-0fdffa80-acbf-11eb-985f-b0b96c3501a9.png)

Please provide formview, kanban view and tree-view

**Module name:** (added by Nils or Fredrik)
odoo-base/partner_design_mocukup

**Development Branch name:** 
Dev-12.0-AFC-2170-DesignMockup

**Target Branch name:** 
https://github.com/vertelab/odoo-base/tree/Dev-12.0

**Module type:** 
Glue module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install the module...
Search for a partner in the normal search field. The result should be a formview (if direct match), a kanban if multiple matches. 

**Test-data:**
Odoo standard demo data

**Description to the manifest:** 
This module adds two different ways of displaying Odoo content. A normal formview with tabs and a custom view with different boxes with content-views.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours and 10 mins for first view and search page
1 hour and 50 mins for Second view research and design
1 hour and 30 mins for new menus and border on each section on second view
2 hours and 10 mins for search box in second view and found solution to fill search box without clicking on Edit button.
1 hour and 30 mins for Advance search button development, suggestion and PR etc.
1 Hour for Separate menus and separate forms for simple search and advance search.
30 mins for fixed same view issue when in result get only one record.

**Comment by rupareliyahemangi145** [comment]
Ok @fredrikarvas-vertel  I will check this issue. Should I need to give time estimation for this issue?

**Comment by fredrikarvas-vertel** [comment]
Please make the first image without estimate. And while doing that - please give an idea of the second image

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel Can you please schedule meeting? I want to discuss and want to show something for this issue.

**Comment by fredrikarvas-vertel** [comment]
yes, 
I have 10 min 1450 - 1500 (CET ) in 15 minutes.
Let's connect in the standard Standup-meeting

**Comment by rupareliyahemangi145** [comment]
Ok @fredrikarvas-vertel

**Comment by rupareliyahemangi145** [comment]
Asked to join

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel and @Radhika435 

Here is video to show what I've developed today:
https://www.loom.com/share/34556a0915194f01ba126f1d0cc9ad11

Please check it and let me know if any suggestion.

For **phonecall_ids**, from which module I can find this field? Didn't create PR because want to discuss about layout on tomorrow meeting.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
I thinkn phonecall_ids is a type of activity. Pick any other object. It is only for illustration.

**Comment by fredrikarvas-vertel** [comment]
I have looked at the video and it is fine as a reference-point for the second screen. 

Please explain why we could not use the normal search-box?

**Comment by rupareliyahemangi145** [comment]
> I have looked at the video and it is fine as a reference-point for the second screen.
> 
> Please explain why we could not use the normal search-box?

Odoo normal search box will show result only in kanban view or list view. We can't show form view direct if there is only one record found.

**Comment by rupareliyahemangi145** [comment]
> I thinkn phonecall_ids is a type of activity. Pick any other object. It is only for illustration.

Ok Fredrik

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  and @Radhika435 

Create PR for this issue https://github.com/vertelab/odoo-base/pull/287.Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel ,

I've tried to create second view and here is video to show result which is so far.
https://www.loom.com/share/1e059f6bd94246958702570bdc067cdf

This is just for test to show. Please check it and let me know your suggestion on this.

Thanks

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
This looks VERY GOOD!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by fredrikarvas-vertel** [comment]
Please push this when you can. And we will show it to the team

**Comment by rupareliyahemangi145** [comment]
Ok Sure @fredrikarvas-vertel

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Pushed code in same PR https://github.com/vertelab/odoo-base/pull/287.

For now it will redirect to new form view like I shown in video, instead of first form view like previous video.
Because still don't know when need to show first view and when need to show second view. So for now shown only second view.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 

I have installed the module and it works fine.
For today, I would like to ask if you can add a fram to the different parts of the screen as illustrated.

![image](https://user-images.githubusercontent.com/61729317/117403845-224d7480-af09-11eb-9912-50bcc9a1fce5.png)

We will have a meeting where we will proceed with this concept and create a new gitissue.
/Fredrik

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Pushed code in same PR https://github.com/vertelab/odoo-base/pull/287. Added new menus and border on second view.

Here is video to show result:
https://www.loom.com/share/de19de8a39e14f51b6af005ad439d6f7

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
![Uploading image.png…]()

**Comment by fredrikarvas-vertel** [comment]
![image](https://user-images.githubusercontent.com/61729317/117613663-85d4dd80-b167-11eb-8b2f-c669230c4dc4.png)

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  and @Radhika435 

I've added search box in form view.

Here is video to show that:
https://www.loom.com/share/c71a4e33e4f844b2ae2e1b170db0d5c5
- With this functionality user can see whole breadcrumbs in top.

https://www.loom.com/share/72360bd48936423daed1467a4b3d0b0b
- In this video I've removed breadcrumbs.

https://www.loom.com/share/2d36447896284d9ca541410137d130f2
- In this video I've installed one OCA module that will allow to fill search box without clicking on Edit button.

Please check all videos and let me know which functionality we need  with breadcrumbs or without breadcrumbs?
And we need this OCA module or not to allow edit fields with double click without clicking Edit button? 

We can't directly allow to edit search box with standard functionality and without OCA module.To check possibility of direct allow search box field I have to research on from view JS.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 

We want 
- without breadcrumbs
- with "seachr without edit". 
Please make a PR with that (but do not include the OCA-module in the PR).
Inlude it as a depend in the manifest and make a reference to the Github-link in the description. 
Thanks
/Fredrik

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Pushed code in same PR https://github.com/vertelab/odoo-base/pull/287 for following points.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Hi again
I have tested now and would like the following changes
- change name from mocukup to mockup in all places
- The current behavior (with a wizard that gets to edit-mode when we search in the form-view) is not ideal. 
Is it possible to create a new (third) view where the normal search box is in the normal place? 
I understand that his would go against "search-results to be one form-view", but it would not risk editing fields while searching.
Something in this direction: 
![image](https://user-images.githubusercontent.com/61729317/117684530-5fd62a00-b1b5-11eb-8a14-311925dfcf2d.png)
Or?

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will change name mocukup to mockup.

For second one as need Odoo standard search I think we can use following flow:

We will add new smart button with name 'Search' and remove current search box and search button.

![form](https://user-images.githubusercontent.com/36560391/117762708-4a114500-b247-11eb-967e-eb19ae317951.png)

When user click on new Search smart button we can redirect kanban view or tree view without any contact.
![kanban](https://user-images.githubusercontent.com/36560391/117762826-79c04d00-b247-11eb-8768-c0732d9653ce.png)

![tree](https://user-images.githubusercontent.com/36560391/117762837-80e75b00-b247-11eb-812b-430b574b3525.png)

And there user can search with Odoo standard search box. But result will return in kanban view or tree view instead of form view if only one contact found. But form will be new when user click on contact.

![new_form](https://user-images.githubusercontent.com/36560391/117763085-d7ed3000-b247-11eb-8337-883819a9d569.png)

Let's discuss in meeting.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-base/pull/293 for Advance search and name change from mocukup to mockup.
https://www.loom.com/share/1e570ef090d442438c4038ae4a3caefc
Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 
I have looked now and I would like you to create two versions of the page: 
One without the new search-button
One with the "new Search"-button and no search-form

So in total, we will have a menu that looks like this: 

Mockups
- Formview with Search-button
- Form and Search-view
- Standard View with tabs

OK?

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas In second one we need following Search form but don't need search text box and old search button, right?

![search_form](https://user-images.githubusercontent.com/36560391/117801560-11d32c00-b272-11eb-9e5a-e053628eac77.png)

![remove_search](https://user-images.githubusercontent.com/36560391/117801635-2ca5a080-b272-11eb-90f4-030f9c71a67f.png)

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145  correct

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Pushed code in same PR https://github.com/vertelab/odoo-base/pull/293 for separate menus.
https://www.loom.com/share/e946a040b26141a3b0f29b58b4b140c1

Please check it and let me know if anything.

Thanks

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
I have installed the new version and both menues lead to the same result-page. 
Please change them and their names to: 
Mockups
- Search-form to Formview with Search-button (the current Advanced)
- Search-form to Form and Search-view (the current search)
- Standard View with tabs

**Comment by rupareliyahemangi145** [comment]
Ok Fredrik

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas 

Please test with latest commit of PR https://github.com/vertelab/odoo-base/pull/293.

Here is latest video:
https://www.loom.com/share/408d7eb12b424c7596ee66a6debe99ba

**Comment by fredrikarvas-vertel** [comment]
Thanks. 
It works fine in your video, on my both links leads to the same formview. I will merge it and see how it works.

**Comment by rupareliyahemangi145** [comment]
Ok Fredrik

**Comment by rupareliyahemangi145** [comment]
Please update app list, uninstall **partner_design_mocukup** and then install **partner_design_mockup** rename one.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 
I have tested again. Unistalled both modules. Removed partner_design_mocukup from the server. Restarted. 
Installed partner_design_mockup
I still get the same view from both menues. :-(
I get different URL:s though: 

http://172.16.42.112:8069/web#menu_id=557&action=758 Search-form to Formview with Search-button = partner_design_mockup.action_advance_search_partners

http://172.16.42.112:8069/web#menu_id=556&action=757 Search-form to Form and Search-view  = 
partner_design_mockup.action_search_partners

http://172.16.42.112:8069/web#menu_id=555&action=756 Standard View with tabs  = partner_design_mockup.action_original_partner_view_action

I think they use the same "Action" when clicking on "Search" (or something like that).

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-base/pull/308 to fix this issue.
Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
