### ISSUE TITLE
AFC-2125 Odoo Tray-widget for Interpreter

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#551]
***User Story***
As a user I want to be able to see my interpreter bookings.
I want a widget that is similar to the "Current Activity"-widget with the similar numbering of tasks and links to a kanban view of tasks but with the following requirements:

The widget shall have Links for:
- EN: All Bookings                SV: Alla bokningar               (active==True)
- EN: Awaiting response      SV: Avvaktar svar                 (active==True, _interpreter_booking_status == '1', _interpreter_booking_status_2 in ('1', '3'))
- EN: Ongoing                     SV: Pågående                       (active==True, _interpreter_booking_status == ‘1’, _interpreter_boking_status_2 in (‘3’, ‘4’)
- EN: Not Delivered             SV: Ej Inlevererad                 datetime.datetime.now >= time_start and _interpreter_booking_status == 1 and _interpreter_booking_status_2 == 4
- EN: Failed                          SV: Ingen tillgänglig             (active==True, _interpreter_booking_status == '1', _interpreter_booking_status_2 == '2')
- EN: Done                           SV: Avslutad                        (active==False)

For reference, the field definitions:
        _interpreter_booking_status = 
            {'1': _('Order received'),
             '2': _('Delivered')}
        _interpreter_booking_status_2 = 
            {'1': _('Order received'),
             '2': _('No available interpreter'),
             '3': _('Order received'),
             '4': _('Interpreter Booked'),
             '5': _('Cancelled by Interpreter'),
             '6': _('Cancelled by AF')}

The Links shall lead to a "kanban"-view displaying mail.activities (the current activity widget shows tasks).

Illustration of the different statuses
![image](https://user-images.githubusercontent.com/61729317/117782627-17188280-b242-11eb-9bf4-6ef1651eee01.png)

**Module name:** (added by Nils or Fredrik)
github.com/vertelab/odoo-outplacement/outplacement_order_interpreter

**Development Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/12.0-DAFA-AFC-2125-interpreter-booking-show-made-bookings

**Target Branch name:** 
Dev-12-Fenix-Sprint-02

**Module type:** 
Property/ module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Login with admin
Show displayed interpreter-bookings

**Test-data:**

**Description to the manifest:** 
This version adds a widget for displaying interpreter-bookings.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: **50 mins** - Prepared database with needed module and checked current functionality.
**1 Hour and 20 mins** - Checked how booking activity widget made and removed other model's activities from booking activity icon.
**6 Hours and 20 mins** - Added new filter on widget. Updated code to count activities on the filter of widget.Updated code to list activities when user click on filter widget based on counter of widget(For this first tried with exiting fields but doesn't work then added new field and added server action to update that field in exiting activities). Added Kanban view for activities. Tried to redirect new form view from Kanban view in Javascript.
**2 Hours and 20 mins**: Prepared videos, Pushed code, Added translations, Redirected new form view instead of popup activity form view.
**1 Hour and 20 mins**: Checked requested changed of code and worked on it.
**20 Mins**: Used order_id.origin instead of order_id.name as Order.
**1 Hour**: Improved code, Added cron to update activity status based on current time.
**2 Horus**: Discussion and developement of following:
    Prevented Booking confirmed message in log repetitive.
    Prevent other users activity from Tray widget.
    Counted other activity filter in 'All Booking' filter.
**1 Hour and 30 mins**: Worked on following points:
1. Added new fields of outplacement in Interpreter view -Slide 8 in PPT
2. Added log for Delivered status - Slide 6 in PPT
3. Hide project code field in popup of Delivered button inside activity. - Slide 5 in PPT

**Comment by fredrikarvas-vertel** [comment]
This module is difficult to test outside of our testing-environment. 
Please make a "dry-run"-version and I can test it on our system.

The reason is that the interpreter-bookings are complext to configure without the API to other internal systems.

**Comment by fredrikarvas-vertel** [comment]
Please suggest an alternative solution, if the widget is complex

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145  
Please change the widget from displaying outplacment.tasks to displaying mail.activites (type=interpreter-bookings)

When you install the system - here is a list on repositories and branches that are used, 
I think you do not need all of them for DAFA
https://github.com/vertelab/odoo-af/blob/Dev-12.0-Fenix-Sprint-02/af_install_modules_dafa_mvp1/__manifest__.py

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks I will check.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've worked on this task. Pushed code in https://github.com/vertelab/odoo-outplacement/tree/12.0-DAFA-AFC-2125-interpreter-booking-show-made-bookings branch and here is commit link:
https://github.com/vertelab/odoo-outplacement/commit/a1c30bb77c4da78edac2a4ff41fde164f73aa1bc

Here is videos to show functionality which developed for this task:
1. https://www.loom.com/share/b50609ffabd547e1a6f3536d72ced4bc
2. https://www.loom.com/share/1f23f10846b4483f82d40e1ec45e6c97
3. https://www.loom.com/share/7e8577fcbc2346228f7319e1c7ac229e

In 3rd video I shown translation and Server action. You have to execute this server action after taking latest pull and interpreter module upgradation. Need to this only one time for exiting tasks for new ask it will auto update based on active, end_time, _interpreter_booking_status and _interpreter_booking_status_2.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 
I have tested the Odoo-tray and would like this field in the kanban to link to this field (outplacement.order_id_origin) instead
![image](https://user-images.githubusercontent.com/61729317/118772702-553a2580-b884-11eb-9376-edd06da23a3b.png)

**Comment by fredrikarvas-vertel** [comment]
@nils-vertel with this change above. I am happy for this module to be merged.
/Fredrik

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas  and @nils-vertel 

Added commit https://github.com/vertelab/odoo-outplacement/commit/f6f7edcf29338ee64fd31e9c7ec99c9ca8020d59 to change Order value on tray widget from outplacement.order_id.name to outplacement.order_id_origin.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I found why 'Interpreter Booking confirmed' log prints repetitive.

**interpreter_booking_status**(Booking Status) is compute field means it is not store-able in database. 
So, We can't check direct in write method that if this field updated, add log at that time.

That's why I have checked following field in write method whenever any field updated it check conditions for Booking status == Booked and added log at that time that 'Interpreter Booking confirmed'.

Booking status == Booked is based on following field:
_interpreter_booking_status, _interpreter_booking_status_2, interpreter_company and time_end.

But one scheduled action, '**Check status on Interpreter Order**' executes every 15 mins and its updating data in _interpreter_booking_status and _interpreter_booking_status_2.
So log prints repetitive.

We have to check booking status in another way now. But for that I have one question that. Is there any possibility to change Booking status booked again and again?

For e.g.,

When creates Booking status == Order received, then some reason 'Booked' then 'Delivered' and again Booked.

Like this?

**Comment by fredrikarvas-vertel** [comment]
Let's talk about this, I do not understand completely.
https://meet.jit.si/standup-oij-wtrh-rzt

**Comment by rupareliyahemangi145** [comment]
Yes Sure

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create new PR https://github.com/vertelab/odoo-outplacement/pull/217 for following points:
1. Prevented Booking confirmed message in log repetitive.
2. Prevent other users activity from Tray widget.
3. Counted other activity filter in 'All Booking' filter.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Here is video for PR 217 https://www.loom.com/share/8f7d2e04b9ce4fbc8955abdda88361c9

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created new PR https://github.com/vertelab/odoo-outplacement/pull/218 for following points:
1. Added new fields of outplacement in Interpreter view -Slide 8 in PPT
2. Added log for Delivered status - Slide 6 in PPT
3. Hide project code field in popup of Delivered button inside activity. - Slide 5 in PPT

Here attached PPT with my comments on each slide with Green color. Please check and let me know if anything.

Thanks

Regards,
Hemangi.
[Problem med Tolkbokning i DAFA prod 2021-05-21.pptx](https://github.com/vertelab/odoo-af/files/6526081/Problem.med.Tolkbokning.i.DAFA.prod.2021-05-21.pptx)

**Comment by fredrikarvas-vertel** [comment]
Outstanding issues that are left for now. I will close this issue. 

![image](https://user-images.githubusercontent.com/61729317/119264719-8d26cd00-bbe4-11eb-9951-0de0e3d057b4.png)
![image](https://user-images.githubusercontent.com/61729317/119264729-957f0800-bbe4-11eb-90cf-3d24022a50a6.png)

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Chatter log for Delivered is done in PR https://github.com/vertelab/odoo-outplacement/pull/218

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 ok. I do not see them in my dev-system. But we will do further testing on that one.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
