### ISSUE TITLE
AFC-2173 - Newsletter unsubscribe page

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#553]
**Userstory:** 
As a user, I wanted to see the unsubscribe page should be matched in accordance with the Swedish public employment service's themes and colors when a mail recipient clicks on unsubscribe link.

Step 1: Adjust the odoo standard unsubscribe form 
I have added some comments on the pictures below 
First screen shot shows the unsubscribe form and second screenshot shows the confirmation form.

![image](https://user-images.githubusercontent.com/59916603/117069397-b6161980-ad2c-11eb-996e-9aaa38ebc022.png)
![image](https://user-images.githubusercontent.com/59916603/117070194-b2cf5d80-ad2d-11eb-976f-12fef44866d6.png)

Step 2: Must automatically unsubscribe the res_partners mail id to stop sending newsletters.

Please refer to the gitissue 2067 for matching the colors
 https://github.com/vertelab/odoo-af/issues/530

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
odoo-mail/mass_mailing_unsubscribe_nyhetsbrev_af

**Target Branch name:** 
Dev-12.0-AFC-2173_unsubscribe_nyhetsbrev

Test steps
Send the test mail to the job seekers
Open the mail 
click on the unsubscribe mail.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 6 hours and 20 mins
30 min - Fixed Setting menu issue.

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435 I will wok on this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

Are you using **mass_mailing_custom_unsubscribe** module in server? I didn't find this module in repo but this module is depends on **mail_installmodules_adkd**.

**mass_mailing_custom_unsubscribe** is OCA module. This module also change some thing in unsubscribe page. If you are using this module then need to change this issue changes in this module.

Because I have created new module to do changes of this issue but templates conflicts each other.

**Comment by rupareliyahemangi145** [comment]
![page_base](https://user-images.githubusercontent.com/36560391/117102552-315fe580-ad96-11eb-8763-409b7605157c.png)

**Comment by fredrikarvas-vertel** [comment]
I may be late with my comments. 
It is not important for us to use the mass_mailing_custom_unsubscribe if you have an other module. 
We also want the recipients to be able to unsubscribe on individual mailinglists in the future

**Comment by Radhika435** [comment]
@rupareliyahemangi145 
Please refer to this image 
![image](https://user-images.githubusercontent.com/59916603/117105795-0b7b1680-ad7f-11eb-87a3-a2379af64d7a.png)

**Comment by rupareliyahemangi145** [comment]
I don't have any other module for unsubscribe we can use mass_mailing_custom_unsubscribe module as it is proving options.

I will do changes in mass_mailing_custom_unsubscribe module to change layout as @Radhika435 mentioned. And will add this module in odoo-mail repo.

**Comment by fredrikarvas-vertel** [comment]
if possible: 
Please do an extend to the oca-module instead of a changed copy of the module.

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas It is not possible to do changes of same template in different module. It conflicts.

**Comment by AnilKesariya** [comment]
@Rupareliya Hemangi ***@***.***> : is it not possible
to put the OCA on depends and override  the template and applying changes
according?

**Comment by rupareliyahemangi145** [comment]
@AnilKesariya Yes it may work. Let me try to do this.

**Comment by fredrikarvas-vertel** [comment]
Please use the logotype from this module for the AF-logo
https://github.com/vertelab/odoo-af/tree/Dev-12.0/auth_saml_af
I think it is better to store the logo in this module as well, so we do not need a depend.

**Comment by rupareliyahemangi145** [comment]
Ok @fredrikarvas-vertel

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @fredrikarvas-vertel 

I've create PR https://github.com/vertelab/odoo-mail/pull/50 for this issue.

Here is screenshots for result:
![unsubscribe_page](https://user-images.githubusercontent.com/36560391/117132039-e78bf500-adbf-11eb-94f2-269a32701b9f.png)

![unsubscribed_page](https://user-images.githubusercontent.com/36560391/117132056-ebb81280-adbf-11eb-89e1-b70237b7bb0e.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
The screenshots look great!

**Comment by rupareliyahemangi145** [comment]
Thanks @fredrikarvas-vertel

**Comment by fredrikarvas-vertel** [comment]
Could you please add the AF-graphical format on this screen as well?
![image](https://user-images.githubusercontent.com/61729317/117133664-d386ca00-ada4-11eb-845b-016c9f24f5f7.png)

**Comment by rupareliyahemangi145** [comment]
@fredrikarvas-vertel From where you have taken this screenshot? It is coming from standard module or any custom module?

**Comment by Radhika435** [comment]
@rupareliyahemangi145 Thanks a lot 👍

**Comment by rupareliyahemangi145** [comment]
Its my pleasure @Radhika435

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 it is from https://github.com/OCA/social/tree/12.0/mass_mailing_custom_unsubscribe

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I've installed this module but can't see. May be missing something. Let me check.

**Comment by rupareliyahemangi145** [comment]
Hello @fredrikarvas-vertel You mean following?
![list](https://user-images.githubusercontent.com/36560391/117140344-eca27180-adca-11eb-85db-a85c36fb64da.png)

This contact is in 2 mailing list so those 2 mailing list's name are listed here. So, user can unsubscribe from other mail list also.But I can't see Come back button.

**Comment by rupareliyahemangi145** [comment]
I found it it will come after user click on Blacklist me.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @fredrikarvas-vertel 

Created PR https://github.com/vertelab/odoo-mail/pull/51 for other button's layout.

![black_list](https://user-images.githubusercontent.com/36560391/117150679-fe3d4680-add5-11eb-94c6-46c6ffa2a007.png)

![come_back](https://user-images.githubusercontent.com/36560391/117150699-0301fa80-add6-11eb-859a-7a60c29af042.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145 
We are not able to open the "Settings" in debug mode in the podd if this module is installed.
could you please fix the error soon.

BR,
Radhika Thadivaka

**Comment by rupareliyahemangi145** [comment]
Yes Sure @Radhika435

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

I've fixed Setting menu issue in this PR https://github.com/vertelab/odoo-mail/pull/54.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment]
@rupareliyahemangi145 will do that
Thank you.
