### ISSUE TITLE
AFC-2185_Logging of sent messages

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#554]
**Userstory:** 
As a user I wanted to see the logs information like the mail sent to the recipient,information of the sender who sent the newsletter(mail).
 With standard odoo module  we can see the email sender info in the **options** tab as shown in the figure which can be editable.
![image](https://user-images.githubusercontent.com/59916603/117584278-55138a80-b10c-11eb-9a73-d361095c3c36.png)
Here we want to see all the above information in the chatter as we see on the standard contact card in odoo.
![image](https://user-images.githubusercontent.com/59916603/117584422-29dd6b00-b10d-11eb-8bb2-8138869a0c8d.png)

The chatter log must show the sender information(who logged in and sent the mail)

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_massmailing_sender_logs

**Development Branch name:** 
Dev-12.0-CRM-AFC-2185-Email_marketing_sender_logs

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Test-steps:**
Install the module...
Login as a user
On the chatter, verify whether logged in user who sent the mail matches with the sender info in the log (once the mail is sent)

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 40 mins
20 mins - Created PR for latest changes to remove Odoobot logs.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

You want only logger like this
![chatter](https://user-images.githubusercontent.com/36560391/117428341-9b69bd80-af43-11eb-9e00-e73332f86067.png)

 or want to add some information in log when email sent? If want to add some information then which information because there is already smart button after emails sent which shows list of email sent?

**Comment by Radhika435** [comment]
@rupareliyahemangi145 please check the user story above. we can discuss this in the meeting tomorrow if you any questions.

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435 Thanks

**Comment by fredrikarvas-vertel** [comment]
Please add logging on the "State"-field with which res_user

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  and @Radhika435 

I've create PR https://github.com/vertelab/odoo-mail/pull/52 for this issue.
Here is video for result:
https://www.loom.com/share/f92528ee682149458ac74992d8b6d4f3

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Thanks @rupareliyahemangi145 
Could you skip the changes generated by Odoobot
/Fredrik

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas 

This one or Status one?
Mailing - Test scheduled by Marc Demo From "Marc Demo" <mark.brown23@example.com>

Can you please mark which one from following screenshot?

![log_1](https://user-images.githubusercontent.com/36560391/117655264-76c84c80-b1b4-11eb-8beb-75ce84d17778.png)

![log_2](https://user-images.githubusercontent.com/36560391/117655280-7af46a00-b1b4-11eb-9f4c-6461b948ac67.png)

**Comment by fredrikarvas-vertel** [comment]
These please
Created 
Draft  -> In Queue

![image](https://user-images.githubusercontent.com/61729317/117659441-3b218880-b19c-11eb-8129-34531619d079.png)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Can you please check? is this ok?
1. https://www.loom.com/share/c8be80df6dfe4e039b8e149b8ddebbd3
2. https://www.loom.com/share/5f205c4db85b45ebaa3ac8f3cf2ebe2f

**Comment by fredrikarvas-vertel** [comment]
Yes - this looks good. Please make a PR

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created PR https://github.com/vertelab/odoo-mail/pull/53 for latest changes(Removed Odoobot logs).
Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
