### ISSUE TITLE
AFC-2100d - change name of autoresponder module-templates

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#560]
![image](https://user-images.githubusercontent.com/61729317/117692563-6ec0da80-b1bd-11eb-856d-5ea5e08d39b6.png)
Please change These to autoresponder instead of customer dialogue

Search thorugh all three mail_autoresponder-modules

https://github.com/vertelab/odoo-mail/blob/Dev-12.0-CRM-AFC-2078-Imp-Autoresponder/mail_autoresponder/data/cron.xml
![image](https://user-images.githubusercontent.com/61729317/117693219-14744980-b1be-11eb-8b62-cca209c7edb3.png)
![image](https://user-images.githubusercontent.com/61729317/117694418-6bc6e980-b1bf-11eb-86bc-78ed8620fa82.png)

**Comment by AnilKesariya** [comment]
@FredrikArvas @rupareliyahemangi145 : I found two modules for autoresponder,  1. mail_autoresponder and 2. mail_autoresponder_crm, which is the third one?

**Comment by fredrikarvas-vertel** [comment]
mail_autoresponder = generic functionality that is intended to be standalone of Arbetsformedlingens other modules. It should be useful for any Odoo-user.

mail_autoresponder_crm = adds special functionality linked to vertelab/odoo-base/partner_daily_notes-module. Basically adds the date of the daily notes linked to a res_partner. And in the future, also links other fields to be available in the selection. 

mail_autoresponder_dafa = is intended to add similar links but to vertelab/odoo-outplacement/outplacement-module. Datefields in that module. And in the future, also links other fields to be available in the selection.

**Comment by AnilKesariya** [comment]
mail_autoresponder_dafa = is intended to add similar links but to vertelab/odoo-outplacement/outplacement-module. Datefields in that module. And in the future, also links other fields to be available in the selection. - Thanks. I will check update.

**Comment by AnilKesariya** [comment]
@FredrikArvas : https://github.com/vertelab/odoo-outplacement - Should I clone Dev-12.0 or any specific branch you recommand to have the latest module of mail_autoresponder_dafa

**Comment by fredrikarvas-vertel** [comment]
the Dev-12.0 is the latest (there are several commits each day now).

**Comment by AnilKesariya** [comment]
Ok @FredrikArvas : thanks for the quick response. for the changes on this module which branch should I checkout?

**Comment by AnilKesariya** [comment]
@FredrikArvas : Hemangi told me that you have asked her to remove that module mail_autoresponder_dafa, on issue #545

I have updated the changes on other two modules those are inside odoo-mail respository.

![image1](https://user-images.githubusercontent.com/5101994/117978891-f8081680-b34f-11eb-91d5-a3298b9e6eec.png)
![image2](https://user-images.githubusercontent.com/5101994/117978896-f9d1da00-b34f-11eb-8714-5f80933ac202.png)
![image3](https://user-images.githubusercontent.com/5101994/117978898-fa6a7080-b34f-11eb-87b5-81d6f10c898f.png)

**Comment by AnilKesariya** [comment]
@FredrikArvas : In  which branch should i push these changes?

**Comment by fredrikarvas-vertel** [comment]
I think it is easiest if you use this branch
https://github.com/vertelab/odoo-mail/tree/Dev-12.0-CRM-AFC-2078-Imp-Autoresponder

**Comment by AnilKesariya** [comment]
@FredrikArvas : This is already submitted do let me know if anything on this.
