### ISSUE TITLE
AFC-2321 - Add user-grops on menu autoresponder

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#587]
**Userstory:** 
As a  user of the CRM-system, I do not want to see the autoresponder menu, if I am not part of the "Autoresponder"-users.

![image](https://user-images.githubusercontent.com/61729317/119090464-f43d5980-ba0b-11eb-95ac-45e4117c58de.png)

Only users within these groups should see the menu
![image](https://user-images.githubusercontent.com/61729317/119090739-47afa780-ba0c-11eb-90f4-5bdc3bb467e2.png)

Please allow only this group
![image](https://user-images.githubusercontent.com/61729317/119090999-aaa13e80-ba0c-11eb-8e91-3580feb5d4c6.png)

Please add dependency to the security groups.
![image](https://user-images.githubusercontent.com/61729317/119091552-8c880e00-ba0d-11eb-9972-54550f99eb52.png)

**Module name:** (added by Nils or Fredrik)
odoo-mail/mail_autoreonder_crm

**Development Branch name:** 
Dev-12.0-AFC-2321_added_usergroup_to_menu

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0

**Test-steps:**
Install the module...
the Autoresponder-menu should not be visible.

Add a "Newsletter-Automatic"-group to the current user.
the Autoresponder-menu should be visible.

**Description to the manifest:** 
This version adds a limitation to the menu to only be visible for users in Newsletter-Automatic-group.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by AnilKesariya** [comment]
@fredrikarvas-vertel , @Radhika435 : The Dev-12.0 is behind 3 commits Dev-12.0-CRM-AFC-2078-Imp-Autoresponder,

You will merge the changes to Dev-12.0, after should I checkout new branch : Dev-12.0-AFC-2321_added_usergroup_to_menu?

**Comment by AnilKesariya** [comment]
We need to merge the last changes of Dev-12.0-CRM-AFC-2078-Imp-Autoresponder to Dev-12.0 because menu name has been changed, once you merge then I can proceed for this.

**Comment by fredrikarvas-vertel** [comment]
Ok

**Comment by AnilKesariya** [comment]
@FredrikArvas, @Radhika435 : One more thing, when I try to install the module **mail_autoresponder_crm**, it is installing calendar_af module which is there in **odoo-af**, but calendar_af module uses hr_skill as depends which I didn't find in my existing repositories, will you please help me on this to know that where is **hr_skill** module located?, I've found 1 module with name **hr_skill_ipf** inside odoo-base but not **hr_skill**.

Regards,
Anil

**Comment by fredrikarvas-vertel** [comment]
I think hr_skill is an OCA-module.

**Comment by AnilKesariya** [comment]
Ok. then I will make one OCA folder and load that module from OCA repository, thanks.

**Comment by AnilKesariya** [comment]
Hi @FredrikArvas : I've pushed the changes and here is the [PR.](https://github.com/vertelab/odoo-mail/pull/56)

https://www.loom.com/share/83bbfcf99db9425d91a27b2bb45b0a95
