### ISSUE TITLE
AFC-AFC-2341 - add limitation to Newsletter -menu item

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#594]
**Userstory:** 
1 Please **add user-role** to the mass-mailing_menu to prevent it to be visible for users outside of the Newsletter-Manual-group
https://github.com/vertelab/odoo-af/blob/cb74ed65f4ca4d9c033382c1b1eb5c7d43b8a554/af_security/security/af_security.xml#L91

For an example on how to do this: see this issue for security-groups-module
https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/base_user_groups_dafa

https://github.com/vertelab/odoo-af/issues/587

2 Please **rename** of this module: 
from:
mass_mailing_unsubscribe_nyhetsbrev_af
to:
mass_mailing_unsubscribe_af
**Module name:** (added by Nils or Fredrik)
odoo-mail/

**Development Branch name:** 
Dev-12.0-2341_newsletter-menu

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/Dev12.0

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 50 Mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-mail/pull/59 for this issue.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
