### ISSUE TITLE
AFC-2363 Interpreter booking bugs

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#602]
**Userstory:** 
As a user, I need some corrections in the interpreter booking process.

1) Displays messages "odoo bot Task created"   // Ignore this //
![image](https://user-images.githubusercontent.com/59916603/119407491-97c88b80-bce4-11eb-91f7-01caf78ba8d5.png)

2) Unable to order plats interpreter shows an error with the address.
![image](https://user-images.githubusercontent.com/59916603/119406366-f856c900-bce2-11eb-93bb-8e6875ce3f32.png)

3) Displays a message "interpreter booking ordered by res_partner" after the interpreter is submitted.
4) Shows an incorrect message in booking status (= delivered) and also in chatter with the cancellation of the interpreter from AF.
5) Hide "inleverera" interpreter button (when we press that button) button must be hidden after interpreter is delivered.

![image](https://user-images.githubusercontent.com/59916603/119407547-a9119800-bce4-11eb-84f3-d0caae7698ab.png)
![image](https://user-images.githubusercontent.com/59916603/119407584-b6c71d80-bce4-11eb-9f29-a9f6b0505abc.png)
![image](https://user-images.githubusercontent.com/59916603/119407613-c0508580-bce4-11eb-83b0-cfaa55e56520.png)
![image](https://user-images.githubusercontent.com/59916603/119407639-cc3c4780-bce4-11eb-9112-b776715625bb.png)

**Bugreport:** (only for Bug-Issues)
Login in the DAFA test environment 1701 and order an interpreter in the outplacement tasks.

**Module name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter

**Development Branch name:** 
Dev-12.0-AFC-2363_Interpreter_bug_fix_2021-05-21

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

**Test-steps:**
Install the module, Login into the test system and check for the bugs for the above five points (in the user story)

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:
3 Hours: Worked on 5 points and added server action to remove repetative booking confirmed log.
2 Hours and 50 Mins: Restored database in local, Fixed layout and other errors in restored database.
1 Hour and 10 Mins: Worked on point 6 to show popup on cancel interpreter activity.
40 Mins - discussed with Radhika some points. Related to cancel booking and base activity filter.
1 Hour: Checked how base filters, Cancelled by AF and Cancel activity works.

**Comment by Radhika435** [comment]
FYR @fredrikarvas-vertel

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

Let's discuss this task first on call. Please let me know when we can.

**Comment by FredrikArvas** [comment]
@Radhika435 Thanks for this report. 
Suggestions: 
Please add the screenshot close to the description to make it easier to read. 
Please describe the "current behaviour" and then the "desired behaviour" to make it easier to understand what change we want. 

I know that it is difficult to write requirements and bugreports. I do them with good and bad quality. It is super-clear in my mind all the time, but only a fraction of the times, I get the same picture when I read my text afterwords. It is difficult - but let's enhance the quality together.

**Comment by Radhika435** [comment]
@FredrikArvas Good suggestion Fredrik we will definitely do that.
@rupareliyahemangi145 I have tested it again for the point 1 and it was created from the previous data so please ignore it.

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

Please let me know when you free I have to discuss point number 3.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-outplacement/pull/220

2. This error comes because another server where interpreter booking integrated may be IPF, is sending response 404 with filled address.May I know which API is used for this integration? So I can check why it is sending 404 response.

3. Need to discuss with Radhika.

4. For wrong delivered message need to change translation. I have updated in PO file of module. 
Load translation after module upgradtion from Setting >> Translations >> Load Translations. Change in database if after module upgration and it doesn't work.

5. Done

Also added server action to remove repetitive 'Booking confirmed' Log.
https://www.loom.com/share/ae3aa9ff78464b6395da801552a49924

Please check it and let me know if anything.

Thanks

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  and @Radhika435 

I've pushed code in same PR for point no. 3

Please check it and let me know if anything.

Thanks

Regards,
Hemangi.

**Comment by Radhika435** [comment]
6)When the user clicks on the cancel button on the chatter then the interpreter must be cancelled from DAFA side and before cancellation  a pop up message box should appear which is missing now.
![image](https://user-images.githubusercontent.com/59916603/119619479-53cca800-be04-11eb-8a66-703d4063ddf0.png)

![image](https://user-images.githubusercontent.com/59916603/119619065-e751a900-be03-11eb-86f4-662ab4d5ad8f.png)

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435 I will check this point.

**Comment by Radhika435** [comment]
@rupareliyahemangi145 please prioritize this issue.

**Comment by rupareliyahemangi145** [comment]
Yes Sure @Radhika435

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

I've added new commit in same PR https://github.com/vertelab/odoo-outplacement/pull/220 for point no. 6
https://www.loom.com/share/721d909b8469486b8ff341c8051dc54c

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

Here I have mentioned points which we have discussed now and We three(you, me and @FredrikArvas ) need to discuss together tomorrow.

1. For now, User is not able to see Cancel booking after cancel. Not from Interpreter widget and also not from chatter log.
2. There are three filters(Future Activities, Last etc) in Kanban view of Interpreter booking widget. For now may be these are working based on Odoo standard Due date field. So these should be based on what? based on Booking status? Booking time end?
3. For now there is no Log when booking cancelled by AF. This should appear.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

I checked about above 3 points in modules and here is detail for those:

1. When a user Cancels a booking it set active=false and it goes in Done booking filter. The user can see the booking in "Done"-filter of interpreter widget. As a user i wanted to see the cancelled bookings by AF,submitted etc separately. 
2. Status update must be visible in the tolk widget history based on the "Booking status field".
3. Filters on the tolk widget must be configured based on the different booking statuses.
_= > Book a separate meeting with Nils, Hemangi, Radhika, Maria Lynberg, to define the requriements and test-cases._

2. When "_interpreter_booking_status_2 = 6" it means booking status = 'Cancelled by AF'. 
Please add the messages in the chatter based on the statuses we have in interpreter booking process.
For now we didn't added any log in chatter for this.
=> "If Delveried is done on AF-side", Show nice message and update status in DAFA without sending a new "Delivery".

3. Odoo base filters (Late activities, Today Activities and Future activities) in interpreter widget search view are based on Due date field of activity. But we hide Due date for Interpreter booking.
=> Please hide the time-based filters
=> Please add tree-view

**Comment by fredrikarvas-vertel** [comment]
@nils-vertel  will contine the testing and do some adjustments for this module.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
