### ISSUE TITLE
AFC-2368 Display the cancelled order on the kanban view.

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#606]
**Userstory:** 
As a user, I want to see the job seeker order have cancelled on the kanban view.
Step 1: Refer the field "Interruption" which shows the cancellation have done(if its checked in)
![image](https://user-images.githubusercontent.com/59916603/119638582-17ef0e00-be17-11eb-80a3-45caf396027f.png)
Step 2: Display the message "Cancelled by AF" (Avbruten av AF) in the kanban card.
![image](https://user-images.githubusercontent.com/59916603/119640312-c6e01980-be18-11eb-9b3e-3c9beb490168.png)

@rupareliyahemangi145 could you please check the module name and write it in the Module name below.
@Radhika435 module name is outplacement_final_report_ipf_client as field "Interruption" is added from this module.

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-AFC-2368_dsplay_cancelled_outplacement_kanban

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

**Integrations used in this module:**

**Test-steps:**
Install the module and select one of the job seeker card 
If interrupted field is checked in then the "cancelled" test must be visible on the kanban card

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/221 for this issue.
https://www.loom.com/share/cf8b7f12abfd42f5bab5420c1f490932

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
