### ISSUE TITLE
AFC-2186 - ADKD Change attributes in "partner_selection"-view

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#608]
**Userstory:** 
As a "newsletter"-sender, I want to see the following attributes in the "selection"-result-tree-view

Existing view
![image](https://user-images.githubusercontent.com/61729317/119850775-21a76d00-bf0e-11eb-9d20-1f246fbd9946.png)
https://github.com/vertelab/odoo-mail/blob/Dev-12.0/mail_mass_mailing_gdrp_limitations/views/res_partner_view.xml

**Add the following fields to the tree-view:**
Age = res_partner.age (from https://github.com/vertelab/odoo-base/tree/Dev-12.0/partner_ssn
Gender = res_partner.gender (1=male, 2=female, 0=unknown Add calculation in https://github.com/vertelab/odoo-base/tree/Dev-12.0/partner_ssn
can be calculated from the next last digit in the SSN. Even-numbers (0,2,4,6,8) = Female, Odd number (1,3,5,7,9) = Male

Desired Job partner_desired_jobs.ssyk.id (try using this widget widget="many2many_tags")

Zipcode res_partner.zip
Municipality (geographical) res_partner.(res_country_state)_id (four digits)
https://github.com/vertelab/odoo-base/blob/f85f8bb7cdad20ed055c2d790d3cab32bca411f5/partner_view_360/views/res_partner_view.xml#L139

State (geographical) res_partner.(res_country_state)_id.name (first two digits)
https://github.com/vertelab/odoo-l10n_se/blob/Dev-12.0/l10n_se/data/res.country.state.csv

Country res_partner.res_country_id.name ?

Segment (res_partner.jobseekersement
Jobseeker (existing field now)
Hide Employer
Hide Employer Segment
Active (existing field now)
Remove "Job position"

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-mail/blob/Dev-12.0/ail_mass_mailing_gdrp_limitations

**Development Branch name:** 
Dev-12.0_AFC-2186_

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/blob/Dev-12.0/mail_mass_mailing_gdrp_limitations-extension

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Description to the manifest:** 
This version adds more fields to the tree view.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 50 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PRs for this issue:
https://github.com/vertelab/odoo-mail/pull/60 
and https://github.com/vertelab/odoo-base/pull/316

Here is result:
![jobseeker](https://user-images.githubusercontent.com/36560391/119985229-0442d380-bfe0-11eb-9bdf-11f7bb208abe.png)

![from_domain](https://user-images.githubusercontent.com/36560391/119985232-060c9700-bfe0-11eb-847b-221411aec601.png)

![contact_list](https://user-images.githubusercontent.com/36560391/119985239-073dc400-bfe0-11eb-80e2-f960da4f196c.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
