### ISSUE TITLE
AFC-2353 - SM- Proposal for GUI for Secure Messages

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#612]
**Userstory:** 
Userstoy: As a Caseworker I want to send and see messages to the current jobseeker.

1 Extend the module https://github.com/vertelab/odoo-mail/blob/Dev-12.0/mail_partner_messages
with "Source" (indicating if it is a mass_mailing, mail_autoresponder, or a normal "mail_message".
![image](https://user-images.githubusercontent.com/61729317/120031881-b33fd900-bff9-11eb-99c2-0bfd59a18a75.png)

2 If possible
with "attachments" and "status"

3 propose a solution to allow Odoo to expose an IMAP-mailbox for each res_partner. 
![image](https://user-images.githubusercontent.com/61729317/120033180-8b517500-bffb-11eb-8229-85d9a2c2c8d4.png)

Anders (CEO of Vertel) sais "we do this frequently byt integrating a mailserver with Odoo". I do not remember his solution, but if you have a suggestion - please describe it here.
Where the userstory is: 
As a user with an IMAP-client, I want to connect to the "Odoo server" and exchange messages for my "res_partner".
( @anderswallenquist - if you have time - please explain your solution here )

4 Either expand the "Standard Message"-window and display the followers (similarly to this module https://apps.odoo.com/apps/modules/10.0/mail_see_recipients/)
or
Add a new Window for a message that will be stored as a "message for this partner". It should not be sent by email, since it will be collected by the IMAP-client only. 

**Development Branch name:** 
Dev-12.0-AFC-2353-extend_mail_partner_messages

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0

**Description to the manifest:** 
This version adds more functionality to prepare for Secure Messages

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date:

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Have you got clear requirements for this issue?

**Comment by fredrikarvas-vertel** [comment]
No, I don't yet. We need to talk about it to see where we can go.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
