### ISSUE TITLE
AFC-2405 Enhancement and bugfixes in interpreter

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#613]
1 Add Translation: 
Current EN: 
Interpreter request has been sent at the time YYYY-MM-DD HH:MM:SS & YYYY-MM-DD HH:MM:SS, with the language [Language name] and waiting for the confirmation from the Interpreter portal.

(If the language is set in the Javascript - it is ok to only have the message in Swedish).
New EN: 
Interpreter request has been sent for YYYY-MM-DD at HH:MM to HH:MM in [Language name]. 

New SV:
Din tolk är beställd till YYYY-MM-DD klockan HH:MM till HH:MM för [Language name]. 

![image](https://user-images.githubusercontent.com/61729317/120062912-bf14b500-c064-11eb-8a0a-db7390856360.png)

2 
The interpreter time needs to be in Swedish time, that is System-time + 2 hours.
![image](https://user-images.githubusercontent.com/61729317/120063169-2bdc7f00-c066-11eb-9f3c-f97c135ac4d0.png)

Nils sais he has implemented a formula for this in the DAFA code (but he did not remember where when I spoke to him).

3 
Translation of EN: "Created By" into SV: "Skapad av"
![image](https://user-images.githubusercontent.com/61729317/120063099-ca1c1500-c065-11eb-8e69-a03e69d7ff80.png)

4 
Add smartbutton on the Outplacment Form that links to "Interpreter bookings" for that "Outplacement".
![image](https://user-images.githubusercontent.com/61729317/120063141-0b142980-c066-11eb-88a4-6c8c664fe23f.png)

5 
Please hide the left "Marked as cancelled"-button for now. It causes more trouble than value until we have a API-cancellation function.
![image](https://user-images.githubusercontent.com/61729317/120063216-63e3c200-c066-11eb-85c7-2dca8a5256ea.png)

6
Hide the "Deliver interpreter" button if the status is "No available Interpreter"
![image](https://user-images.githubusercontent.com/61729317/120063272-98577e00-c066-11eb-9fd1-b0ef29a3baba.png)

7 Add "search for" in the interpreter-tray-kanban-view
![image](https://user-images.githubusercontent.com/61729317/120064092-e8d0da80-c06a-11eb-9c2d-ee2d82414eaa.png)

8 Add Tree-view in the interpreter-tray-kanban-view

9 Please add these fields to the kanbanview that is displayed from the Transation Odoo-tray
![image](https://user-images.githubusercontent.com/61729317/120064454-84167f80-c06c-11eb-958a-cd595def762a.png)

10 The calculation of "awaiting" is not right. 
In this case, I added a new booking, that and I had not recieved any response from the interpreter-portal.
![image](https://user-images.githubusercontent.com/61729317/120064376-1f5b2500-c06c-11eb-8c6a-94cf3c0c498c.png)
Please check the code comment 
https://github.com/vertelab/odoo-outplacement/commit/7428528e46bb715d3f206d3be4e68bda021b02ad#diff-82d91000c781591c93b599fd7585cd0e985ff8b3266343f5f41ee3424201451c

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter

**Development Branch name:** 
Dev-12.0-DAFA-AFC-2405_Interpreter_enhancements

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

**Description to the manifest:** 
This version adds a smartbutton for the Outplacements Interpreterbookings and some translation fixes.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 4 Hours and 20 min For Point 1,2,3,4,5,6,8,9
1 Hour and 30 mins: For Point 7
30 mins- Added translation and discussed all points with Radhika.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas  I will start work on this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Interpreter request has been sent at the time YYYY-MM-DD HH:MM:SS & YYYY-MM-DD HH:MM:SS, with the language [Language name] and waiting for the confirmation from the Interpreter portal.

What should be translation for **and waiting for the confirmation from the Interpreter portal.**?Or should I need to remove this line from message?

**Comment by fredrikarvas-vertel** [comment]
Yes, please remove that line.

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @fredrikarvas-vertel

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 
In point 7, Add "search for" in the interpreter-tray-kanban-view

You need same search view in Interpreters menu's list view which is on tray widget?
Here:
![interpreter](https://user-images.githubusercontent.com/36560391/120068042-46c9e600-c09c-11eb-822b-49feefbb6431.png)
 
Or in tray widget search view, need to add new fields on search view which are in kanban view?

@rupareliyahemangi145 
Please add the same "search"-fields as in the "Interpreter Accountant"-view 

InterpreterAccountant view:
![image](https://user-images.githubusercontent.com/61729317/120096236-893a0400-c12a-11eb-8040-00dd280f3778.png)

The current Outplacment->OdooTray-view
![image](https://user-images.githubusercontent.com/61729317/120096277-d6b67100-c12a-11eb-9847-08a1fc780d18.png)
Please also add a separator line.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas I don't understand comment of point 10.
@rupareliyahemangi145 Ok. Leave this for now. The calculation get right as soon as the Chron-job has connected to the InterpreterPortal-service.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-project/pull/29 for Point no. 1 and 2

This PR https://github.com/vertelab/odoo-outplacement/pull/227 is for 3,4,5,6,8,9
I've added README.rst file for outplacement_order_interpreter module.

Here is video for 1,2,3,4,5,6,8,9:
https://www.loom.com/share/c677e73de9a546a9a6bd37c3740c9e0f

Remaining points are 7 and 10. Added comments for those. 

Please check and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 Item 7 is the only thing outstanding now.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/228 for point 7.

Here is video for that:https://www.loom.com/share/e0fd543efff0496ea25fcb7a5d860daa

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Thanks @rupareliyahemangi145 
The search-view is better now, but I still want to be able to search for partner name etc
![image](https://user-images.githubusercontent.com/61729317/120143742-f9a35c80-c1e0-11eb-97c7-f15e6cc20761.png)

**Comment by rupareliyahemangi145** [comment]
Ok Sure @FredrikArvas I will add search for Partner name, Name, Source document, Booking Ref, Performing Operation.

To Add separator I have to check JS part we can't add there via XML.

**Comment by fredrikarvas-vertel** [comment]
Ok, skip the separators then. :-)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas :)

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  Added one more commit in same PR https://github.com/vertelab/odoo-outplacement/pull/228 to add new fields on search.

https://www.loom.com/share/9a44f1bf63a343fc9a20bc3b4adc8d11

Also added Outplacement and Task clickable in Interpreter form view.

![interpreter_form_view](https://user-images.githubusercontent.com/36560391/120147611-89a6cd80-c204-11eb-8a66-f11e3f6f18f8.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Added group on **Outplacement** and **Task** fields of Interpreter view in same PR https://github.com/vertelab/odoo-outplacement/pull/228

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment]
Hi @rupareliyahemangi145 
Point 3: I have tested it and seems to be not working with the translations.
Translation of EN: "Created By" into SV: "Skapad av" , "Deadline"  to "Tidsfrist" and "Activity type" to "Aktivitet typ".
![image](https://user-images.githubusercontent.com/59916603/120449175-7f650a80-c38f-11eb-86eb-2d9469703841.png)
Could you please check on this.

**Comment by rupareliyahemangi145** [comment]
Yes Sure @Radhika435 Let me check.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-outplacement/pull/234 for translations in search view.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
