### ISSUE TITLE
AFC-2407 Printerfriendly version of the Final Report

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#615]
**Userstory:** 
As a user, I want create a printerfriendly version of the Final Report, because I want to share it with the Participant.

The report should be "printable" and "possible to email". 

Suggestion: Create a report that can printed and can be emailed participant. 

Please use the following fields: 
![image](https://user-images.githubusercontent.com/61729317/120096567-83ddb900-c12c-11eb-8c7e-78979ce7cc91.png)
![image](https://user-images.githubusercontent.com/61729317/120096574-8c35f400-c12c-11eb-8ce5-5e93524b64ce.png)
![image](https://user-images.githubusercontent.com/61729317/120097109-00719700-c12f-11eb-9a0f-62c8dd5f1605.png)
![image](https://user-images.githubusercontent.com/61729317/120097111-09626880-c12f-11eb-8cfd-35324498ad61.png)

![image](https://user-images.githubusercontent.com/61729317/120096452-eb473900-c12b-11eb-8aad-ace43f017d62.png)
![image](https://user-images.githubusercontent.com/61729317/120096470-0619ad80-c12c-11eb-893b-a8fffcc8896a.png)
![image](https://user-images.githubusercontent.com/61729317/120096511-35c8b580-c12c-11eb-941c-e71f746cdb28.png)
![image](https://user-images.githubusercontent.com/61729317/120096526-4aa54900-c12c-11eb-9f80-97cbb041b56b.png)
![image](https://user-images.githubusercontent.com/61729317/120096534-52fd8400-c12c-11eb-85dd-a9ac2e4bccc8.png)

Please add the print-link here:
![image](https://user-images.githubusercontent.com/61729317/120097223-9e656180-c12f-11eb-9850-f23024cce228.png)

**Module name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_final_report

**Development Branch name:** 
Dev-12.0-DAFA-AFC-2407_Printerfriendly_Finalreport

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Description to the manifest:** 
This version adds a printerfriendly report to the Outplacement

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: **2 Hours and 20 mins** - Created Final report with some fields.
**3 Hours and 50 mins** - Improved Final report layout, Added new fields, Added button to send report via email.
**1 Hour and 30 mins** - Added details of Goals in Final report.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will start work on this.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here I attached today's work of Report. Remaining to add some fields and some improvements
[AKTTEST-4831 - Final Report.pdf](https://github.com/vertelab/odoo-af/files/6570441/AKTTEST-4831.-.Final.Report.pdf)
 in layout.

**Comment by fredrikarvas-vertel** [comment]
yes, this is good!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here I attached latest version of PDF report. Please check it and let me know changes for this report.
[AKTTEST-9311 - Final Report.pdf](https://github.com/vertelab/odoo-af/files/6573697/AKTTEST-9311.-.Final.Report.pdf)

Now I will add button to send this report via Email. Like this:
![sale_button](https://user-images.githubusercontent.com/36560391/120274103-01d8c600-c2cd-11eb-8d3d-0e749c447691.png)

![sale_wizard](https://user-images.githubusercontent.com/36560391/120274125-08673d80-c2cd-11eb-9ef0-1745e05cb470.png)

Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/230 for first version of this issue.

![outplacement](https://user-images.githubusercontent.com/36560391/120294950-52a7e900-c2e4-11eb-92e3-00a47e156cbb.png)

![outplacement_mail](https://user-images.githubusercontent.com/36560391/120294974-58053380-c2e4-11eb-9960-ff2974bea4b3.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 I have tested this module and it is a good start. 
But it does not report all data. Please check again. 
I have not checked all fields now, but please Main target and Alternative target - all of the "second level"-values need to be visible in the report as well. It is ok if the report uses more than one page.

**Comment by rupareliyahemangi145** [comment]
Ok Sure @FredrikArvas 
I will add all data of Mail Goal and Alternative Goal fields in Report. Please let me know which other data you want in report.
Should I need to add all fields in report which are in form view?

**Comment by fredrikarvas-vertel** [comment]
Yes please, add all fields that are in the screenshots of the form view above. 

Thanks

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created https://github.com/vertelab/odoo-outplacement/pull/235 for latest Final reprot with detail of Goals.
[AKTTEST-9311 - Final Report(1).pdf](https://github.com/vertelab/odoo-af/files/6584170/AKTTEST-9311.-.Final.Report.1.pdf)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Great this looks good. Now it is up to our designers to give an opinion about the formatting etc!

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas
