### ISSUE TITLE
AFC-2410 - add import wizard for deregistration to mass_mailing

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#618]
**Userstory:** 
As a Mass_Mailing-user, I want to upload a csv/xlsx-file with a list of "blacklisted" email-addresses to the "de-register"-table in Odoo. Becauase if a Jobseeker has deregistred from one newsletter in one of our systems, they should not need to deregister again. 

A Suggested Format is:  email, date-time, reason (pick one default value)

Security aspects: 
The normal "Import"-function can not be used since it allows the user to import more than just blacklisted emails.

Suggested solution: 
Add a screen with a "File-upload"-function that allows to upload a file in a certain format. 
The file should then be processed by Odoo and stored in the in the "(de)register"-table.

We will use the OCA module mass_mailing_custom_unsubscribe is installed, for unsubscriptions and they are store here
![image](https://user-images.githubusercontent.com/61729317/120177163-6716b380-c208-11eb-98a5-7308cd7b0554.png)

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-mail/tree/Dev-12.0/mass_mailing_unsubscribe_af

**Development Branch name:** 
Dev-12.0-AFC-2410_Blacklisting_wizard

**Target Branch name:** 
https://github.com/vertelab/odoo-mail/tree/Dev-12.0

**Description to the manifest:** 
Adds an import-wizard to allow import of "deregistrations" from the previous system.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:
2 Hours and 10 mins - Prepared code to import files, Analyzed task to complete it. Added some logic and tested it.
2 hours and 20 mins: Prepared code to import with CSV file, Added some user interface warnings to prevent Odoo screen error, Tested functionality, Prepared videos.
2 Hours and 50 mins - Allowed to import with Text format also, Added sample file to download from wizard.
1 Hour: Updated code to import with new File format.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas

I've created PR https://github.com/vertelab/odoo-mail/pull/61 for this
issue.
Here is videos for testing:
https://www.loom.com/share/e09fdb2f25284db1956991562cd297e1
https://www.loom.com/share/c19d34e085c34c949ad4a0d7634e47f2

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Thanks for this module. 
We need to improve the error management a bit:

1
I got this error: 
  File "/opt/af/odoo/odoo_crm/src/odoo-mail/mass_mailing_unsubscribe_af/wizard/import_deregistration.py", line 119, in import_data
    date = str(datetime.strptime(date, DEFAULT_SERVER_DATETIME_FORMAT) - timedelta(hours=2))
TypeError: strptime() argument 1 must be str, not float

When I imported this Excel file: (Excel strips out the seconds).
![image](https://user-images.githubusercontent.com/61729317/120963928-c02f9b80-c762-11eb-8db5-f7e901b8f0bc.png)

2  Please display the expected format.
(and I would like the csv-headers to be small-letters only)
![image](https://user-images.githubusercontent.com/61729317/120964072-fbca6580-c762-11eb-87b3-aa8a2510d43d.png)

3
![image](https://user-images.githubusercontent.com/61729317/120964289-624f8380-c763-11eb-99d7-ad7d95905b3e.png)

4 This file worked fine to import.
[email_import.zip](https://github.com/vertelab/odoo-af/files/6606141/email_import.zip)

5 We need to add some more logic in order to link the content of the unsubscribe reasons to existing reason.
![image](https://user-images.githubusercontent.com/61729317/120964582-d38f3680-c763-11eb-9e88-75aa8b137b24.png)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas ,

I've added one more commit in same PR https://github.com/vertelab/odoo-mail/pull/61 for above changes.

Here is videos for testing:
1. https://www.loom.com/share/5250fb4a27ab468099d51e09ce96dd45
2. https://www.loom.com/share/98ac104fa1b64d768d9bbf3855b8fc69
3. https://www.loom.com/share/1afc4b18c9cb4b8792524bb815bbbfe5

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 
I have now got the exact format we are getting from the previous system. 
Could you please add that as an alternative import-format?
Pick only column 2 and 3 and for now, only assign the default un-subscription reason.
The date-time needs to be accepted in the format given here.
[Optout_Apsis_2021-06-07_test.zip](https://github.com/vertelab/odoo-af/files/6613708/Optout_Apsis_2021-06-07_test.zip)

**Comment by fredrikarvas-vertel** [comment]
Please push these changes to the same branch

**Comment by rupareliyahemangi145** [comment]
Ok Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 
I've pushed new commit in same branch to import with new file format.

Please check it and let me know if anything.

Thanks.

Regards,
Heamangi.
