### ISSUE TITLE
AFC-2441_Add_Pivot-view for interpreter bookings

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#630]
**Userstory:** 
As a Interpreter Accountant-user, I want see a report of how many interpreters are booked, to follow up bookings.

Add Pivot-view (and other graphical views if they are easy to add).
(x are prio 1)

**Meaures**
x Count
Interpreter time
Interprter Additional time

**Values**
x date
split_start_time
duration
additional_time
x Interpreter _remote_type.name
x Interpreter _language.name
Interpreter _language.code
user_id
interpreter_booking_status
interpreter_company.name

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter

**Development Branch name:** 
Dev-12.0-2441_Interpreter_report

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Description to the manifest:** 
AFC-2441 adds a Pivot-view

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 20 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas Let me check this issue.

**Comment by rupareliyahemangi145** [comment]
PR for this issue is with #633 issue.

**Comment by Anushalewis** [comment]
@rupareliyahemangi145  : Please have a look , there are some deviations from the expected results . [Test Results AFC-2441.docx](https://github.com/vertelab/odoo-af/files/6966219/Test.Results.AFC-2441.docx)

**Comment by rupareliyahemangi145** [comment]
Ok Let me check @Anushalewis

**Comment by rupareliyahemangi145** [comment]
Hello @Anushalewis Please send full screenshot of error on Language

Click on see full details link on error popup.

**Comment by rupareliyahemangi145** [comment]
Hello @Anushalewis 

Please schedule call. I want to discuss with you.

**Comment by Anushalewis** [comment]
@rupareliyahemangi145 : additional screen shots added   : [Test Results AFC-2441.docx](https://github.com/vertelab/odoo-af/files/6966626/Test.Results.AFC-2441.docx)

**Comment by rupareliyahemangi145** [comment]
Ok Thanks but still need call.

**Comment by Anushalewis** [comment]
Hi @rupareliyahemangi145 : As discussed over the call, testing results updated, works as expected.
[Test Results AFC-2441.docx](https://github.com/vertelab/odoo-af/files/6972995/Test.Results.AFC-2441.docx)

This issue can be closed.
