### ISSUE TITLE
AFC-2445 [BUG] Statuses in Interpreter bookings

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#633]
1
Please add the status = '5': _('Cancelled by Interpreter'), as a "Interpreter Booking Status " and in "Odoo Widget"
![image](https://user-images.githubusercontent.com/61729317/120822535-cbae7700-c556-11eb-8a6b-fb586342323e.png)

https://github.com/vertelab/odoo-outplacement/blob/55bfe8c72f055aa40106d36795904bc3449a2420/outplacement_order_interpreter/models/mail_activity.py

2
Change the order in Interpreter "search view"
![image](https://user-images.githubusercontent.com/61729317/120822395-a91c5e00-c556-11eb-9a0d-85839cb2f68d.png)

3
Add group by "Booking Status"
![image](https://user-images.githubusercontent.com/61729317/120823128-6444f700-c557-11eb-9825-17d52d007725.png)

4 
If simple, Add a Calendar view 

**Module name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter

**Development Branch name:** 
Dev-12.0-AFC-2445-interpreter-status

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

**Description to the manifest:** 
AFC-2445 displays the state Cancelled by Interpreter.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 hours and 30 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Can I create one PR for this issue and https://github.com/vertelab/odoo-af/issues/630 issue to avoid conflicts?

Because both issues changes are in One file and one xml record.

**Comment by fredrikarvas-vertel** [comment]
Yes!

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-outplacement/pull/238 for this issue and #630 issue.

Here is videos(with voice):
https://www.loom.com/share/7ed82b84070c4bbb8ac3213f04451175
https://www.loom.com/share/06f6e889f88a475394a7cbe985c74a3b

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Merged
