### ISSUE TITLE
AFC-2438 Translate the text box while submitting the  GP 

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#636]
**User story:** 

In the outplacement; we have a dependency field Mötestyp(meeting_remote) which needs to be filled in for sending/submitting the GP tasks to the BÄR. 
While submitting the tasks we will get a warning message as shown in figure below.

Step :1
Look after the dependency field
![image](https://user-images.githubusercontent.com/59916603/121178103-6dd3a500-c85e-11eb-8845-cb127ef31c34.png)

Step: 2
Change the translation
![image](https://user-images.githubusercontent.com/59916603/121180135-c99f2d80-c860-11eb-9a86-7d553a236460.png)

**Module name:** (added by Nils or Fredrik)
outplacement

**Development Branch name:** 
Dev-12.0-AFC-2438_submit_GP_translation

**Target Branch name:** 
https://github.com/vertelab/odoo-af/tree/Dev-12.0-Fenix-Sprint-02

**Test-steps:**
Check the branch is merged.
Go in to the test environment 
Log in with DAFA Handledare user role 
Select " send the GP to BÄR then a pop up  message box appears with Swedish text

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 50 mins with Discussion, Development, Submission.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 and @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/242 for this issue.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
