### ISSUE TITLE
AFC-2469 - prepare code for automatic testing

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#640]
Please identify reasons for error/warning-messages when installing DAFA

and suggest solutions

Table 'account_move': column 'period_id': unable to set constraint NOT NULL
column "period_id" contains null values

odoodafa odoo.models: The model hr.employee.user.ciam has no _description 

odoodafa odoo.addons.base.models.ir_model: Two fields (operation_ids, operation_id) of hr.employee() have the same label: Operation.

Two fields (partner_state_id, stage_id) of outplacement() have the same label: State.

odoodafa odoo.addons.base.models.ir_model:  - Two fields (partner_email, email_from) of outplacement() have the same label: Email.

odoodafa odoo.addons.base.models.ir_model: Two fields (skill_id, skills) of outplacement() have the same label: Skill.

odoodafa odoo.addons.base.models.ir_model: Two fields (interpreter_remote_type, interpreter_type) of outplacement() have the same label: Interpreter Type.

 

etc...

 

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by rupareliyahemangi145** [comment]
Ok Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

For this issue, Should I need to fix this warnings or need to find tool for automatic testing?

**Comment by fredrikarvas-vertel** [comment]
I think we can do this in two steps. 
1 Fix issues that needs to be fixed that can be found with "automatic qualty testing".
2 set up testing-scripts. Here we need more knowledge about how to do this.
