### ISSUE TITLE
AFC-2469  - clean up unused code

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#641]
https://jira.arbetsformedlingen.se/browse/AFC-2469

https://github.com/vertelab/odoo-outplacement/pull/239/commits

Actual Hours:

Hemangi - 50 mins: Checked committed code and removed other two unused extra methods.

**Comment by Bahaa864** [comment]
> https://jira.arbetsformedlingen.se/browse/AFC-2469

https://www.facebook.com/groups/elite.of.iraq

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created new PR https://github.com/vertelab/odoo-outplacement/pull/255 for this issue.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
