### ISSUE TITLE
AFC-2465- The KA-number is not part of the automated email for interpreter cancellation

### ISSUE THREAD

**Issue by Anushalewis** [vertelab/odoo-af#642]
**User story** : The KA-number is not part of the automated email for interpreter cancellation
As a user of the DAFA-system, when a interpreter booking is cancelled user should be able to see both the reference  number and the KA number on the automated email .

To replicate the issue follow the steps, please refer below for screen shots.
Log in user of dafa , cancel an interpreter booking, click on the text in window as below existing system the automatic cancellation email subject has booking reference number only.

•Please add KA-Nr to the email subject 
![image](https://user-images.githubusercontent.com/84374527/121608009-60cad780-ca51-11eb-97a2-fba1b0a99616.png)

**Module name:**  https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter

**Development Branch name:**
Dev-12.0-DAFA-AFC-2465_Add_KA_Number_On_Automated_Email_Interpreter_Cancellation

**Target Branch name:**
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

**Test-steps:**
•Log in as : user in dafa
•Do this to recover the error:
  cancel an interpreter booking
  click on the text in the window
•This is what happens:
An email is created with Booking Reference. The email subject should have the KA number in addition to booking reference.

**Description to the manifest:**
This user story adds  KA number in addition to booking reference on the subject of the automated email for interpreter cancellation.

**Estimate:** (@Developers: Add your times here, not in comments please)
**Estimated Hours:
Estimated Date:**

**Comment by fredrikarvas-vertel** [comment]
Hi @Anushalewis 

Thanks for doing this issue. Here are a few comments: 
1 The userstory gives a clear understanding of what needs to happen. In this case the change is small and we can accept a smaller userstory, but it is usually better to give more information then to little. 

2 The image is clear!

3 The module-name is easier to get correct if you copy the URL to the module. In this case: 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter
This gives the developer a direct link to both the Odoo-Project (Repository), the Current branch and the module. 

4 The development branch is normally only one. In this case: 
Dev-12.0-DAFA-AFC-2465_Add_KA_Number_On_Automated_Email_Interpreter_Cancellation

5 The Target Branchname is: 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/
This is where the Pullrequest should be aimed at. 

6 The important part of the test-step is to illustrate that the change works. In this case, we want to see the KA-number next to the Booking Reference-number. 

7 The Manifest Description is normally a short line that describes what this enhancement do to an existing module. In this case: 
AFC-2465 Adds KA-number to the email-link.
If the module is new, then it is appropriate to give a full description. (and we should store that in the index- or readme-file now.

8 Please add project to the issue as well, this helps the follow up of the issues. 

I hope these comments can help. 
/Fredrik

**Comment by Anushalewis** [comment]
@fredrikarvas-vertel : Thank you for the well described inputs ,  The comments have been very helpful, have made the corrections and will follow the same when writing future stories .
