### ISSUE TITLE
AFC-2471-review the code according to pep8

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#643]
One PR for each per repository.
One Repository will come with multiple module-changes.

Add README.rst file
Format code based on pep8 

**Done Repositories**
odoo-outplacement - https://github.com/vertelab/odoo-outplacement/pull/246 - Merged
odoo-web - https://github.com/vertelab/odoo-web/pull/66  - Merged
odoo-mail - https://github.com/vertelab/odoo-mail/pull/63  - Merged
odoo-project - https://github.com/vertelab/odoo-project/pull/31 - Merged 
odoo-base - https://github.com/vertelab/odoo-base/pull/329  - Merged
odoo-sale - https://github.com/vertelab/odoo-sale/pull/23  - Merged
odoo-af - https://github.com/vertelab/odoo-af/pull/648  - Merged
odoo-api - https://github.com/vertelab/odoo-api/pull/19 - Merged
odoo-hr - https://github.com/vertelab/odoo-hr/pull/72 - Merged
odoo-account - https://github.com/vertelab/odoo-account/pull/4 - Merged
server-auth - https://github.com/vertelab/server-auth/pull/6 - Merged
odoo-user-mail- https://github.com/vertelab/odoo-user-mail/pull/1 - Merged
odoo-server-tools - https://github.com/vertelab/odoo-server-tools/pull/6 - Merged

*Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 
12th Jun 2021 - 2 Hours and 40 mins - Updated odoo-outplacement and odoo-web.
14th Jun 2021 - 5 Hours and 10 mins - Updated odoo-mail, odoo-project and odoo-base.
15th Jun 2021 - 4 Hours and 20 mins - Updated odoo-base, odoo-sale and odoo-af.
17th Jun 2021 - 2 Hours and 30 mins - Updated odoo-af.
29th Jun 2021 - 2 Hours and 10 mins - Updated odoo-api, odoo-hr, odoo-account, server-auth,odoo-user-mail, odoo-server-tool 1st Jul 2021 - 40 mins - Updated code to remove warnings from log.
2nd Jul 2021 - 3 Hours - Updated code to remove warnings from log.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/246 for Outplacement repo.

- Added README.rst file in all modules of outplacement repo.
- Formatted code based on pep8 in all modules of outplacement repo.
- Updated code to remove warnings from terminal which were came from this repo's modules.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-web/pull/66 for odoo-web repo.
- Formated code according to pep8.
- Added README.rst file.
- Updated index.html file where index.html file added.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Yesterday I've created PR for odoo-mail https://github.com/vertelab/odoo-mail/pull/63 and odoo-project https://github.com/vertelab/odoo-project/pull/31. And just now created PR for odoo-base https://github.com/vertelab/odoo-base/pull/329.
- Formated code according to pep8.
- Added README.rst file or index.html file.
- Updated index.html file where index.html file added.

Note: Added index.html file instead of README.rst where application: True in manifest file. Because we can't see content of README file where application:True in manifest file.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-af/pull/648 for odoo-af.

- Formated code according to pep8.
- Added README.rst file or index.html file.
- Updated index.html file where index.html file added.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created following PRs to format code.

1. odoo-api
https://github.com/vertelab/odoo-api/pull/19
- Formatted code according to pep8.

2. odoo-hr
https://github.com/vertelab/odoo-hr/pull/72
- Formatted code according to pep8 for installed modules.

3. odoo-account
https://github.com/vertelab/odoo-account/pull/4
- Formatted code according to pep8 for installed modules.

4. server-auth
https://github.com/vertelab/server-auth/pull/6
- Formatted code according to pep8 for installed modules.

5. odoo-user-mail
https://github.com/vertelab/odoo-user-mail/pull/1
- Formatted code according to pep8 for installed modules.

6. odoo-erver-tools
https://github.com/vertelab/odoo-server-tools/pull/6
- Formatted code according to pep8 for installed modules.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PRs to remove warnings from log.

1. https://github.com/vertelab/odoo-website/pull/10
2. https://github.com/vertelab/odoo-web/pull/71
3. https://github.com/vertelab/odoo-base/pull/344
4. https://github.com/vertelab/odoo-outplacement/pull/260
5. https://github.com/vertelab/odoo-hr/pull/74
6. https://github.com/vertelab/odoo-user-mail/pull/2
7. https://github.com/vertelab/odoo-edi/pull/108
8. https://github.com/vertelab/odoo-auth/pull/24
9. https://github.com/vertelab/odoo-l10n_se/pull/15
By mistake I pushed code in Dev-12.0 branch of odoo-l10n_se https://github.com/vertelab/odoo-l10n_se/commit/bdc67b4c654b708c98c9588c082d43ca4e25694f but then I reverted it https://github.com/vertelab/odoo-l10n_se/commit/473e371d75de19b3508c5be51b8e9e33b028715f.

Please check it when you can and let me know if anything.

Thanks.

Regards,
Hemangi.
