### ISSUE TITLE
AFC-2505 - Extend outplacement with jobseeker category

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#653]
1 
**Userstory:** 
As an Interpreter Accountant, I need to see the "jobseeker-category" of an "interpreter booking"
For this to happen, we need to add one more field from CRM to DAFA. Data is fetched when the Outplacement is created. 
(See Kundbild Arbetssökande -> Kundbild Deltagare in the image)
![image](https://user-images.githubusercontent.com/61729317/123038074-084fee80-d3f0-11eb-8adc-5fed2c448bc0.png)

I think that this is done by calling this method:
https://github.com/vertelab/odoo-outplacement/blob/cf1d9dbb2e6c586785835be506a234842f8698c1/outplacement_crmsync/models/res_partner.py#L257
from:
https://github.com/vertelab/odoo-outplacement/blob/cf1d9dbb2e6c586785835be506a234842f8698c1/sale_outplacement/models/outplacement.py#L183

**Solution:** 
Add the Jobseeker Category to the CRM-DAFA synk
![image](https://user-images.githubusercontent.com/61729317/123037192-83180a00-d3ee-11eb-92cc-1c012edba9e4.png)

![image](https://user-images.githubusercontent.com/61729317/123035523-c15ffa00-d3eb-11eb-94fe-abac58814112.png)
**DAFA Sync is used on the CRM-side:** 
(I am not sure if there needs any changes on the CRM-side, since the field is stored on the res_partner). 
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0/outplacement_dafasync/models/res_partner.py

**CRM Sync is used on the DAFA-side.** 
Add the field jobseeker_catogory to DAFA
![image](https://user-images.githubusercontent.com/61729317/123037780-8cee3d00-d3ef-11eb-9041-48204753bef9.png)

Add the field here: 
https://github.com/vertelab/odoo-outplacement/blob/cf1d9dbb2e6c586785835be506a234842f8698c1/outplacement_crmsync/models/res_partner.py#L293

Add the Jobseeker Category to the Outplacement View, with user-group "debug"
![image](https://user-images.githubusercontent.com/61729317/123034992-e011c100-d3ea-11eb-839d-fddcf4585685.png)

Add the Jobseeker Category to the Interpreter Accountant View
![image](https://user-images.githubusercontent.com/61729317/123035102-0cc5d880-d3eb-11eb-8482-3d01bd84a71d.png)
![image](https://user-images.githubusercontent.com/61729317/123035167-29621080-d3eb-11eb-90ac-61ab29f0bd12.png)

Add the Jobseeker category to the Interpreter Bookings Report
![image](https://user-images.githubusercontent.com/61729317/123035453-a2f9fe80-d3eb-11eb-99bd-4461007b267d.png)

2
Remove these unused actions from the outplacement menu
![image](https://user-images.githubusercontent.com/61729317/123037501-10f3f500-d3ef-11eb-8227-22eb2542eef3.png)

3 Add the Group-by translation for Swedish language: Bokningsstatus, as displayed in the Tree-view-header.
![image](https://user-images.githubusercontent.com/61729317/123035308-6b8b5200-d3eb-11eb-833b-366ce5b385e9.png)

**Development Branch name:** 
Dev-12.0-AFC-2505_ExtendJobseekerCategory

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_crmsync
(and possibly also) 
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0/outplacement_dafasync/

**Test-steps:**
Run the action on a DAFA-system in Af's test-environment. 
I do not think it is possible to test this module in the dev-server.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 3 Hours and 50 mins - First version
50 mins - Added partner_view_360 and partner_co_address in odoo-base Fenix and checked functionality again.
1 Hour - Removed dependency of partner_view_360 and added new module partner_view_360_DAFA.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

**jobseeker_category** is comes from partner_view_360(https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/partner_view_360). jobseeker_category is based on  jobseeker_category_id, which is Many2one of res.partner.skat.

And res.partner.skat is not added in any module. It was added in partner_view_360_old module.
https://github.com/vertelab/odoo-af/blob/Dev-12.0-Fenix-Sprint-02/partner_view_360_old/models/res_partner.py#L307

So JFI, I have to add it in partner_view_360(https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/partner_view_360).

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created following PRs for this issue:
During this issue I faced some errors. So also created PRs for those.

1. https://github.com/vertelab/odoo-base/pull/334
- Updated inverse name on partner_id to prevent error when clicking on Jobseeker record from Partner view.
- Improved code to prevent logger warning and for compute method.

2. https://github.com/vertelab/odoo-base/pull/335
- Added class(model) for res.partner.skat.
- Improved compute method code.
 - Added access right for res.partner.skat.

3. https://github.com/vertelab/odoo-hr/pull/71
- Added outplacement module in depends as outplacement model is used in module.

4. https://github.com/vertelab/odoo-outplacement/pull/248
- Added Jobseeker category in outplacement and its interpreter booking.
- Synced Jobseeker category from CRM.
- Removed two server actions.

5. https://github.com/vertelab/odoo-outplacement/pull/249
- Sent Jobseeker information to DAFA.

Please check it and let me know if anything.

Here is screenshots for result:
![booking_form](https://user-images.githubusercontent.com/36560391/123085409-d5354b80-d43f-11eb-92d2-19eddd157bfd.png)

![booking_tree_search](https://user-images.githubusercontent.com/36560391/123085416-d6ff0f00-d43f-11eb-998e-4a6583970d87.png)

![booking_pivot](https://user-images.githubusercontent.com/36560391/123085420-d8303c00-d43f-11eb-8f22-edd2c31e7c0e.png)

![outplacement](https://user-images.githubusercontent.com/36560391/123085422-d9616900-d43f-11eb-8376-265fc02519de.png)

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Please copy partner_360:view from dev-12.0 to dev-12- Fenix-branch and try to apply your changes again.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created new PR for odoo-base Fenix. Added partner_view_360 module and partner_co_address(Need as it is in depends).

Here are latest PR's list.

1. https://github.com/vertelab/odoo-base/pull/334
- Updated inverse name on partner_id to prevent error when clicking on Jobseeker record from Partner view.
- Improved code to prevent logger warning and for compute method.

2. https://github.com/vertelab/odoo-base/pull/338
- Added partner_view_360 and partner_co_address

3. https://github.com/vertelab/odoo-hr/pull/71
- Added outplacement module in depends as outplacement model is used in module.

4. https://github.com/vertelab/odoo-outplacement/pull/248
- Added Jobseeker category in outplacement and its interpreter booking.
- Synced Jobseeker category from CRM.
- Removed two server actions.

5. https://github.com/vertelab/odoo-outplacement/pull/249
- Sent Jobseeker information to DAFA.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi

**Comment by fredrikarvas-vertel** [comment]
I would like to avoid dependency to the partner_360_view-module if possible. 
Could you see if you can add the functionality you are now depending on in an existing module or in a new extend-module called partner_360_view_dafa which only uses the required code?

Please add the changes in point 4 and 5 in the same pull request, then I can test them all in one go.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've used **partner_360_view** module just for Jobseeker category.
Do you want Job-seekers menu for DAFA?
If not then I can add new module partner_360_view_dafa, and in that module I will add fields for Job seeker category in res.partner.

**Comment by fredrikarvas-vertel** [comment]
We do not want the "Jobseekers"menu in DAFA.
Yes please create a separate module, and we can use that module for fields that are added in CRM by partner_360_view without installing the partner_360_view

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created new PR for odoo-base Fenix. Added partner_view_360_DAFA module.

Here are latest PR's list.

1. https://github.com/vertelab/odoo-base/pull/334
- Updated inverse name on partner_id to prevent error when clicking on Jobseeker record from Partner view.
- Improved code to prevent logger warning and for compute method.

2. https://github.com/vertelab/odoo-base/pull/339
- Added partner_view_360_DAFA module to add Jobseeker category inside res.partner.

3. https://github.com/vertelab/odoo-hr/pull/71
- Added outplacement module in depends as outplacement model is used in module.

4. https://github.com/vertelab/odoo-outplacement/pull/248
- Added Jobseeker category in outplacement and its interpreter booking.
- Synced Jobseeker category from CRM.
- Removed two server actions.
- Added dependency of partner_view_360_DAFA 

5. https://github.com/vertelab/odoo-outplacement/pull/249
- Sent Jobseeker information to DAFA.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi

**Comment by Anushalewis** [comment]
@rupareliyahemangi145 : Test Results attached. Jobseeker fields  are empty 
[AFC-2505 test results.docx](https://github.com/vertelab/odoo-af/files/6799043/AFC-2505.test.results.docx)

**Comment by fredrikarvas-vertel** [comment]
@Anushalewis  - I see that this code is working in production.
1 did you check on a new/old jobseeker?
2 did you test to update the "action" to only update the Jobseeker Category?

Thanks

**Comment by Anushalewis** [comment]
@fredrikarvas-vertel : I have tried testing again today job seeker Fields are empty. on test db1701 environment.
update jobseeker category on action gives an error : 
<img width="952" alt="2505 job seeker category update error" src="https://user-images.githubusercontent.com/84374527/125409275-090aed80-e3bc-11eb-93cc-b59559afd2b2.png">

**Comment by fredrikarvas-vertel** [comment]
This has to do with the config of the pods. 
I ran the script in production yesterday for all jobseekers so the module works.  We need better test-data/config between the pods.
