### ISSUE TITLE
AFC-2456 -Ignore the value "FALSE" if it is set as default language

### ISSUE THREAD

**Issue by Anushalewis** [vertelab/odoo-af#654]
User story : As a user of the DAFA-system, The field temp_lang (Language support requested) on the outplacement view  should not  have False as the default value.

To replicate the issue follow the steps, please refer below for screen shots.
Log in as user of dafa, open outplacement view , filter Language support requested = false.

![image](https://user-images.githubusercontent.com/84374527/123176088-23b80980-d483-11eb-9c71-5fb887b3721a.png)

![image](https://user-images.githubusercontent.com/84374527/123177049-d0df5180-d484-11eb-827a-d6e7b0081d75.png)

If it is easy, plase also provide a server action that can be run manually to remove the value false on existing outplacements.

External id of the view : sale_outplacement.outplacement_form_view
Module name: https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/sale_outplacement/

Development Branch name:
Dev-12.0-DAFA-AFC_2456_Ignore_False_On_Language_Support_Requested

Target Branch name:
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/

Test-steps:
•Log in as : user in dafa
•Do this to recover the error: Open Outplacement view, filter by Language support requested field = “False”
•This is what happens: There should not be any results with Language support request field as false
(This applies only to new outplacements).

Description to the manifest:
This user story removes the default value for language requested field which is “False”.

Estimate: (@Developers: Add your times here, not in comments please)
Estimated Hours:
Estimated Date:
Actual Hours: 40 mins

**Comment by fredrikarvas-vertel** [comment]
Thanks Anusha, This issue works fine now.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/250 for this issue.

Added server action **'Update Language Support Requested'** to keep **Language Supported Request** field empty if there is false for exiting records.
And prevented false value for new records.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
