### ISSUE TITLE
AFC-2535 - add error handling in API for Joint planning

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#656]
**Userstory:** 
As a user of the system, I want to know that the transmission was successful, before I get a "message" in the chatter-log that the JointPlanning was sent
[bar-genomforande-redovisning-1.0.13-raml.zip](https://github.com/vertelab/odoo-af/files/6710534/bar-genomforande-redovisning-1.0.13-raml.zip)

https://github.com/vertelab/odoo-outplacement/pull/252

In this branch I've added a basic check to make sure that the response code from BÄR is 201 and only set jp_sent_date if it is, this is so that SR can't be sent if the GP wasn't accepted.

For more accurate look at line 34-41 of outplacement_final_report_send/models/outplacement.py, however the code cannot be copied exactly as the GP API might not have the same structure to their responses.

The structure for responses may also look different depending on what went wrong, for an example a 400 error for SR looks like this:
{
"error_id": null,
"message": "Bad request.",
"cause":

{ "message": "Error validating JSON. Error: - Invalid element Delta i praktik." }
}

But when getting a 500/501 error the structure will be slightly different as the cause dict also includes a "code" field in those cases.

Therefore someone has to test sending some different kinds of faulty GPs in Postman to see what the responses look like and how they are structured. The data I have to test with returns a 404 error with no response text at all, so 404 errors have to be handled separately (this assumes that some types of errors do return a response text which I'm not sure of).

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 50 mins

**Comment by fredrikarvas-vertel** [comment]
@FredrikArvas  books a meeting between @rupareliyahemangi145  and @SebastianGieser-Vertel  to explain the error messages in the APi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-outplacement/pull/257 for this issue.
In this PR updated code for following:
1. This will add logger in odoo log file and raise popup on screen if there will be any connection error.
2. If after connection there is no success response 201 then it will add logger and also raise user error on screen.
With Response status code and reason of response like Not found, Forbidden, Not allowed etc based on response code.

Please check it and let me know if anything. If this way will work we will apply it for all.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 
I have checked the error log for the integration for Joint planning and found these: 

'message': 'Bad request', 'cause': {'system': 'BAR', 'code': '400', 'message': 'case_resolved', 'error': {'pxObjClass': 'AF-Int-Cause'}}}
message': 'Bad request', 'cause': {'system': 'BAR', 'code': '400', 'message': 'case_not_found', 'error': {'code': 'Pega_API_004', 'pxObjClass': 'AF-Int-Cause'}}}
 'message': 'Internal error.'}
 'message': 'Conflict', 'cause': {'system': 'BAR', 'code': '409', 'message': 'GP already exists', 'error': {'pxObjClass': 'AF-Int-Cause'}}}
'message': 'Error validating JSON. Error: - Invalid type Boolean, expected String'}}

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

This is response from API which added in log.

**Comment by fredrikarvas-vertel** [comment]
Great @rupareliyahemangi145 

How complex is it to add a function that sends an email to (configurable address in system parameters) team-crm@arbetsformedlingen.se when the API gets an error?

It is important that the email contains: 
URL to the database
Name of the API that malfunctions
Error message including some kind of ID to the record. 
But no personal data (Name, SSN, email, Phonenr).

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

It will take 2 to 3 hours.

**Comment by fredrikarvas-vertel** [comment]
Great @rupareliyahemangi145 
1 Please add that for Completion report. 
2 And please change display-name of that API to "Gemensam Planering" (we are changing to Swedish business terms for certain key phrases in the code.
![image](https://user-images.githubusercontent.com/61729317/124223770-acc6e480-db04-11eb-886c-56852fe29150.png)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @Anushalewis

Please let me know once you create new issue.

**Comment by Anushalewis** [comment]
> Hello @Anushalewis
> 
> Please let me know once you create new issue.

Hey @rupareliyahemangi145 

New issue has been created : https://github.com/vertelab/odoo-af/issues/667
