### ISSUE TITLE
AFC-2357 Add Visible aid for submitting Joint Planning and Final Report

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#658]
**Userstory:** 
As a Case Worker, I want to be assisted in what to do in the system:

Add a calculation to allow for filter and visible aid: 
1 Add calculated field_ outplacement.time_to_submit_jp: 
Display if: 
”Today>(Start data + 5 workdays)” AND ”Joint Planning date Submitte = EMPTY”

2 Add calculated field_ outplacement.time_to_submit_fp: 
”Today>(End date + 5 workdays)” AND ”Final Report Submit-date = EMPTY”

3 Add Visible aid on the kanban view
![image](https://user-images.githubusercontent.com/61729317/123326651-c763f100-d539-11eb-97c4-06e4850b0fc3.png)

4 Add filter for EN: "Time to submit joint planning" SV: "Dags att skicka in gemensam planering"

5 Add filter for  EN: "Time to submit Final Report" SV: "Dags att skicka in slutredovisning"

**Module name:** (added by Nils or Fredrik)
odoo-outplacment/sale_outplacement

**Development Branch name:** 
Dev-12.0-AFC-2357_Add_visual_Reminder

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/sale_outplacement

**Description to the manifest:** 
AFC-2357 Adds visual aids on the kanban-view to help the caseworker to remember to submit Joint Planning and Final Report.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/254 for this issue.

Here is video for result:
https://www.loom.com/share/a3cfa17a1f054055a300bfbe121b1d7b

Please check it when you can and let me know if anything.

Thanks.

Regards,
Hemangi.
