### ISSUE TITLE
AFC-2539a -  downgrade module_change_auto_install to V12

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#660]
**Userstory:** 
1 We want to use this module in V12. See if it can be downgraded.
https://github.com/OCA/server-tools/tree/14.0/module_change_auto_install

**Userstory:** 
2 As a sysadmin I want to see which modules we have with auto-install enabled based on the "install all module"-list of depends in our system to decide which to keep and which not to keep.

**Development Branch name:** 
Dev-12.0-AFC-2549_module_change_auto_install

**Target Branch name:** 
https://github.com/vertelab/odoo-server-tools/tree/Dev-12.0

**Test-steps:**
See module documentation

**Description to the manifest:** 
See module documentation

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-server-tools/pull/4 to add this module in odoo-server-tool  Dev-12.0 branch.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
