### ISSUE TITLE
AFC-2457-Change to Swedish business terms for certain key phrases

### ISSUE THREAD

**Issue by Anushalewis** [vertelab/odoo-af#667]
Userstory : Please Change to Swedish business terms for certain key phrases
As a user of DAFA I would like to see the correct Swedish terms.
please change display-name of the “IPF CompletionReport Client Config” to "Gemensam Planering"

Please refer the below screen shot.
![image](https://user-images.githubusercontent.com/84374527/124280930-85ded180-db49-11eb-91b0-65a55f5ef369.png)

![image](https://user-images.githubusercontent.com/84374527/124281132-b58dd980-db49-11eb-876b-e11ada9f6d95.png)

External id : outplacement_completion_report_ipf_client.ipf_client_config_view_list

Module name: 
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_completion_report_ipf_client/views/client_config_views.xml

Development Branch name:
Dev-12.0-AFC-2457_Change_to_Swedish_business_terms_for_certain_key_phrases

Target Branch name:
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

Test-steps:
Scenario 1 :
Install the module , Select the technical drop down ,Correct Swedish business terms for IPF configurations.

Description to the manifest:
This user story adds Swedish business terms to technical dropdown view for ease of use for the user.
Estimate: (@Developers: Add your times here, not in comments please)
Estimated Hours:
Estimated Date:
Actual Hours: 2 Hours and 30 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-outplacement/pull/261 for this issue.

Here is video for result:
https://www.loom.com/share/e330dc02d97a4e8998fc585bbbd16ca8

Please check it when you can and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 
This is great. 
Could you make the error message more userfriendly int he chatter-log?
Possibly only stating: "There was an error when sending the joint planning. It has been reported to Service desk and will be handled."

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Is this ok now?
![email](https://user-images.githubusercontent.com/36560391/124420664-88c20800-dd7d-11eb-8630-88b94a4310ad.png)

![rec](https://user-images.githubusercontent.com/36560391/124420669-8a8bcb80-dd7d-11eb-90fc-2f7463565d64.png)

**Comment by fredrikarvas-vertel** [comment]
Yes
and cand you add the swedish translation: 

"Det uppstod ett fel vid överföringen av den gemensamma planeringen. Felet är rapporterat till ServiceDesk och kommer att åtgärdas. Du blir kontaktad om du behöver göra något mer. "

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've updated chatter log message in same PR https://github.com/vertelab/odoo-outplacement/pull/261

Please check it when you can and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've updated translation from "Gemensam Planering" to "IPF Gemensam Planering Client Config" in same PR https://github.com/vertelab/odoo-outplacement/pull/261/commits/2130544e0c44ece6448e6c25c1d79cc7520a9e14

Please check it when you can.

Thanks.

Regards,
Hemangi.
