### ISSUE TITLE
AFC-2560-IPF Configurations - fix better error message

### ISSUE THREAD

**Issue by Anushalewis** [vertelab/odoo-af#669]
User story : Please change error message and translate error messages to Swedish for ease of use. 
As a user of DAFA I would like to see the correct error message in Swedish language for each IPF configurations.

1.	Please change error messages for each of ipf configurations “IPF TLR Client Config” 
![image](https://user-images.githubusercontent.com/84374527/124484696-000e9080-ddac-11eb-9f09-086ec2bb38e7.png)
![image](https://user-images.githubusercontent.com/84374527/124484703-043aae00-ddac-11eb-860e-3e4785e075dc.png)

External id : api_ipf_tlr_client.ipf_client_config_view_form
Module name: https://github.com/vertelab/odoo-api/tree/Dev-12.0-Fenix-Sprint-02/api_ipf_tlr_client 

2.	Please change error messages for ipf configuration :  “IPF Deviation Report Client Config” 
![image](https://user-images.githubusercontent.com/84374527/124484789-216f7c80-ddac-11eb-894c-f5da09a686bc.png)
![image](https://user-images.githubusercontent.com/84374527/124485006-68f60880-ddac-11eb-914b-1296845fd7c7.png)

External id : outplacement_deviationreport_ipf_client.ipf_report_client_config
Module name: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_deviationreport_ipf_client

3.	Please change error messages for ipf configuration :  “IPF Final Report Client Config” 
![image](https://user-images.githubusercontent.com/84374527/124485055-78755180-ddac-11eb-8c24-b5d4fb95386a.png)
![image](https://user-images.githubusercontent.com/84374527/124485081-8034f600-ddac-11eb-8f22-f8cdac1d20d0.png)

External id : outplacement_final_report_ipf_client.ipf_client_config_view_list
Module name: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_final_report_ipf_client

4.	Please change error messages for ipf configuration :  “IPF Showorder Client Config” 
 ![image](https://user-images.githubusercontent.com/84374527/124485169-9642b680-ddac-11eb-92b6-c9c279fedb6b.png)
![image](https://user-images.githubusercontent.com/84374527/124485196-9f338800-ddac-11eb-839a-65240c503f33.png)

External id : sale_showorder_ipf_client.ipf_client_config_view_list
Module name: https://github.com/vertelab/odoo-sale/tree/Dev-12.0-Fenix-Sprint-02/sale_showorder_ipf_client

5.	Please change error messages for ipf configuration :  “IPF Interpreter Client Test” 
![image](https://user-images.githubusercontent.com/84374527/124485280-b3778500-ddac-11eb-8375-46c2998466b4.png)
External id : task_interpreter_ipf_client.ipf_client_config_view_list
Module name: https://github.com/vertelab/odoo-project/tree/Dev-12.0-Fenix-Sprint-02/task_interpreter_ipf_client

Development Branch name:
Dev-12.0- AFC-2560_IPF_Configurations_fix_better_error_message
Target Branch name:
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/
Test-steps:
Scenario 1 :
Install the module, Select the technical drop down, select error messages correct error messages should be available in Swedish

Description to the manifest:
This user story adds relevant Swedish error messages when the API does not return a successful response.
Estimate: (@Developers: Add your times here, not in comments please)
Estimated Hours:
Estimated Date:
Actual Hours: 2 Hours
1 Hour and 40 mins - Checked error and discussed with Anusha and Fixed.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here is information for APIs and PRs.

1. IPF TLR Client Config
PR: https://github.com/vertelab/odoo-base/pull/346
Usage: 'Update TLR Data' server action inside Contacts.
![tlr_config_server_action](https://user-images.githubusercontent.com/36560391/124571387-5ab7f300-de65-11eb-9896-9bf96b935e3e.png)

2. IPF Deviation Report Client Config
PR: https://github.com/vertelab/odoo-outplacement/pull/263
Usage: 'Deviation Report' in Outplacement
Added message in Log file for error. Please let me know if need to add in logger and need to send email also which is configured as system_parameter_to_send_api_error - team-crm@arbetsformedlingen.se(https://github.com/vertelab/odoo-af/issues/667)

![deviation_report](https://user-images.githubusercontent.com/36560391/124574301-f5b1cc80-de67-11eb-957d-9780857c7168.png)

![deviation_report_popup](https://user-images.githubusercontent.com/36560391/124574299-f3e80900-de67-11eb-86e8-41423d4a925f.png)

3. IPF Final Report Client Config
PR: https://github.com/vertelab/odoo-outplacement/pull/263
Usage: 'Send Report' in Outplacement
Added message in Log file for error. Please let me know if need to add in logger and need to send email also which is configured as system_parameter_to_send_api_error - team-crm@arbetsformedlingen.se(https://github.com/vertelab/odoo-af/issues/667)

![ipf_final_report_client_config](https://user-images.githubusercontent.com/36560391/124577725-26473580-de6b-11eb-8f50-7c550ec53015.png)

4. IPF Showorder Client Config
PR: https://github.com/vertelab/odoo-sale/pull/25
Usage: Cron - Check for Outplacement Order Update
Server action - Uppdatera_order_från_Ordertjänsten

![update_order_action](https://user-images.githubusercontent.com/36560391/124581226-87bcd380-de6e-11eb-9e83-35dd982d91a5.png)

![outplacement_order_cron](https://user-images.githubusercontent.com/36560391/124581235-89869700-de6e-11eb-8257-84b66dd20cec.png)

5. IPF Interpreter Client Config
No Usage

6. API Raindance Client Config
PR: https://github.com/vertelab/odoo-api/pull/20
Usage: Cron 'Check for Outplacement Invoices'
![cron_outplacement_inv](https://user-images.githubusercontent.com/36560391/124584364-c738ef00-de71-11eb-804e-da3e81c8a994.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Anushalewis** [comment]
@rupareliyahemangi145 : Please find attached the test results . There is an error on IPF Showorder Client Config
[Test results AFC-2560.docx](https://github.com/vertelab/odoo-af/files/6799855/Test.results.AFC-2560.docx)

**Comment by rupareliyahemangi145** [comment]
Can you attach full error message?

**Comment by Anushalewis** [comment]
@rupareliyahemangi145  : Please find attached the error : 
[2560 server error.txt](https://github.com/vertelab/odoo-af/files/6806688/2560.server.error.txt)

**Comment by rupareliyahemangi145** [comment]
Thanks @Anushalewis

**Comment by rupareliyahemangi145** [comment]
Hello @Anushalewis 

Can you please check that where you are testing, there is latest code with this PR https://github.com/vertelab/odoo-sale/pull/25?
And you are facing error with this latest code.

**Comment by rupareliyahemangi145** [comment]
Hello @Anushalewis  and @FredrikArvas 

I've created following PRs for to fix errors:
https://github.com/vertelab/odoo-base/pull/350
https://github.com/vertelab/odoo-api/pull/22
https://github.com/vertelab/odoo-sale/pull/26
https://github.com/vertelab/odoo-outplacement/pull/276

Please check it and let me know if anything.

Thanks.
Regards,
Hemangi.

**Comment by Anushalewis** [comment]
@rupareliyahemangi145  : Thank you , working now
