### ISSUE TITLE
AFC-2563 Module Remover for DAFA

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#670]
**Userstory:** 
As a sysadmin I do only want the modules we use to be installed on the system, because it reduces the risk of vulnerabilities

**Suggested solution:** 
A module that removes modules that are not installed from the repository-folders on the server. 

**Step to get there:** 
Add a Server Action to remove modules from the "Apps list" that are selected.
Add a Scheduled Action to run the Server Action automatically.

**Module name:** 
https://github.com/vertelab/odoo-server-tools/servertools_module_remover

**Development Branch name:** 
https://github.com/vertelab/odoo-server-tools/tree/12.0-AFC-2563_Module_Remover

**Target Branch name:** 
https://github.com/vertelab/odoo-server-tools/tree/Dev-12.0-Fenix-Sprint-02

**Module type:** 
Resource module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Login to the Unix-server to see which modules are available on the server.
See the list of available modules in the Apps->tree-view
Install the module
Select one module -> Action -> "Remove Selected Modules from Server"
Run Scheduled Action Manually
Download the repositorys again
Wait until the Schedule Action runs automatically

**Description to the manifest:** 
This module adds a Server Action to remove modules that are not used from the server. It is done to reduce the risk of having vulnerabilities entered to the system without notice.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 40 mins to check possibilities and on discussion.
2 hour and 10 mins - Added module to remove module code from server.
40 mins - Tried to find way to remove folder without informing git.
40 mins - worked on Nil's comment

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've some questions for this issue.

We just need to remove module from APP list only we want to remove file store of that module from system if any file store exits?
We will remove module which are installed or uninstalled or both?

I've an idea to remove module from APP list. And idea is we can add flag 'Active'. So if user click on 'Remove module' server action it will uninstall module if installed and set active false.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 

The important thing is to remove them from the server and then update the "modules list". 
it is not enough to remove them from the modules list.

It should not remove installed modules.

**Comment by rupareliyahemangi145** [comment]
Ok @fredrikarvas-vertel Understood thanks.

We want module in repo but want to remove source code of module from server and module list.

**Comment by fredrikarvas-vertel** [comment]
yes

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I found a way to remove module from server but I have one more question that:
Is there any possibility that we have more than one database on server and you want to remove module for one database only?

**Comment by fredrikarvas-vertel** [comment]
Good question @rupareliyahemangi145 
In this case, I still want to remove the unused modules, since we will only have the same modules in all databases on that server. 
Thanks

**Comment by rupareliyahemangi145** [comment]
If we remove module from server using one database and that module is installed on another database then it will create problem where module is installed.

If module is uninstalled in all database then we just need to Update app list on another databases.

**Comment by fredrikarvas-vertel** [comment]
In this case, I am willing to take the risk of removing the module and risking to disturb the other databases. 
(We should not have different databases on the production server.)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-server-tools/pull/8 for this issue.
Here is video to show how it works:
https://www.loom.com/share/b24cd3bf5dd945c6b34f58443895a32c

I have recording issue in loom account so recorded video in other app and uploaded it on loom.

We have to give path of parent directory in System parameter. In my case I have added all repos in **Fenix** folder so I given path based on that. In **Fenix** folder I have all repos like odoo-outplacement, odoo-sale, odoo-base etc.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
