### ISSUE TITLE
AFC-2568 Make Gender to a mandatory field 

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#675]
**Bugreport:** (only for Bug-Issues)
When the "Desired Gender"-field is empty, then the "Delivery" API will not accept an delivery.

Please make the Gender-field editable again 
odoo-outplacment/outplacment_order_interpreter.interpreter_gender_preference
![image](https://user-images.githubusercontent.com/61729317/124592827-2c82e500-de5e-11eb-9f05-1ddce27c4f18.png)

https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter/views/mail_activity_views.xml

**Development Branch name:** 
Dev-12.0-AFC-2568-gender_preference_fix

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02

**Test-steps:**
Install the module...
admin / admin
Go to Interpreter-bookings
Edit a booking
The Gender-preference should be editable.

**Description to the manifest:** 
Adds edit-options to the Genderfield if it was empty-

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 40 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/265 for this issue.

Please check it and let me know if anything.

Thanks.

Regard,
Hemangi.
