### ISSUE TITLE
AFC-2505b - create a server action that updates the Jobseeker Category without changing other attributes

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#676]
**Userstory:** 
As a system Owner, I want a ServerAction that updates an attribute of the Jobseeker without chaning other Attributes.

Daniel have made an example of such a Server Action: 

Usage: Selecte records in a Tree-view. Run Action. 
Response: Update the JobSeekerCategory, without updateing all other values.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 30 mins
40 mins - Created PRs and tested again. 

# This server Action is to update an order.

PRODUCT_MAPPING = {
    166: "sale_outplacement.startersattning",
    167: "sale_outplacement.slutersattning",
}

client_config = env["ipf.showorder.client.config"].search([], limit=1)
if not client_config:
    raise Warning(_("No client config for showorder integration"))
if not client_config.url:
    raise Warning(_("No url configured for showorder client config"))
if not client_config.client_id:
    raise Warning(_("No client_id configured for showorder client config"))
if not client_config.client_secret:
    raise Warning(_("No client_secret configured for showorder client config"))

# find outplacements to send to ordertjänsten

for outplacement in records:
    # send request
    res = client_config.get_order_id(outplacement.name)
    order_status = res.get("orderstatus")
    if not order_status:
        raise Warning(_("Error in communication with ordertjänsten"))

    outplacement_stage = env["outplacement.stage"].search(
        [("ordertjansten_status", "ilike", order_status)], limit=1
    )
    if not outplacement_stage:
        raise Warning(
            "Unmapped status from ordertjänsten: order status = %s"
            % order_status
        )
    else:
        # TODO: Decide if we should update outplacement stage in more cases
        if outplacement_stage == env.ref("outplacement.cancelled_stage"):
            outplacement.write({
              'stage_id': outplacement_stage.id,
              'interruption': True,
              'service_end_date': datetime.date.today()
            })
        if outplacement_stage.order_id_state:
            order = outplacement.order_id
            if order:
                order.write({'state': outplacement_stage.order_id_state})
                confirm_date = res.get("definitivDatum", False)
                if confirm_date:
                    order.write({'confirmation_date': datetime.datetime.strptime(
                        confirm_date, "%Y-%m-%d"
                    )})
                for order_line_ext in res.get("artikelList", []):
                    tlr_id = order_line_ext.get("tlrId")
                    for order_line in order.order_line:
                        order_line_product = env.ref(
                            PRODUCT_MAPPING[tlr_id]
                        )
                        if order_line.product_id == order_line_product:
                            order_line.write({
                              'price_unit': order_line_ext.get("nuvarandeAPris", 0)
                            })
                            break

            else:
                raise Warning(
                    "Outplacement does not have a sale order: %s"
                    % outplacement.name
                )
        else:
            raise Warning(
                "Unmapped saleorder status: outplacement.stage = %s"
                % outplacement_stage
            )

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I have discuss this issue on call. So please let me know when you can.
Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here is video to show how server action works to update Jobseeker category from contacts.
https://www.loom.com/share/79c5bef75aaf4eeda8cbea23e7a49d55

Files which I've changed for it are:
[partner_view_360_DAFA.zip](https://github.com/vertelab/odoo-af/files/6776007/partner_view_360_DAFA.zip)
[outplacement_crmsync.zip](https://github.com/vertelab/odoo-af/files/6776009/outplacement_crmsync.zip)

Modified files are:
       To add Jobseeker Category in Contact form view:
	modified:   partner_view_360_DAFA/__manifest__.py
	modified:   partner_view_360_DAFA/views/res_partner_views.xml
       To add new server action:
	modified:   outplacement_crmsync/data/data.xml
	modified:   outplacement_crmsync/models/res_partner.py

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 
I think it is best to add these changes to a normal PR and add it to the server. Then we can remove the code again when it is not needed. 

Please make a comment in the code where you have added stuff with a note: 
"Temporary fix to update jobseeker category. Should be removed before 2021-SEPT-01"

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here is PRs for this issue:
https://github.com/vertelab/odoo-base/pull/348
https://github.com/vertelab/odoo-outplacement/pull/268

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
