### ISSUE TITLE
AFC-2576 - Error when sending a GP

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#677]
**Bugreport:** (only for Bug-Issues)
Error message when sending GP

1: When sending a GP, the sent date is a mandatory field. Please add that to the payload when sending it. 

![image](https://user-images.githubusercontent.com/61729317/124822214-e9b13200-df6f-11eb-9736-c98e47b227c6.png)

2: When sending a successful GP (response 201), we want the message "GP has been sent" to be displayed. It is currently saved to the chatterlog when the date of the "GP sent" is added, not when the GP is sent.
![image](https://user-images.githubusercontent.com/61729317/124821757-61cb2800-df6f-11eb-9a47-3004825e1ec4.png)

**Module name:** 
odoo-outplacement/outplacement_joint_planning

**Development Branch name:** 
Dev-12.0-Fenix-AFC-2576-error_on_sending_jp

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hour and 20 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by fredrikarvas-vertel** [comment]
Thanks, I have not added the right modules and repos yet, but I think you can add that.

**Comment by rupareliyahemangi145** [comment]
Yes I will add that.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/266 for this issue.
Done things:
1. Added full error message on email if response not equal to 201.
2. Prevent error email if response 201.
3. Set target to open record in new tab from email record.

I can't reproduce response 201 in local but I think this code will work.
Please let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Please display this error message to the user: 
Manual: 
EN: Meeting type for outplacement not set.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created new PR https://github.com/vertelab/odoo-outplacement/pull/267 for menu name and User warnings.

Please check it and let me know if anything.

Thanks.
Regards,
Hemangi.
