### ISSUE TITLE
AFC-2581 Add "Dynamic Time Ranges" to filter in Interpreter- and Outplacement-search views

### ISSUE THREAD

**Issue by Anushalewis** [vertelab/odoo-af#679]
Userstory : Please add Dynamic Time Ranges to the filter on the Outplacement and Interpreter pages.

As a user of dafa, I would like to filer and group on time ranges for 
1. Outplacements 
2. Interpreter-bookings

Illustrations of the existing system
![image](https://user-images.githubusercontent.com/84374527/124947399-161c8b00-e010-11eb-9033-da746a0cdefe.png)

Illustration of proposed changes ,Add the time sheets on filter of below pages

![image](https://user-images.githubusercontent.com/84374527/124947714-61cf3480-e010-11eb-8ccd-47c2012ddd60.png)
External Id : outplacement.outplacement_filter_view

![image](https://user-images.githubusercontent.com/84374527/124947788-714e7d80-e010-11eb-9785-bd7a465c9c8a.png)
External Id : outplacement_order_interpreter.mail_activity_search_view_for_interpreter_booking

Module name:
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement/
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter/

Development Branch name:
Dev-12.0-DAFA-AFC-2581_Crete_Time_sheets_for_Interpreter_and_Outplacement

Target Branch name:
https://github.com/vertelab/outplacement /tree/Dev-12.0-Fenix-Sprint-02

Test-steps:
Install the module...
Login and select the filter drop down  and select Outplacement that were created in a time-range
Login and select the filter drop down  and select Interpreter Bookings that were created in a time-range

Description to the manifest:
This user story adds dynamic time range on filter on Outplacement and Interpreter views for ease of use for the user.

Estimate: (@Developers: Add your times here, not in comments please)
Estimated Hours:
Estimated Date:
Actual Hours: 1 Hour and 10 min

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas 
I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas

Please check this video for this issue. Then I will create PR based on feedback.
https://www.loom.com/share/57cdb8b26c454ec7ac8215eea168464d

Thanks.

Regards,
Heamangi.

**Comment by fredrikarvas-vertel** [comment]
Thanks. 
This is fine like this!

**Comment by rupareliyahemangi145** [comment]
Ok Thanks @FredrikArvas I will create PR for this.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Here is new PR for translation of filters.
https://github.com/vertelab/odoo-outplacement/pull/270

Please check it.

Thanks
Regards,
Hemangi.

**Comment by Anushalewis** [comment]
Test results : 
[Test Results AFC-2581.docx](https://github.com/vertelab/odoo-af/files/6966253/Test.Results.AFC-2581.docx)

**Comment by rupareliyahemangi145** [comment]
Ok @Anushalewis I will check it.

**Comment by Anushalewis** [comment]
Hi @rupareliyahemangi145 : Works as expected , please find the updated test results. this issue can be closed.
[Test Results AFC-2581.docx](https://github.com/vertelab/odoo-af/files/6973033/Test.Results.AFC-2581.docx)
