### ISSUE TITLE
AFC-2585 - Add second coach (SYV) to Outplacement

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#682]
**Userstory:** 
As a second coach ("SYV"), I want add my name to an outplacement, because there is always one Coach and one SYV working with a participantn.

Add EN: SYV SV: SYV
![image](https://user-images.githubusercontent.com/61729317/125207425-9f3ff600-e28c-11eb-8590-fd0e51e5f8c8.png)
![image](https://user-images.githubusercontent.com/61729317/125207501-dc0bed00-e28c-11eb-8914-67f378f2d343.png)
![image](https://user-images.githubusercontent.com/61729317/125207509-ecbc6300-e28c-11eb-9f2e-b1241e6151bc.png)
Change Emploee to EN: "Coach" SV: Handledare
Add EN: SYV SV: SYV

**Module name:** (added by Nils or Fredrik)
odoo-outplacment/odoo_outplacment

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create PR https://github.com/vertelab/odoo-outplacement/pull/274 for this issue.

Please check it and let me know of anything.

Thanks.

Regards,
Hemangi.
