### ISSUE TITLE
AFC-2586 - The customer is displayed incorrectly

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#683]
**Bugreport:** (only for Bug-Issues)
![image](https://user-images.githubusercontent.com/61729317/125209256-e1226980-e297-11eb-9fb8-b9e222311cb3.png)

![image](https://user-images.githubusercontent.com/61729317/125209278-fa2b1a80-e297-11eb-95e4-7493298fc29b.png)

![image](https://user-images.githubusercontent.com/61729317/125209285-0ca55400-e298-11eb-8ac2-da4fe53e4a57.png)

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 40 mins

**Comment by rupareliyahemangi145** [comment]
Hello @Anushalewis

Can you please add AFC-number for this issue?

**Comment by Anushalewis** [comment]
Hello @rupareliyahemangi145 
Am not able to edit the git issue , the jira story for this is : AFC-2586

**Comment by rupareliyahemangi145** [comment]
Np @Anushalewis Fredrik has changed.

**Comment by Anushalewis** [comment]
@rupareliyahemangi145 : 
Module Name : https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_invoice/views/account_invoice_view.xml

Development Branch name:
Dev-12.0-AFC-2586-The_customer_is_displayed_incorrectly

Target Branch name:
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

Description to the manifest : 
The Customer name in the invoices should be displayed correctly.
Currently it displays the city name which has to be corrected for ease of use.

**Comment by rupareliyahemangi145** [comment]
Ok @Anushalewis Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/275 for this issue.

![invoice](https://user-images.githubusercontent.com/36560391/125264711-b846b680-e321-11eb-9d03-4b9f4d8851ad.png)

Please check it and let me know if anything.

Thanks.
Regards,
Hemangi.
