### ISSUE TITLE
AFC- 2375 Add display of Quicklinks for partners to a menu

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#684]
**Userstory:** 
As a user I want to see the links in an menu in the normal menu position 
1 Contacts 
![image](https://user-images.githubusercontent.com/61729317/125255020-4f4c4800-e2fb-11eb-9b30-3200e8a8171e.png)

2 My admin-area search
![image](https://user-images.githubusercontent.com/61729317/125255092-5e32fa80-e2fb-11eb-8e87-ed9c63082c61.png)

3 Jobseeker Formview
![image](https://user-images.githubusercontent.com/61729317/125255208-7a369c00-e2fb-11eb-86cd-88ffd4184e03.png)

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-af/blob/Dev-12.0/contact_links/

**Development Branch name:** 
Dev-12.0-AFC-2375

**Target Branch name:** 
https://github.com/vertelab/odoo-af/blob/Dev-12.0/contact_links/

**Description to the manifest:** 
AFC-2375 Adds a menu with the partner-links in Contacts and Jobseeker views.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours
20th July - 30 mins - Checked possibility to add new column in view for links.
29th July - 30 mins - Checked possibility to add new column in view for links.
29th July - 1 Hour and 20 mins - Listed links in column with link image, name and url.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Can we discuss this issue on call?

**Comment by fredrikarvas-vertel** [comment]
yes
 I will available in 10 minutes - do you have time then?

**Comment by rupareliyahemangi145** [comment]
Yes @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Suppose we have one link: Planeringsverktyget
URL link for this link is: http://ivs.arbetsformedlingen.se/etjanst/planeringsverktyg/#/start/bedomning/{clean_pnr}
So you want to redirect user to http://ivs.arbetsformedlingen.se/etjanst/planeringsverktyg/#/start/bedomning/ when user click on menu?
Or we have to put value in {clean_pnr}?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've create Pr https://github.com/vertelab/odoo-af/pull/685 for this issue.
I've added server action that will create menu for each link.
https://www.loom.com/share/ff7dd05db70d404fb2049b186c9b6a6e

For now I've just redirected static url and added server action to create menu for each link.
If this is ok then we will update code to create menu automatic when new link created and to update URL in exiting menu when url changes in link.

Please check it and let me know if anything.

Thanks.
Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 Please see how we can do those links dynamic.

**Comment by rupareliyahemangi145** [comment]
Need to find place in Partner form view to show list of links so we can get value in URL from partner fields.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 is it possible to add a extra column in the standard view?

**Comment by rupareliyahemangi145** [comment]
I will check it @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I checked possibility to add column in standard view. We can add column like this:
![contact_view](https://user-images.githubusercontent.com/36560391/127439586-2a9b0147-cbb4-48c5-a0c0-94a9a8421312.png)

We have to add one compute HTML field that will list URls, for now I just added 123,123 etc. I've added it on right side but we can add it on left side. I tried to add it outside the form view but didn't found way for that.

Please check it and let me know if anything.
Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Great!
could you see if you can display links from the odoo-base/partner_links-module there?

**Comment by rupareliyahemangi145** [comment]
For that we have to add one HTML compute field or need to check why widget is not working on this place?

I checked odoo-base/contact_links module, it uses widget to list links on **Links** tabs. I tried same widget in new place column but it doesn't work.

**Comment by fredrikarvas-vertel** [comment]
Could you use the same table of links and display them in the new computed fields (somehow)?

**Comment by rupareliyahemangi145** [comment]
Yes @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've tried to add column that list contact links like it is in tab.
Here is video to show result:
https://www.loom.com/share/a1ed9c9436dc40f1b2ad770737f89da7

Please check it when you can and let me know if anything.

Thanks.
Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
This looks really promising!
@Radhika435 Could you please forward this video to Anders Hagström?

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas
