### ISSUE TITLE
AFC-2593- Refined Interpreter cancellation message

### ISSUE THREAD

**Issue by Anushalewis** [vertelab/odoo-af#687]
User story : As a user of dafa , would like the interpreter cancellation message to have interpreter contact information when there is an appointed interpreter as displayed in the screen shots

Steps to replicate the issue :
• On the Interpreter page, select activity cancel.

Please refer the below images to replicate the issue :
![image](https://user-images.githubusercontent.com/84374527/125569202-8ce8c0f8-59d6-4d2e-84b9-3f683323d565.png)

Expected changes
Scenario 1: There is an appointed interpreter
![image](https://user-images.githubusercontent.com/84374527/125569281-1b789221-182a-4399-a437-604e938ea5d6.png)
Please call the interpreter and cancel the booking.
Interpreter's name: XN
Telephone no: 070

Also send another email team-crm@arbetsformedlingen.se and enter reference no 123 and current KA-no: 123123
![image](https://user-images.githubusercontent.com/84374527/125569315-25dad083-f1c9-402d-99da-07f5a02ec549.png)

Scenario 2 : There is No appointed interpreter
 ![image](https://user-images.githubusercontent.com/84374527/125569418-3f2cf2e7-96d4-465b-b6c4-28de04055db4.png)
Also send another email team-crm@arbetsformedlingen.se and enter reference no 123 and current KA-no: 123123
![image](https://user-images.githubusercontent.com/84374527/125569449-d3f0e79b-96d0-405f-b946-b856d3b3fcdb.png)

External id : project.view_task_form2

Module name:
https://github.com/vertelab/odoo-outplacement/blob/f764ad317ae342a7bbaf77c0b4454acf70b2118e/outplacement_order_interpreter/static/src/js/activity.js#L36

Development Branch name:	
Dev-12.0-AFC-2593- Refined Interpreter cancellation message

Target Branch name:
https://github.com/vertelab/ odoo-outplacement /tree/Dev-12.0-Fenix-Sprint-02/

Test-steps:
Step1  : Install the module , Select Interpreter page, edit activity
Step 2 : Cancel the activity
Step 3 : The cancellation notification should have interpreter information if there is an interpreter assigned to the case.

Description to the manifest:
This user story adds interpreter information on the booking cancellation page (if there is an interpreter assigned) on the outplacement final report for ease of user.

Estimate: (@Developers: Add your times here, not in comments please)
Estimated Hours:
Estimated Date:
Actual Hours: 50 mins - Added name and number on message. Researched to add deliver button.
1 Hour and 20 mins - Created new PR. Added button to deliver booking. Change button label and layout.
1 Hour and 10 mins - Added if condition to remove false on Interpreter name and phone and to show if value exits in interpreter name and phone.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  or @Anushalewis 

Can we do short call for this issue?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/283 for this issue.
Added Phone number and Name in booking cancellation message.
![popup](https://user-images.githubusercontent.com/36560391/125767219-17dd0d24-6478-4423-9609-efc7fc71111a.png)


I also researched to add new button for deliver booking. We can add new button and open popup which is now on **Inleverera tolk**.

Please let me know if you want me to add that button and also let me know name of the button.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
1 Please change the swedish wording from "två steg" to "tre steg"
2 Remove the current blue button. 
3 Add a new blue button which sais with functionality that "delivers the interptrer" "SV: Inleverera tolken". 
4 Add a new white button with a "close function" which sais "Stäng"

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created new PR https://github.com/vertelab/odoo-outplacement/pull/287 for this issue.

Here is result:
![popup](https://user-images.githubusercontent.com/36560391/125948482-fc30c35a-9fec-4247-b950-49ef323abd13.png)

Deliver popup after click of Inleverera tolken.
![popup_after_click](https://user-images.githubusercontent.com/36560391/125948552-8a8acfb3-0562-4f07-b862-031ef94332a8.png)

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.
