### ISSUE TITLE
 AFC-2596 to 'Change the response when interpreter is delivered'

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#688]
userstory: 

1 Change Interpreter-view Action to: 
['|', ('active', '=', True), ('active', '=', False)]

2 
when the interpreter is deliverd by AF, the API responds with:
"x"
Please adjust our logic to treat that as a "success" of delivery and "hide the delivery button"

 ![image](https://user-images.githubusercontent.com/61729317/125571035-6db63ff9-296f-47e2-8fd5-200cb137dfca.png)

**Userstory:** 
As a user, I want/do ...., Because... 

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 10 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created Pr https://github.com/vertelab/odoo-outplacement/pull/279 for this issue. _ Merged

Please check it and let me know if anything.

Thanks.
Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Thanks

Is there a api-log for the interperter-bookings - as there are for other APIs?

**Comment by rupareliyahemangi145** [comment]
I will check it and let you know @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Yes there is log for interpreter booking.
1. When creates activity.
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter/models/mail_activity.py#L610

2. From Cron 'Check status on Interpreter Order'
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter/data/cron.xml#L4
https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter/models/mail_activity.py#L641

**Comment by fredrikarvas-vertel** [comment]
Is that log visible somewhere?

**Comment by rupareliyahemangi145** [comment]
Yes if error message is added with **_logger.error** or **_logger.exception** or **_logger.warning** then you can see it in log file.

If error message is added with _logger.debug then you can see it if in Odoo config log_level=Debug.
