### ISSUE TITLE
AFC-2612 -add links to interpreter API-logs

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#689]
**Userstory:** 
As a user, I want see the interpreter logs in the same way as I can see the other logs.

**Screen-shots old GUI:** (illustrations of the old system)
Move from here: 
![image](https://user-images.githubusercontent.com/61729317/125735232-9a8fef6a-5af2-4be9-bc09-a85e0df02401.png)

To here: 
![image](https://user-images.githubusercontent.com/61729317/125735068-a73ba72a-6866-4983-b685-04692a441285.png)

**Description to the manifest:** 

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours and 50 mins

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I checked this issue. We can add API-logs but it will take near about 4 to 5 hours.
So I need approval for 4 to 5 hours.
Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
I approve this change.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 
Can you please add AFC number for this issue?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created Pr https://github.com/vertelab/odoo-project/pull/34 for this issue.
I renamed previous **IPF Interpreter** to **IPF interpreter Test**(ipf.interpreter.client.test) and Added new menus **IPF Interpreter**(ipf.interpreter.client which was in general setting).
I am not able to test it. Please test it from your end and and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Anushalewis** [comment]
Testing completed working as expected .
[Test results AFC-2612.docx](https://github.com/vertelab/odoo-af/files/6840311/Test.results.AFC-2612.docx)

**Comment by rupareliyahemangi145** [comment]
Thanks @Anushalewis
