### ISSUE TITLE
AFC-2600 - Requried fields-messages in Final Report does not show for the users

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#690]
**Userstory:** 
As a user, I want/do ...., Because...
![image](https://user-images.githubusercontent.com/61729317/125735844-e38968aa-90d6-40af-b633-a46448ce2bc1.png)

![image](https://user-images.githubusercontent.com/61729317/125735809-667b1ea8-8bc8-47cc-a17b-1afce64162f5.png)
 

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created Pr https://github.com/vertelab/odoo-outplacement/pull/282 for this issue.

Please check it and let me know if anything.
Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I checked for GP there is only two onscreen fields warnings which we have added already.
So, nothing to do for GP now.
