### ISSUE TITLE
AFC-2613 - make interpreter steps similar in all parts of the system

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#694]
Userstory: As a user of the system, I want to know that all my bookings are included in the searches and the statuses. 
Please use one definition of statuses (or if it is nessesary one defintion and various ways of calculating them)

1 Please add an extra field "manual_cancelled_date" with the date of the cancelletion is added. 

Please add a cancellation-date when an "interpreterbooking is delivered before the interpreterdate" or when the "close"-button is pushed before there is an interpreter assigned.
We could change the name of that button to "EN: Mark as cancelled", "SV: Markera som avbokad"

2 Here is a list of statuses I see we have: 

https://github.com/vertelab/odoo-outplacement/blob/d2f7dc6272321edada40a7b8483eddde272f5e12/outplacement_order_interpreter/models/mail_activity.py#L348
statuses =  

I have added # for changes to the defintion in Odoo Tray.
I have added ## for the delivery-action.

'1': _('EN: Order received, SV: Order mottagen'), # Change to "Order Recieved" i Odoo Tray. ## no delivery button
'2': _('EN: No available interpreter, SV: Ingen tillgänglig tolk'), # Change to "No available Interpreter" i Odoo Tray. ## No delivery button
'3': _('Order received'), # Change to "EN: Order in Process, SV: Ordern behandlas" in Odoo Tray ## no delivery button
'4': _('EN: Interpreter Booked, SV: Tolk bokad'), ##  delivery button after the time has passed.
'5': _('EN: Cancelled by Interpreter, SV: Avbruten av Tolkleverentören'), [Cancelled by Interpreter] ## automatic delivery (without extra time) when the "cancel interpreter window is closed". 
'6': _('EN: Cancelled by AF, SV: Avbokad via Arbetsformedlingen')} ## automatic delivery (without extra time) when the "cancel interpreter window is closed". 

3 Please make the "interpreter button" work the same way both for the "case worker" and the "interpreter accountant".

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:
1 Hour and 50 mins - Updated code to change filters on odoo tray and Search views.
2 Hours and 40 mins - Tested interpreter steps from every place and updated needed code to make it working.
1 Hour - Added translation, Prepared video and pushed code.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I want to discuss this issue on call. So Please let me know when you can.
Thanks

Regards,
Hemangi

**Comment by rupareliyahemangi145** [comment]
Questions need to discuss on tomorrow morning:

1. Is this same that Cancel button on cancellation popup and need to save date in new field? Also want to show functionality which I've added for cancel date.
= Yes

2. Understood need to search and Odoo tray widget with same filter as now values in Booking status.
Don't understood this line : automatic delivery (without extra time) when the "cancel interpreter window is closed".
= I want automate the "delivery"-function to when the case worker cancels the meeting if theres is no interpereter assigned.

3. Are you facing any error from Interpreter account or Case worker? I think logic is same for both.
= Good. I do not see any difference. 

Ok @FredrikArvas Thanks

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've added commit on PR https://github.com/vertelab/odoo-outplacement/pull/294 to update booking filter on Odoo tray and search views.
Here is video for result:
https://www.loom.com/share/a6fb9a33551c41cea58d6c8c76181ccc

After latest pull we have to execute one server action from Task and need to execute one cron job. I have mentioned it in video.
Please check it and let me if anything.

I will add one more commit in same PR for translation. For now I skipped automate delivery when cancel because we have added log only on cancel.

Thanks.
Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 
I've added https://github.com/vertelab/odoo-outplacement/pull/294/commits/65fcd28130e316b5da072e3f023f73d6d4f131e6 for translation.
