### ISSUE TITLE
AFC-2614 - do not show delivery button when there is no available interpreter in "cancel-message"

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#695]
**Userstory:** 
do not show delivery button when there is no available interpreter in "cancel-message"

![image](https://user-images.githubusercontent.com/61729317/126058311-7c996e4d-c715-4061-a666-ad7138371d9e.png)

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 30 mins - Hide button based on condition
40 mins - Added button to cancel booking.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/289 for this issue.
Please check it and let me know if anything,

Thanks.
Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Please add a cancellation-date when an "interpreterbooking is delivered before the interpreterdate" or when the "close"-button is pushed before there is an interpreter assigned.
We could change the name of that button to "EN: Mark as cancelled", "SV: Markera som avbokad"

**Comment by rupareliyahemangi145** [comment]
> Please add a cancellation-date when an "interpreterbooking is delivered before the interpreterdate" or when the "close"-button is pushed before there is an interpreter assigned.
> We could change the name of that button to "EN: Mark as cancelled", "SV: Markera som avbokad"

Added this point on AFC-2613 https://github.com/vertelab/odoo-af/issues/694 as Point no. 1
