### ISSUE TITLE
AFC-2615 - Adjust Final Report Send-date to +1 instead of +41 after Service End Date

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#696]
**Userstory:** 
As a user, I want/do ...., Because... 

**Bugreport:** (only for Bug-Issues)
![image](https://user-images.githubusercontent.com/61729317/126058565-19ca2283-3360-4db8-a0a8-6ae5d1dffad5.png)

Change this in "sale_outplacement.outplacement_form_view" 
from: 

to

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 hours

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

When we want to raise this warning? or you want me to remove this warning?
You are not allowed to send final report before service end unless there has been an interruption

**Comment by fredrikarvas-vertel** [comment]
Hi @rupareliyahemangi145 
I think I would like the controls to take place in this order: 
1 Joint Planning date is set. 
2 Service Date is passed (this will be when interruption signal has been recived by the Order API and the "service_end_date" is updated or the "original" service_end_date has passed)
3 Main goal has all attributes
4 Alternative goal has all attributes
5 the remaining attributes are filled in

So:  "You are not allowed to send final report before service end unless there has been an interruption" is the message for step 2.

ok?

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas 

It means Interpreted check box is checked and Service end date is passed at that time we have to show this warning, right?

**Comment by fredrikarvas-vertel** [comment]
The "interrupted"-check box is also set by the "Order-API" when the status is changed to "cancel" so it is ok to only check the "service_end_date". 

The new API "BAR Handelser" will replace the order-api to listen changes on the BÄR-side when we are ready for that. 
Now we set the date at the day we see the signal (when the API is working), not the actual value. But this is the best we have now.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check only service end date.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/290 for this issue.
Please check it and let me know if anything.

One more thing I have to confirm with you related to final report. We have one more warning, **The Final Report can only be sent after the Service has ended.** We raised this warning in following conditions:
1. If Outplacement is in Cancelled stage **Or**
2. 40 days are passed after service end date

Is this right or need to change logic of this also?

**Comment by fredrikarvas-vertel** [comment]
Thanks @rupareliyahemangi145 
I think you found the bug. 
This should only check for service_end_date, since we now now that BÄR changes the service_end_date to the day of cancellation if there is a cancellation

The stage cancelled will only be set in DAFA when there is an early ending. This is good for "statistics" but not important to us.

**Comment by rupareliyahemangi145** [comment]
So, May I remove this warning?
**The Final Report can only be sent after the Service has ended**

**Comment by fredrikarvas-vertel** [comment]
No, not unless we have two warnings for ServiceEndDate

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've Created new PR https://github.com/vertelab/odoo-outplacement/pull/291 

Please check it and let me know if anything

Thanks
Regards,
Hemangi
