### ISSUE TITLE
AFC-2627 -"Preferred Gender" is a mandatory field, but it is allowed to be empty

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#700]
**Userstory:** 
as a Interpreter booker, I do not want an error when delivering the interpreter, for an error I can not affect. 

![image](https://user-images.githubusercontent.com/61729317/126608133-26514ff2-fabc-4ed7-a912-626e0d5728a3.png)

Please adjust the following: 
1 In the API, add the code= 1 ( "Valfri")  if the field mail_acitivity.interpreter_prefered_gender is empty
2 in the booking form: Default "Valfri" when booking a new booking.
Change this code: 
<field name="interpreter_gender_preference" attrs="{
                            'readonly': [('interpreter_booking_ref', '!=', False)],
                            'required': [('activity_type_id', '=', 8)],
                            'invisible': [('activity_type_id', '!=', 8)]}" options="{'no_quick_create': True, 'no_create_edit' : True}"/>

To Default to "code 1, valfri" and make Editable

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 10 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've pushed code for this issue in PR https://github.com/vertelab/odoo-outplacement/pull/294 and https://github.com/vertelab/odoo-project/pull/35.

Please check it when you can and let me know if anything.
Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment]
@fredrikarvas-vertel 
How can the Interpreter preference be set to **valfri** by default? Do the case workers change it manually on the job seeker card (outplacement) or do DAFA receive it from the order?

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 I think we get the value "valfri" (optional) in many times from the API. 
Could you confirm that you have added that value if it is missing?

**Comment by rupareliyahemangi145** [comment]
Yes Sure @FredrikArvas 
I can't test it on my local but here is code for that:
https://github.com/vertelab/odoo-project/pull/35
