### ISSUE TITLE
AFC-2628 AFC-2630  AFC-2631 AFC-2632   Interpreter Fixes

### ISSUE THREAD

**Issue by rupareliyahemangi145** [vertelab/odoo-af#701]
**Userstory:** 

1.  Issue with Next execution date after upgrading modules.
![Scheduled_Action_GetsWrongDate_WithNewPod](https://user-images.githubusercontent.com/36560391/126635609-07f0127a-d686-4e7b-99f1-74f813f8242b.JPG)

2.  If Interpreter deliverd by another user than show messge that this delivered and update booking status to Delivered
![Interpreter_Delivered_By_Another_user_is still_in_state_NotDeleiverd](https://user-images.githubusercontent.com/36560391/126635717-7f6577d8-a679-4a82-acb3-6a18ef653d0d.png)

3. Make this message to one line
![PleaseMakeInterpreterError_to_a_OneLiner](https://user-images.githubusercontent.com/36560391/126635921-0e03e446-c1cb-4612-bfca-330de7741338.JPG)

4. Log message when system cron job sending mail
![LogMessage-Error_about_email](https://user-images.githubusercontent.com/36560391/126635981-31ecbf74-e5f8-406f-9a1a-6ace61dd0d3a.JPG)

5. Booking is delivered in chatter log but status is not updated
![Interpreter_Delivery_Status_not_updated-in-all-places](https://user-images.githubusercontent.com/36560391/126636127-afc82537-f3c1-48fa-86ff-839939fb9a45.JPG)

6. For all API request history
Add group by Response code, Url in search and Filter & group by for Create date(When developer mode active)
Remove Config ID and URL from List view
Add form view
![Add_Search_parameters_to_search_box](https://user-images.githubusercontent.com/36560391/126636225-86f37235-bd7e-4546-82bd-17822c810a82.JPG)

7. Show only yellow text in popup
![Interpreter_Booking_type_of_distance-interpreter_error](https://user-images.githubusercontent.com/36560391/126636411-738aadd4-4ed5-4f48-b3c1-755cb7048c7a.JPG)

8. Show only yello text in popup
![Interpreter_Booking_Length_error](https://user-images.githubusercontent.com/36560391/126636494-33e80b5f-7959-4b53-8552-2f2458673c39.JPG)

9. Add Dynamic date filter for Interpreter booking
![Add_Interpreter_dynamic_date_filter](https://user-images.githubusercontent.com/36560391/126636539-7a85aab2-7366-429b-a5b0-b1ff5d15dbf6.JPG)

**Screen-shots old GUI:** (illustrations of the old system)

**Screen-shots with changes:** (illustration of proposed changes)

**Screen-shots from development:** (plese add screen-shots of the development in the comment below)

**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 4 Hours and 10 mins
1 hour and 20 mins: For point 2

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR for points except point no. 4 and point no. 2
1. https://github.com/vertelab/odoo-sale/pull/29 (For point no.6)
2. https://github.com/vertelab/odoo-project/pull/35 (For point no. 6)
3. https://github.com/vertelab/odoo-api/pull/24 (For point no. 6)
4. https://github.com/vertelab/odoo-outplacement/pull/294 (For all points)

@FredrikArvas 
For Point no. 2, For now I didn't found way to open popup that will notify user that this is already delivered and then when user click on Ok booking status will go in 'Delivered' stage.
I have to research on that. If we raise popup like it is now then it will not help us to update booking status.

For point no. 4, Could not able to reproduce in local. We have check email from setting in server when error is exits.

@SebastianGieser-Vertel 
Please review all PRs and let me know when we can test together.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
For point 2. could we simply "confirm" delivery (without actual delivery, but only update the status on our side)?

**Comment by rupareliyahemangi145** [comment]
Let me check Fredrik

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've updated code for Point 2 on same PR. We will test this PR once you will back from vacation.
Thanks.

Regards,
Hemangi.
