### ISSUE TITLE
AFC-2640 Interpreter booking and delivery status update.

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#704]
**Userstory:** 
As a user, I wanted to 
1) Book an interpreter and get a confirmation status from the interpreter portal.

2) Status must be changed if the interpreter is confirmed and job coach must see information about the interpreter's name and booking ref. On the picture below we can see there is no information visible about interpreter.
![image](https://user-images.githubusercontent.com/59916603/127299097-04a2c675-cfc0-4c55-8b21-a0494523eafe.png)

3) Job coach or interpreter portal must click on the delivery button (Inlevarera) to "deliver an interpreter when the service has been completed or when the interpreter's order has been interrupted. But job coaches are getting an error message like this.
![image](https://user-images.githubusercontent.com/59916603/127297807-25a653cc-1760-4a20-bbe8-c1912212cfcc.png)

**Module name:** (added by Nils or Fredrik)
odoo-xx/xx_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations used in this module:**

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours

**Comment by Radhika435** [comment]
@rupareliyahemangi145 Please look in to this production issue
Lets connect to discuss in detail

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

We need to check log file of Odoo production server. As per above screenshot it seems like system is not able to take response from API. It could be possible that there is some error in process but don't know where. To know that we have to check log file of odoo server when user creating interpreter booking.

**Comment by SebastianGieser-Vertel** [comment]
I think the access issue is caused by this file on line 3: https://github.com/vertelab/odoo-project/blob/Dev-12.0-Fenix-Sprint-02/task_interpreter_ipf_client/security/ir.model.access.csv
However I'm not sure why it causes this issue, the log file on the server says the same thing:
('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Administration/Settings\n\n(Dokumentmodell: ipf.interpreter.client) - (Operation: read, Användare 78)', None) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)

**Comment by SebastianGieser-Vertel** [comment]
I think something like line 4 from here might be necessary: https://github.com/vertelab/odoo-outplacement/blob/Dev-12.0-Fenix-Sprint-02/outplacement_final_report_ipf_client/security/ir.model.access.csv

**Comment by rupareliyahemangi145** [comment]
Thanks @SebastianGieser-Vertel  Yes its access issue. Let me create PR to fix. Thanks again.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435  and @SebastianGieser-Vertel 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/296 to fix this issue.
Please check it and let me know if anything.

@Radhika435 For exiting booking where no booking reference added, user have to recreate it via Interpreter menu >> Select booking >> Go to Action and Duplicate. First try with new booking if works then recreate one by one with duplicate action.

Thanks.

Regards,
Hemangi.
