### ISSUE TITLE
AFC-2646 - add an uppercase in the password for CIAM

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#708]
We need to change the password requirements to include a uppercase letter compared to now.

**Module name:** 
https://github.com/vertelab/odoo-hr/blob/31f1add30e15312cb41853b05c7cbc5393815345/hr_user_ciam_update/models/ciam_update.py#L71

**Development Branch name:** 
https://github.com/vertelab/odoo-hr/tree/12.0-AFC-2646_password-fix

**Target Branch name:** 
https://github.com/vertelab/odoo-hr/tree/Dev-12.0-Fenix-Sprint-02/

**Description to the manifest:** 
Adds an upper case letter in the automatic password.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this issue.

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 
I just got a response from the CIAM-platform that they can do the change for all Arbetsformedlingens systems. This means we do not need to do this change on our side.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by Radhika435** [comment]
Hello @rupareliyahemangi145 

I am opening this issue again as we got some information from the CIAM platform about the rules that we have to follow while creating the password for the user to log in to the DAFA via CIAM.

We need to **change the automatic generation of passwords to include a uppercase-letter** compared to what we have today.

(The CIAM-rule for passwords as it stands now is 8-64 characters with at least one lowercase letter, at least one uppercase letter, at least one number. Some special characters are also allowed.)


Best regards,
Radhika.

FYI @fredrikarvas-vertel 
I have updated it.

**Comment by rupareliyahemangi145** [comment]
Ok @Radhika435 I will check this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @Radhika435 

Can we call to discuss this issue?

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145  I have done some adjustments in the gitissue. 
Please check again.
:-)

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment]
Ok its clear now. Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-hr/pull/76 for this issue.

Please check it when you can and let me know if anything.

Thanks.
Regards,
Hemangi.
